# Version mapping for Z_RELEASE_VERSION files across release branches
# This file is maintained in the main branch and used by the update-release-versions workflow
# to automatically update Z_RELEASE_VERSION files in each release branch

release_mappings:
  backplane-2.6: "2.6.9"
  backplane-2.7: "2.7.7"  
  backplane-2.8: "2.8.4"
  backplane-2.9: "2.9.2"
  backplane-2.10: "2.10.0"
  backplane-2.11: "2.11.0"
  # Add new release mappings here as needed
  # backplane-2.12: "2.12.0"
