apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-curator-controller?rev=b2427085b024d957d92681df46f5658486c2c4d2
    build.appstudio.redhat.com/commit_sha: b2427085b024d957d92681df46f5658486c2c4d2
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "43489431158"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-qoqiqa
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-curator-controller-mce-29-on-push-5t2k7
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: cluster-curator-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-curator-controller
    pac.test.appstudio.openshift.io/repository: cluster-curator-controller-2kgj
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: b2427085b024d957d92681df46f5658486c2c4d2
    pac.test.appstudio.openshift.io/sha-title: 'ACM-20850: train 28 upgrade hive apis
      (#424)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-curator-controller/commit/b2427085b024d957d92681df46f5658486c2c4d2
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-curator-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-curator-controller
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"mce-29-enterprise-contract-registry-standard-release-mce-29-fxbnq":{"lastUpdateTime":"2025-06-04T18:53:45.512427138Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1749062000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-curator-controller
    test.appstudio.openshift.io/status: '[{"scenario":"mce-29-enterprise-contract-registry-standard","status":"TestPassed","lastUpdateTime":"2025-06-04T18:53:45.512427138Z","details":"Integration
      test passed","startTime":"2025-06-04T18:45:17.538287849Z","completionTime":"2025-06-04T18:53:45.512427138Z","testPipelineRunName":"mce-29-enterprise-contract-registry-standard-ntn76"}]'
  creationTimestamp: "2025-06-04T18:45:17Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: cluster-curator-controller-mce-29-on-push-5t2k7
    appstudio.openshift.io/component: cluster-curator-controller-mce-29
    pac.test.appstudio.openshift.io/check-run-id: "43489431158"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-curator-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: cluster-curator-controller-2kgj
    pac.test.appstudio.openshift.io/sha: b2427085b024d957d92681df46f5658486c2c4d2
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-curator-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1749062710"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-fxbnq
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "4077513528"
  uid: ac1378c4-2adb-45b6-8547-6801cc727913
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:7a20d7023aeaa009471667f2b784c5aec38fe3038640152e47b84fd6780931fa
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: cc0eba5c5d1a042e65ac36898086612b8f638da2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:cfa689df1f551eaef0d846c419dfea31b020d29109eaa2799eda3ee9a47d89f8
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 2c55fad4ab5261efe42f6966294f753037e44fe3
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:24bc168bde6bf9bb477500d046ebf5fb8dcfc484df90f51fcfc3215005b78c6b
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 3dbf32dbbbdbf469a4bf48d7cc5f354713ab5c00
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:a689873b5c3aedce488ef5d52aef2692337f91266da679065bb6e871e1f116e7
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 86ad6953c4d9366c1d2d29c20324b7f35609cdf6
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:23efbab671dcb2a3eedae8da47b6f415d732a476c2b76186eae607077235c578
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: eeeabe9ce80b9ecd2fd544b168759ac7dc2d1c8b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:293709ee0719ef7c389b08e5e4300b0e61eaa837af9398bf770d43cdd6e1004b
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6f1b30543b318eb61f76017e45ee7bf933abdb37
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:e93a3d7b5ccb4f6a2f7408cb1d4ef5865184bb0b801f5caa2454a26dc4cf0637
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fd72e143f5ce0b4f5aaaa0e362b68dac2c2fdec3
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:e9a82d8328b3e5787fff2c0ddd215c75e4fd75ad065196bbebb98384c25e6295
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1d4441f78d5f0666c29799cd94c666771f534d0a
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:f2ac26e79ab3a5a82190ef56474af38af3dcfb056500e95622f7c5005d650013
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: cc0eba5c5d1a042e65ac36898086612b8f638da2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:85dd59ff4929b7c4df276e9f6cf49082c99ed9641855e998aa12ea67c784c577
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: cc0eba5c5d1a042e65ac36898086612b8f638da2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:9add13b0e0377bf52abb301d09e602c7624c8d7051150d4070c0f79a05bb5e4a
    name: cluster-curator-controller-mce-29
    source:
      git:
        revision: b2427085b024d957d92681df46f5658486c2c4d2
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:5ed3e4b628baa103f6511bbed6ff964e0806f99e7c8cd0697c718ac66468c771
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: eaa6200700a5eb78e1d4e59a37a103cfc20fc0cc
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:0728f4e98bf6dae5b77e8fadeaee8f6a994dcb0b838346589b2d78a33879bb74
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0986c3b3421b14d65c949de6d68df43093afbd29
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:fa37e6e9daf1a5ec9cd28006ab058bb6c75ab7887870ab1c11de5b9310150e13
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: cdaa79631be3818a7c068e538c235e76c2e9ac78
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:19542174a5484114ef4a8150ed61d7ef85b5847a4cbbf3ac0f921d66a613f3dc
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 1e499709b5bbba8e5ff52e963dde7b1621dd7359
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:b3f032b409969a117587b7547f2d47291e9f8b78bc00457cf6c2d9e516e640fa
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 1e499709b5bbba8e5ff52e963dde7b1621dd7359
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:279bfe27146e2c5e11f727f2c99c9f1f350313e07900ce12cc4fc18c73780ffa
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: ba28571844fe81d67266e2ce5b9d6becb3b511e3
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:58ee2ab122a092365f6905bf2c25fe50d52e8ceec1be5aca6111ae60b6bdccd5
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: dec319950a1f662305191f981ff087097312fe33
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:16bf66f6efcc3649b315f400f0c749c730068ff3aea283df0fb29bab0f91c467
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: be90a90ba5f52e9bbaf661884cb1b0482156ab6a
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:3d1720673a0da3b5a38dff1cf1568a4aba558b016bda77be1c7b9eba682ed7c5
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9f0ce0c1bc7e2da8a41b1f60b0f411ca439b6ae4
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:ae6f222b33cbabe329633a7e532c0425b7d7286ab5ae3394029d7093aec5000d
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0fd954f387b0790772c3b697108da20f36a774c1
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:104fd6bb4b1807d2ebc2e2c55ac9c0b4d43cde8ee7a1f3813871b7766c0053c9
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3b20f5aed5df79881a617e8eee5f91eb3a160f27
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:5307198803c8f1cd512ef35093d42cd8f5a39cdf0bef09bab3497571bdf9ae51
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: dec319950a1f662305191f981ff087097312fe33
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:230066e4ce23dec6ddba1e9453fa708790926462b8964f9f200dbff6058ea217
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 11eaebe70f16c8b00178afc182189b424ab0f180
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:8f9e7cd45051d7ee3f560df6d92e8f39c42a5bb604f2e832b13e0479c2ae459a
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: fd2ad3659ba71cc14d7ac6927809176e5cfbe27d
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:7c862bad3f4d422b75ffa557d56225a715800fcf39487b4b2d14d55c44c0a4f9
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: cc0eba5c5d1a042e65ac36898086612b8f638da2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:993230c95b9dc5003659aecc152d52dbb053f381d3eb43ac72f4bb35b92a7230
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 5b9f8121f6cd5fc82f73bd9cd5904768a9fa0f72
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:bbbc4c582fa9d74657e5c4d51dd914e125894fb3862f82a314ee6f54815e246a
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e18fc62a3a8ff9f29731329b937c1bba52ed4e36
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:0d529c4d65f74dbb18fd2512598e979143ad3193eb0e06dd5afb3d3e06bdc2b9
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 09de2c44e8784725e66efa00cdc94dcb63c42af8
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:f6bca5a6e67c24f8c82ddd3e4be336075d14ba723a163564140eee7cc95d25c4
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: cc0eba5c5d1a042e65ac36898086612b8f638da2
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-06-04T18:45:17Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-06-04T18:53:45Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-06-04T18:53:45Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-06-04T18:53:45Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
