apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hive?rev=185e29cd0ca289bc614a8e98db004a013c827d6e
    build.appstudio.redhat.com/commit_sha: 185e29cd0ca289bc614a8e98db004a013c827d6e
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "51170379266"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-euhpcr
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/hive-mce-26-on-push-mgqpz
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "master" && !files.all.all(x, x.matches('^docs/|\\.md$|^(?:.*/)?(?:\\.gitignore|OWNERS|PROJECT|LICENSE)$'))
    pac.test.appstudio.openshift.io/original-prname: hive-mce-26-on-push
    pac.test.appstudio.openshift.io/pull-request: "2750"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/hive
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 185e29cd0ca289bc614a8e98db004a013c827d6e
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #2750 from openshift/konflux/references/master'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/hive/commit/185e29cd0ca289bc614a8e98db004a013c827d6e
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hive
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-26-release-mce-26-tj62l":{"lastUpdateTime":"2025-09-24T20:28:02.724669983Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1758743266"
    test.appstudio.openshift.io/pr-group: refs/heads/master
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hive
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-26","status":"TestPassed","lastUpdateTime":"2025-09-24T20:28:02.724669983Z","details":"Integration
      test passed","startTime":"2025-09-24T20:27:18.939078792Z","completionTime":"2025-09-24T20:28:02.724669983Z","testPipelineRunName":"enterprise-contract-mce-26-vcd9f"}]'
  creationTimestamp: "2025-09-24T20:27:18Z"
  generateName: release-mce-26-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-26
    appstudio.openshift.io/build-pipelinerun: hive-mce-26-on-push-mgqpz
    appstudio.openshift.io/component: hive-mce-26
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "51170379266"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: hive-mce-26-on-push
    pac.test.appstudio.openshift.io/pull-request: "2750"
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/sha: 185e29cd0ca289bc614a8e98db004a013c827d6e
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/pipelinerunfinishtime: "1758745587"
    test.appstudio.openshift.io/pr-group-sha: 49c8f7d5c7458baeb01c297edec96d2886bf083c68c65a3df9c2d60de88795
    test.appstudio.openshift.io/type: component
  name: release-mce-26-tj62l
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-26
    uid: 43345c03-0b85-4096-aa0c-17856575797d
  resourceVersion: "5213367139"
  uid: a6df14cc-0ba4-4845-a63a-e970e6a1e369
spec:
  application: release-mce-26
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/console-mce-mce-26@sha256:8484c447e64cf9e1ae449e4a7faa5c37d0edb06598a29ace0897b99e1231b4cd
    name: console-mce-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 77adc8a94e73b7397adfd770ae91f7667b2ac45c
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-addon-operator-mce-26@sha256:f0357b2ea8da428c7d568f6aa5690765b4e9e1e32638f65d768ffb4e0a57051a
    name: hypershift-addon-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a0590919682d3e55a29ce5747886b83c509c0f6f
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-26@sha256:16a402734f074e36618b0c00dcdf7c61e64704c5a1c48234cfac3d85cb46f231
    name: image-based-install-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: ef5e535f2ea566ec640ff2415f67e63b4d0681a1
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/addon-manager-mce-26@sha256:999f6f71a0e6b26b583b5b08e1ca59d9f1ea673d8c5d321a22a8a4a0cea10255
    name: addon-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-must-gather-mce-26@sha256:ff2416ff0fef6350b654f38d5833222cbfc95c08bb984a14d0f76586775d9364
    name: backplane-must-gather-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: afdeeeea98604a995b897400d132b7d654212450
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterclaims-controller-mce-26@sha256:4aae59ca1b9016f9609670b6bf4c1f8ef7ea197e14ba188cb10bf4ed5e617a1b
    name: clusterclaims-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0f2608d267a6ea253e443046a93be43cc5fc2938
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-26@sha256:617b99de4c50f9202d655bbd1af3da490e81e8419860b0d7fcd64e8faaa1f217
    name: hypershift-cli-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 6d025d384fa9859f1536b89a6c42a86c6a938a77
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/multicloud-manager-mce-26@sha256:1914f7fba67b475fb484c1049e8adeb51256047318b43c37bd2c6bb153dc58d7
    name: multicloud-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e8b8f67c6faedb8a700f3d7f48d94882ebdad266
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/placement-mce-26@sha256:833246200c6119366e5887cf6a889cfaaa9e25b4bad07c427813e41a616ea914
    name: placement-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/provider-credential-controller-mce-26@sha256:c146ce3bd628f3b18f62f89dec6572dcd0b10534669fa9e6a532b88c0d3f9583
    name: provider-credential-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 07088723d86c6be44e9b7f1689b026c84153969c
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-mce-26@sha256:d6dd1927e6af21e1e38a372564f9888cacf4925164c2d476cf8a14fe8bf584c2
    name: registration-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-26@sha256:559c0c3a0074e7cc01d885e592c75b9dc1bdf4258c783634e5227068201aea5b
    name: cluster-api-provider-agent-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 288c313de4f44e200f47ba99a89818d5cb462e13
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-addon-mce-26@sha256:e77398d017548f8504435929803c711381a76254ddf140f5717fd858076d0c4c
    name: cluster-proxy-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2ff4f0c8c87bc942d07b7b6bb6d30fea28f288a2
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/discovery-operator-mce-26@sha256:85202573fe7889074f72ff02e24858849e220ba9deb25fdb000a0d54fd6a5967
    name: discovery-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0d7cb97d18e1d86282af08b093ac4ffe2a8ae796
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hive-mce-26@sha256:ff680e2456f300a8cc0ea0cf66886650e761f368dec483a26de25a6270d75a6b
    name: hive-mce-26
    source:
      git:
        revision: 185e29cd0ca289bc614a8e98db004a013c827d6e
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-26@sha256:07905f92d6127e72bf1127244bf49a05a0d0ecd946d57f85ae63e49000e23c93
    name: cluster-api-provider-kubevirt-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 015c9830a89aa5308294e354be60cf25ff95ede1
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-release-mce-26@sha256:809d5a27e7dd8d131adde691a8a501ae4443f5f3d9cd5556e14688d390d351d7
    name: hypershift-release-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 6d025d384fa9859f1536b89a6c42a86c6a938a77
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/kube-rbac-proxy-mce-26@sha256:3dba9efd727f86be27afda05a46676cff1104814c1d4631916a25a46277833f0
    name: kube-rbac-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 62f9ccefe5fdf6f396385be838f8d6ee5ec2ceea
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managed-serviceaccount-mce-26@sha256:e0cbbfb7ec50bd514769b704ea8c9fd266a3591419e7249146383a749b3c4b34
    name: managed-serviceaccount-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c7c8e4c541b6128f5e8031989b23e249a3e69b17
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managedcluster-import-controller-addon-mce-26@sha256:11adb425f0076dacfffc3d76ab1da8a4ef1fa34bddeb6c769d2a24fe76bddbdd
    name: managedcluster-import-controller-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 6c99d46e1f4f80c7ac9fb8adae7a089ad84bb0ac
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-operator-mce-26@sha256:9060259acd1a34449b8b605328de57a2b10c6081e1fd0359bad1ca54d0e34845
    name: registration-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/work-mce-26@sha256:bff9e8ae9f584b0a2dbe92614f7d03dae1cc8838a4787488dad58551c18c6cf2
    name: work-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-operator-mce-26@sha256:93e77557e3395126eceac5539d7696740f5bddd3cebb3f21ec42e87f91923fcf
    name: backplane-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5d978d93b8de1429d9c09eea6cfde0e7284a737b
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-curator-controller-mce-26@sha256:e9d92d0bba088aa59df54b8ee192b069bae783e774faff84a3adf0ad09a8fe07
    name: cluster-curator-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dc4eae41f4f1ac38518913711acd6c057c1e4dd5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-image-set-controller-mce-26@sha256:ab25831b94e2bb2820459d2210b1921b10e8a7d01ab7840e716f08f424fc9132
    name: cluster-image-set-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-mce-26@sha256:c01e56b7a6886f2a32a4a618a4421a14fd86aed2b49c57f9064a30ed47d1dc0d
    name: cluster-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 18963aee595b0afd2620d67236bfe6960d804cd1
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterlifecycle-state-metrics-mce-26@sha256:fd0b8fd083626ab95ec8d13496b807d48a844039fa44ae9a7b45245f4cdb9274
    name: clusterlifecycle-state-metrics-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 87b8d77b18c407a5e2e13455c544fe880940f27d
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
status:
  conditions:
  - lastTransitionTime: "2025-09-24T20:27:18Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-24T20:28:03Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-24T20:28:03Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-24T20:28:03Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
