apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/console?rev=4f8e04cb18be82ba2b7352234391371027afc270
    build.appstudio.redhat.com/commit_sha: 4f8e04cb18be82ba2b7352234391371027afc270
    build.appstudio.redhat.com/target_branch: backplane-2.10
    pac.test.appstudio.openshift.io/branch: backplane-2.10
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "57198107755"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-zlnghz
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/console-mce-mce-210-on-push-lfhtj
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.10"
    pac.test.appstudio.openshift.io/original-prname: console-mce-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "5281"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/console
    pac.test.appstudio.openshift.io/repository: console
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: 4f8e04cb18be82ba2b7352234391371027afc270
    pac.test.appstudio.openshift.io/sha-title: '[release-2.15] [ACM-26304] Fix missing
      select options in react-form-wizard (#5281)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/console/commit/4f8e04cb18be82ba2b7352234391371027afc270
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.10
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/console
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: console
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2025-12-04T23:25:00Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-rp5k4":{"lastUpdateTime":"2025-12-04T23:25:30.681568142Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1764889515"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/console
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"TestPassed","lastUpdateTime":"2025-12-04T23:25:30.681568142Z","details":"Integration
      test passed","startTime":"2025-12-04T23:25:00.319880492Z","completionTime":"2025-12-04T23:25:30.681568142Z","testPipelineRunName":"enterprise-contract-mce-210-cl5g8"}]'
  creationTimestamp: "2025-12-04T23:25:00Z"
  generateName: release-mce-210-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: console-mce-mce-210-on-push-lfhtj
    appstudio.openshift.io/component: console-mce-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "57198107755"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: console-mce-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "5281"
    pac.test.appstudio.openshift.io/repository: console
    pac.test.appstudio.openshift.io/sha: 4f8e04cb18be82ba2b7352234391371027afc270
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: console
    test.appstudio.openshift.io/pipelinerunfinishtime: "1764890695"
    test.appstudio.openshift.io/type: component
  name: release-mce-210-rp5k4
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "6147045167"
  uid: 56a3dc30-102d-4a15-a282-ac7f57a35276
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:10585f909b6431accc8c5e7268bc88dfe4b6c607042a61f9a442601870e5c5bf
    name: multicloud-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cd93fad042be078f7d98849a9ab9605268ad88be
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:30fb0061330a9a68102e2fc341b0d5436c26fdd76de3fbb8485fa5f09714bbad
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 1301263e88021f6f26566da31a3297d3bf2d3edb
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:10a0962955f1bc658760464710cfadf464d5ffb2ef86e29091a7ee22fcf5d7dc
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ac20e9ef54eac5824b7a3700d6c5d6d388e42f88
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:6b3757adaa278dab4379f62c567f4b8d87145a010e303d8bd351796e45652a59
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: ce3de7ce786af65440ab615d200487ca0ff1ca4d
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:041dff9a872cb23af60f968b05d09ddaa7237895d3c74995e51e6ffb8fdb82a6
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6dc47ae17a495f939ef868139c16d8891626ec49
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:6faf8790e24eb1ecfa5d19d5d543f9b03fc7b7575f3c0d20a57b0724badad4ac
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 4d5b42ea8e82b62930f2dbd0c0f4d96617fad465
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:4c4486f17c1bd21a3e16487092a86e0ba263394baa12eeec1f66e345ef34edd8
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 29b412be7fc329ef3222a74569d9f62a9d447db1
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:fd520e8770f275b6a25cd243d75a2c588ab6195897623aec54364ef20545d23c
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: ad96bb1380b3d8e8d98644782d1ffd5581811c63
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:8b35f4fe3508212535e6419ff0405ea89db8add00ed7b9e0e4cdbd83d2a67250
    name: console-mce-mce-210
    source:
      git:
        revision: 4f8e04cb18be82ba2b7352234391371027afc270
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:b72b011e5c89677515c11f5fd52f69d9478bb22ef6d243ab981fb1a418e27c31
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: db0c5ecc7e93078c55aa9e63a7a4237afdf8df7a
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:ddad4b9d9c969a5d709220afbc901307b3339fd27503db433097261c8cacd8d4
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 4d5b42ea8e82b62930f2dbd0c0f4d96617fad465
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:6cac409afbde2fc895c7c9f8c86dd7408c15afd8d696ad31720c02c1c7a89b34
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 90db2f3f4407aacda682c410aae9e6906383d4a8
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:0704243a5bbd3e33993d1268596dc946f27fc5b16005a186a5c9d824c52a834a
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: ce3de7ce786af65440ab615d200487ca0ff1ca4d
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:4ad80c8e3c847b66a9ea1b51ee8095f7d618868a5d8765a775d8da84bde240ac
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: badb6ad539ac1f5bbf2cc867d6106af2be2c552b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:25d4f89543e853894fb939738bfe18e22aa2cfc3e00b3448f0a1ea13844b7f80
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 89cc93c6ddebfe570cf1cb67f3af4799c61506e8
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:352e45a0d0708aa0a13747cc18abf4bffb1c5034184a98c2cbb37344ec0e270b
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7d43c96da5006ec0274c0d6bae8d2f4188b6e08c
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:8937f9140d8ced827733882314ad863a9fd617da8dbc78c62bf4be84618c0751
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: ce3de7ce786af65440ab615d200487ca0ff1ca4d
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:3138b3daeae7d701fb70b098245415e4097fc93daf282a1643c6ec0b60e979f1
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dcae5dee41eedc1c048e4c2986d29871cc302a7e
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:8c519497a22f2b3f11347d4b35fa7e791e8b62244eede43be3d4ececd5d0961c
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: ce3de7ce786af65440ab615d200487ca0ff1ca4d
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:2d1ed5d7fd1d8107d0c661734f98a305aa03bfa9564e9af26e29107610b5212a
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 36cb7b89014ac4abc95ee6e35afffe36fa7f8c83
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-aws-mce-210@sha256:fc3c656202e95738b70d17af95c81a89c87e355646f79b811816a95e33ada15a
    name: cluster-api-provider-aws-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: 43f5b1dd098bf0ed0a22172fae41c10912eb53a9
        url: https://github.com/stolostron/cluster-api-provider-aws
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:e178f65ca95b0cdcb5b16f50ecf852f4d9812a83529a928f34feac6f462be41d
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65467dd9b9c74340d6bfbc4a321603b299f77bf0
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:016e7139281f6d18d1094edeceb15efd4b8834a12416e86cbb3d49b64fc0fd40
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 6aee2552b72156dafb8bf558ec6a9e87b0aa3cc2
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:2b725421986812ce501db94fe0ae5df6ae3e2a8bb31be6aebe24e85cd1ac4703
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ed1d5a4a0fbb7bd488f41af792df6c929dd91e40
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:262db9468caefa25b66176fb3492c5b310c249ee1035d866b6a1faca30318ae9
    name: kube-rbac-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 45af4674a5957dfa597d9931d31698d3c367992e
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:4baaee864c81d590e3760eb8c899ae17fc1c48b5a35541eedbf26353f93ea3f0
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 07fbe130235b63e883cb46234b8028575b5e8c74
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:f7fea1c89b44bf01b57173c3de70fbd6f1e91df8d390480240a9b1c83b2783f0
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b2312c44f2b6ef7e3ea02912d5c57aa544c24496
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:6349cb7f82d566e94ddb686e0ca86124166d42421bf891cb0efa0595832ef623
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: a5aab25bedac7d53d90415cf08490acb6d0d7052
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:00c66305f6ba7fb2c68960d872f3a272b9a56fe54c85f54ceda1b6b9bc25084a
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 46a59a6ea47079f9e64b5bda938ac39708ec8733
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:955205ef3981507c5e039c655ab54b0cc6ea27c8a0f47832e9e0e3dbd99f542a
    name: hypershift-cli-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: a5aab25bedac7d53d90415cf08490acb6d0d7052
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:7ff965ef136b4e9aec6cca4415dc204249ee70247672c7bcf1196eee6d14f364
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: ce3de7ce786af65440ab615d200487ca0ff1ca4d
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-12-04T23:25:30Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-12-04T23:25:30Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-12-04T23:25:30Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
