apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hive?rev=f1cc92b576a5db92e8a408677192f5e28366f3c4
    build.appstudio.redhat.com/commit_sha: f1cc92b576a5db92e8a408677192f5e28366f3c4
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "95609438736"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-muauzn
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/hive-mce-26-on-push-zwm9c
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "master" && !files.all.all(x, x.matches('^docs/|\\.md$|^(?:.*/)?(?:\\.gitignore|OWNERS|PROJECT|LICENSE)$'))
    pac.test.appstudio.openshift.io/original-prname: hive-mce-26-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/hive
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/secret-created: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: f1cc92b576a5db92e8a408677192f5e28366f3c4
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #2931 from 2uasimojo/OCPBUGS-78995/azure-mp-image-id'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/hive/commit/f1cc92b576a5db92e8a408677192f5e28366f3c4
    pac.test.appstudio.openshift.io/source-branch: master
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-08-18T06:07:53Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-26-release-mce-26-20260818-054148-000":{"lastUpdateTime":"2026-08-18T06:08:49.618607668Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1787031708000"
    test.appstudio.openshift.io/result-chains-git-commit: f1cc92b576a5db92e8a408677192f5e28366f3c4
    test.appstudio.openshift.io/result-chains-git-url: https://github.com/openshift/hive
    test.appstudio.openshift.io/result-image-digest: sha256:72f35d36537b6de997289c6534baf060dd16e2ed37980e65e0f71e0087efcb67
    test.appstudio.openshift.io/result-image-url: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hive-mce-26:f1cc92b576a5db92e8a408677192f5e28366f3c4
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hive
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-26","status":"BuildPLRInProgress","lastUpdateTime":"2026-08-18T06:08:49.618607668Z","details":"Integration
      test passed with warnings","startTime":"2026-08-18T06:07:54.47759745Z","completionTime":"2026-08-18T06:08:49.618607668Z","testPipelineRunName":"enterprise-contract-mce-26-q9xgk"}]'
  creationTimestamp: "2026-08-18T06:07:54Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-26
    appstudio.openshift.io/build-pipelinerun: hive-mce-26-on-push-zwm9c
    appstudio.openshift.io/component: hive-mce-26
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "95609438736"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: hive-mce-26-on-push
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/sha: f1cc92b576a5db92e8a408677192f5e28366f3c4
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/pipelinerunfinishtime: "1787033265"
    test.appstudio.openshift.io/type: component
  name: release-mce-26-20260818-054148-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-26
    uid: 43345c03-0b85-4096-aa0c-17856575797d
  resourceVersion: "10634149946"
  uid: bada7be0-a725-450f-82ae-2b48da5b0b0f
spec:
  application: release-mce-26
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-26@sha256:cdb148416cb37eee7cf454abb4f4944f27a0c2ca2b299bc24d99d952d7f3e1af
    name: cluster-api-provider-agent-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9b5454e7a1c2139982d61fadc9e38bf4d65530be
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hive-mce-26@sha256:72f35d36537b6de997289c6534baf060dd16e2ed37980e65e0f71e0087efcb67
    name: hive-mce-26
    source:
      git:
        context: ./
        revision: f1cc92b576a5db92e8a408677192f5e28366f3c4
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-addon-mce-26@sha256:b1d80436839a95061760157b501f9fccdb0994cdc2329bcdbc41d1655f8f3289
    name: cluster-proxy-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 71e04e09242c39ccc9e493b2f11e50716aaf7afc
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/provider-credential-controller-mce-26@sha256:4785aecb445c8d8837a2f1a6ff225725df8e01bb9580014fce749aac75b6473e
    name: provider-credential-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3573f408887bf222917f8527fb3beefa7d63300c
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterclaims-controller-mce-26@sha256:c2d90374ef8e1c6a17e69547b8bb428d6c960126fe4d3cb86e192b2c4bd8eaff
    name: clusterclaims-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cf48f84867ed2461f80856fb6d59588fc0d2685c
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/console-mce-mce-26@sha256:b34605528b48fe5b35a5e98d84edbd5bf79356e603ae841c1ca40da2bb6cf123
    name: console-mce-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: f790b1e40f7f910e3011b3b5909e23c1ae2a7c06
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-operator-mce-26@sha256:fc85a5886c43c221f11ddbce9a91753b9c358e224791b797cd10159906123b60
    name: registration-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-mce-26@sha256:d4de4bdd94f4ce5589038d547f86d18708c86a1aa8b72331caea46bca841f243
    name: cluster-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: f984904b1d5027fdcac82e36f50d5dadedf57ebf
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-26@sha256:a529e11b844e27a8dc3ac2dda094daac943332e3e4309b56ec5f49b1e3fe656d
    name: hypershift-cli-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 9f79ec9a8b77b41a6485924f42d74ffa9d902507
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/multicloud-manager-mce-26@sha256:bb980381548d7aaeb348ec804d57dcec09bcf6e862654a67521f708953603e00
    name: multicloud-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c786e36c6878c9e6b7ed5bd5e2dbaabf3be1050a
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/addon-manager-mce-26@sha256:bb7a740ad1131c06ac178c16ba7773df68b7ab5679f4aae3b33ce73ba3f292a6
    name: addon-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-mce-26@sha256:88501c56b55e347132f668279df8a7f62be480c3d921667d2e814307646d818e
    name: registration-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-operator-mce-26@sha256:b9d0aee900d71205d2849f0927ca7b1ad7e04a887b4b92dcf7a89d6b367d8c17
    name: backplane-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a65aa4f504d351c0f8639ce910f6ad2f914a9117
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/discovery-operator-mce-26@sha256:c9be8246e9403a0602a3747b45d776921da7d2e98bbea5d919fcbe7687e1af27
    name: discovery-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d7248e5d4b12d47b65656303fc316c3e3c66e90b
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-26@sha256:f4a505fda86bee84a016c25cfeaea0ec957d1ab143438ccc14c7c49ccd5816f4
    name: cluster-api-provider-kubevirt-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1657485e8500c31b4e4d759bceff5b480cf2395b
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-26@sha256:3146014c89942c5d7fe90cf991515074a499c0ae496810fdcef192d46a3e75b9
    name: image-based-install-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: a8be761018365a98bd1c8310f230dd8843060c41
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-release-mce-26@sha256:c9dc5825c556e11d8cb8defe39655f2c3feeeb13a7e1bac0a27347dac03c68d8
    name: hypershift-release-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 9f79ec9a8b77b41a6485924f42d74ffa9d902507
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-must-gather-mce-26@sha256:3107baa22df56b36ba57fa9eb50cfc53a6625523c4de1f37655ae1f54c8526fe
    name: backplane-must-gather-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 566a6925a65f896d25c4163e11972f0e043e5ae2
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-addon-operator-mce-26@sha256:82a1d6e51bc8fbabc502d122cf2f05efdc884d04813f04bf297546135af9bd7e
    name: hypershift-addon-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5d5d6ea87a73d116241b1deb0c3f6d78c6aa550f
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/kube-rbac-proxy-mce-26@sha256:7139dfcdd9cbdfe48c88621a515d44f01a154f64887157379f48d9e7fbee8ab7
    name: kube-rbac-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 880bd3a0f40d0bd97ad6800e75d8a7fe7224347f
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/placement-mce-26@sha256:dd8bebec2d45455b062ff60195c359c73b1460e8420aba7212ce40af1b6ebc44
    name: placement-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-curator-controller-mce-26@sha256:f5bdac28722eb8cebabec0346f19e3bd3ffeba5bcc13b338840e23da37c51194
    name: cluster-curator-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f74211e8cfc963af4fdcb1bb2e20e0c221aaf5f7
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterlifecycle-state-metrics-mce-26@sha256:cb513b9b4eca139be725cbf16d242b7c1a9ab637d1b6ac6cb994486b7a48491a
    name: clusterlifecycle-state-metrics-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b846582ed4781433bf4fc07869e0d53df97625ee
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managedcluster-import-controller-addon-mce-26@sha256:2043678b63fa693e296209852c350890169059ca89a242eaea0f066e46de1bf4
    name: managedcluster-import-controller-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 16a80f62a4fac113d1a68aa18de888c150614d9b
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managed-serviceaccount-mce-26@sha256:44fa1622790a5b6645cd0400fc15758bdb5dc291c08ad60d45b9be34dc92d5bd
    name: managed-serviceaccount-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: beb522146bee0c07d731ad36f2f27e9bdd1051f1
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-image-set-controller-mce-26@sha256:f4c17e89c41fa45d902a71bce533472337b1820385b2cb7e976e47357c02fac3
    name: cluster-image-set-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4d40094da4e6e4a2be33212f814533fe54ed1c64
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/work-mce-26@sha256:e3e656973806ea7d351b25cce524e0c608f8cdfca49e230c453800d4273a539b
    name: work-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2026-08-18T06:08:49Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-08-18T06:08:49Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-08-18T06:08:49Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
