apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hypershift?rev=408c12cae00359fc90020cf66c8bd2f6106697d9
    build.appstudio.redhat.com/commit_sha: 408c12cae00359fc90020cf66c8bd2f6106697d9
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "48720789301"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-angwyc
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/hypershift-operator-main-on-push-5f4d9
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: |
      event == "push"
      && target_branch == "main"
      && files.all.exists(x, !x.matches('^(?:docs|examples|enhancements|contrib)/|\\.md$|^(?:.*/)?(?:\\.gitignore|OWNERS|PROJECT|LICENSE|renovate\\.json)$'))
    pac.test.appstudio.openshift.io/original-prname: hypershift-operator-main-on-push
    pac.test.appstudio.openshift.io/pull-request: "6315"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/hypershift
    pac.test.appstudio.openshift.io/repository: hypershift-manual-merge
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 408c12cae00359fc90020cf66c8bd2f6106697d9
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #6315 from sdminonne/CNTRLPLANE-935'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/hypershift/commit/408c12cae00359fc90020cf66c8bd2f6106697d9
    pac.test.appstudio.openshift.io/source-branch: refs/heads/main
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hypershift
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hypershift
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"hypershift-operator-enterprise-contract-hypershift-operator-bjlhc":{"lastUpdateTime":"2025-08-23T04:48:21.025873767Z"},"hypershift-operator-main-enterprise-contract-hypershift-operator-bjlhc":{"lastUpdateTime":"2025-08-23T04:48:31.624158008Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1755922641"
    test.appstudio.openshift.io/pr-group: refs/heads/main
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hypershift
    test.appstudio.openshift.io/status: '[{"scenario":"hypershift-operator-enterprise-contract","status":"TestPassed","lastUpdateTime":"2025-08-23T04:48:21.025873767Z","details":"Integration
      test passed","startTime":"2025-08-23T04:47:35.133983193Z","completionTime":"2025-08-23T04:48:21.025873767Z","testPipelineRunName":"hypershift-operator-enterprise-contract-s2jz5"},{"scenario":"hypershift-operator-main-enterprise-contract","status":"TestPassed","lastUpdateTime":"2025-08-23T04:48:31.624158008Z","details":"Integration
      test passed","startTime":"2025-08-23T04:47:35.155936723Z","completionTime":"2025-08-23T04:48:31.624158008Z","testPipelineRunName":"hypershift-operator-main-enterprise-contract-drwdp"}]'
  creationTimestamp: "2025-08-23T04:47:35Z"
  generateName: hypershift-operator-
  generation: 1
  labels:
    appstudio.openshift.io/application: hypershift-operator
    appstudio.openshift.io/build-pipelinerun: hypershift-operator-main-on-push-5f4d9
    appstudio.openshift.io/component: hypershift-operator-main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "48720789301"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: hypershift-operator-main-on-push
    pac.test.appstudio.openshift.io/pull-request: "6315"
    pac.test.appstudio.openshift.io/repository: hypershift-manual-merge
    pac.test.appstudio.openshift.io/sha: 408c12cae00359fc90020cf66c8bd2f6106697d9
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hypershift
    test.appstudio.openshift.io/pipelinerunfinishtime: "1755924450"
    test.appstudio.openshift.io/pr-group-sha: f921bd05e68b03740c450e565e0e6173e546193170b2dd404ddb6f153e9b5b
    test.appstudio.openshift.io/type: component
  name: hypershift-operator-bjlhc
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: hypershift-operator
    uid: 707fa676-9cc7-4f0b-a0c0-59a833f0bc74
  resourceVersion: "4857788340"
  uid: 259c3617-2e48-4da3-bd08-e1f5ee62c03d
spec:
  application: hypershift-operator
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/ho-hotfix-ocpbugs-58200@sha256:c2b4351a98034cfeae473bf33fff77c72009ba4ac0a1223bfec5c086152c8b33
    name: ho-hotfix-ocpbugs-58200
    source:
      git:
        dockerfileUrl: /Containerfile.operator
        revision: 9ac9e19a4964ab1e858bd9f2948bd31be4fc3f19
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-operator/hypershift-operator-main@sha256:6d087497f2b0071b715abf14ad850c5b6677427e66e8781c7febb36e4e40e4db
    name: hypershift-operator-main
    source:
      git:
        revision: 408c12cae00359fc90020cf66c8bd2f6106697d9
        url: https://github.com/openshift/hypershift
status:
  conditions:
  - lastTransitionTime: "2025-08-23T04:47:35Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-08-23T04:48:31Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-08-23T04:48:31Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-08-23T04:48:31Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
