apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/provider-credential-controller?rev=a9e7ce4b7cdbd6dcf71871d31349109a7d36cadc
    build.appstudio.redhat.com/commit_sha: a9e7ce4b7cdbd6dcf71871d31349109a7d36cadc
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "40583476642"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-cxhbft
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://console.redhat.com/application-pipeline/ns/crt-redhat-acm-tenant/pipelinerun/provider-credential-controller-mce-29-on-push-j7gl4
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: provider-credential-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/provider-credential-controller
    pac.test.appstudio.openshift.io/repository: provider-credential-controller-mce-25
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: a9e7ce4b7cdbd6dcf71871d31349109a7d36cadc
    pac.test.appstudio.openshift.io/sha-title: ACM-19998 Disable Konflux Go dependency
      update (#248)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/provider-credential-controller/commit/a9e7ce4b7cdbd6dcf71871d31349109a7d36cadc
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/provider-credential-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: provider-credential-controller
    test.appstudio.openshift.io/pipelinerunstarttime: "1744723695"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/provider-credential-controller
  creationTimestamp: "2025-04-15T13:36:10Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: provider-credential-controller-mce-29-on-push-j7gl4
    appstudio.openshift.io/component: provider-credential-controller-mce-29
    pac.test.appstudio.openshift.io/check-run-id: "40583476642"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: provider-credential-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: provider-credential-controller-mce-25
    pac.test.appstudio.openshift.io/sha: a9e7ce4b7cdbd6dcf71871d31349109a7d36cadc
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: provider-credential-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1744724137"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-hgxdq
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "3634505292"
  uid: 849244ef-5b59-449a-a93a-29ea0a319996
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:9cf3eb3d3ef5f0cffbce4e1d201d0a316230f43ecb8ac9c3c51b20fc2e2189a6
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 69cb7942ece43308899eb378168b4463dc5662c2
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:5326610524d94b862f0514b20e0bba3cae0e1e3e4878da9c747bc60d119c0386
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 69ad577802b105ed054a80e327090c166d7a5d0e
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:3f990f195b869206cfd52658bd5ad1dc7960c71129f2c0a861204c85deeea445
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 75c03db0ed3c71b0459dab9b7c78612e5c79cc51
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:e1689387b51f276c0b7ae4e4e5d437e3420c96de3bb7b44d7465409ae150d686
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:2ea68e91d34b001e300b35c8e62dcb048f0a8991e90e3962d60fe01d76528cfd
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:d59ce936cfba4f386d4904442da4b121184ce419d5a63c59d325eef9475a712b
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:01a8d590d731893cdd3bdef83891e65de3c0d6be5c87be1488aade6265d0b51a
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 5a77f879c75e648bca2748ccccbb6a12a580d3c4
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:be20f31ab8888a15a784f7422b5eedd282f4bdbf9140cebb0a1b10d3d1a3ad7d
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9e1fd688615b803394f43d042140d9eef6851e23
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:637b077ceeab5c6693283a7f8a6173286d06a9aaa1c74e0a94695d3ae9263c12
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d8efb9c7d910fec7c42cf2fd0adf7183563a4bcf
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:b50f04f6e24066f63b08c9d8b103baa83698dbb244a8ef77dde51df167ab63d9
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:9067e32b13d77be0e720ba0c7f4256e624ae3d79859921b6552d9950fc5292f2
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b16c24571a6d3ec72faf0b370900e3679edbab48
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:ca06577248b37946214a86b67e1b6ee1e457380705cd30f3f0cee61f970e1aec
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 50d7920e42a9424565b95774d7a2059b41c31b53
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:cd71b3589379185bc26b4633f02b462bd267e38f9a882c8bd344ca927631f46c
    name: provider-credential-controller-mce-29
    source:
      git:
        revision: a9e7ce4b7cdbd6dcf71871d31349109a7d36cadc
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:537d55cbaeb7b1a98a2c1e031b4c66e3035de045511a7e6624b8ce7e81ea0486
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8c6d550b5fc10b3f99b17e7843bb5c541d79136e
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:50b9f10cf12fc3c90214fd3d1deee4cc2f7294f0c7503ef32a045308fe125ad4
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: ec1e2e926a5d617ba4463daa4f71a9670c9969e1
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:6105d21436d67786aa356ecbc3e1aac8458f5132f4e1407851b6db4dba3cac86
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9a346a398438b642ec03efb7af5fe35fb0b435f5
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:5964aa8e9347f034494c52215b25b6c2075dc90d876d1b978373640119a633ce
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d16c93b7777a4d1f3e9d8addfea6caafdf3c8d53
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:20d56b7a1480fff690d8af0888009d1841163ca6f551086f7fb0aa06c5464642
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4a46ee4604795c3edac1bad8ca489fc4e8b17e76
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:77eb66dac8d51c90627e4969ce9730d56aa52e2a13b10d4ab4d781ab10051447
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3fedb83a8f33f85e4c18008b51b9b3ae178ce22e
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:6a1379c9aacc0edafa1820b8f9e4ce779ff82f919a0b602f1154410481d5c1fb
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f3dd3f783f5749e01aaafe1f77f554bdab48bccc
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:f4a00dae51a6fe1c035d91fb16da5f14cd572a3ac797524d793132b4f5f5dd24
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: be1ddfe67a6b75fc8947aae24f9011fa74b14dd5
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:5fde151ce032fa94a22f17bb0572547048cdb2ad1c410ee83d0483e6e61ac1c4
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-04-15T13:36:11Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-04-15T13:36:11Z"
    message: No required IntegrationTestScenarios found, skipped testing
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-04-15T13:36:11Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
