apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/backplane-must-gather?rev=d290d0a1550bf298c80af65078694df6c0f30f94
    build.appstudio.redhat.com/commit_sha: d290d0a1550bf298c80af65078694df6c0f30f94
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54925867275"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-fyegtd
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/backplane-must-gather-mce-29-on-push-hrvzj
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: backplane-must-gather-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/backplane-must-gather
    pac.test.appstudio.openshift.io/repository: backplane-must-gather-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: d290d0a1550bf298c80af65078694df6c0f30f94
    pac.test.appstudio.openshift.io/sha-title: 'chore(KONFLUX-6210): fix and set name
      and cpe label for backplane-must-gather-mce-29'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/backplane-must-gather/commit/d290d0a1550bf298c80af65078694df6c0f30f94
    pac.test.appstudio.openshift.io/source-branch: backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-must-gather
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-8hdqx":{"lastUpdateTime":"2025-11-09T23:51:37.71494289Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762731360"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-must-gather
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2025-11-09T23:51:37.71494289Z","details":"Integration
      test passed","startTime":"2025-11-09T23:50:46.173223319Z","completionTime":"2025-11-09T23:51:37.71494289Z","testPipelineRunName":"enterprise-contract-mce-29-66x6w"}]'
  creationTimestamp: "2025-11-09T23:50:46Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: backplane-must-gather-mce-29-on-push-hrvzj
    appstudio.openshift.io/component: backplane-must-gather-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54925867275"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: backplane-must-gather-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: backplane-must-gather-mce-25
    pac.test.appstudio.openshift.io/sha: d290d0a1550bf298c80af65078694df6c0f30f94
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-must-gather
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762732238"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-8hdqx
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "5771386461"
  uid: 43665c6b-9c89-43d8-a346-e033303ad356
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:1119e85a3f7c77c356279f2142d3fadc0ddd4a8f6c57d1510ed755eca123563e
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:98fe1e9e4167c8cf3054fc77ef2be22d4e5064c547066b5915fa3d6f70532bb9
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: b16150762ce2e89c23244147c065f6f7caca6cfc
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:f010248cc6ec6729f4f9e035998500f293f159fd192b64050727a383a9efdccf
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 61a5fb5d58056eb8cbc3885c4b1417e596b258ce
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:11803b453f6b19a8949d215714599523bbb9bb75519b8a6c4b441f49b9d1485a
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ceb233e25cfb1626bb25887f1bd134ad07485a83
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:bcf57620be0e3342b4b598173fdef535326bc76a83f95c1baa04f430d374a178
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5b74daded4750a2cbf0d4a5a6b5528d419d33d9a
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:f3ec94cfba2f44eb3997844cb3957a4cce40ec0d4b7151d2e19ede6b016d847a
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:20c26b068b3146342455b9fcff612b4afdc27b4ab201ce6008b39aebc5085bf2
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a875352be0a241119334c5339c461d0a0d35a624
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:f1ac23f8cadb79fd5ca266c970207d764c3a0a1d9ed94dca74cba07cbd695fe1
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:cd6dac2fd5240b7a9d042f76887611076802a40c99f1532cf8be36ac6e7d237a
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8d638542a691da818d959babf6cf455b9465d351
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:f3e25f411c1c21f088b91de50b729fc49ab0221e427ba878467e70b26c7cfbdf
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9359b998ac1769eca470bd0466a5b960357fd427
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:897d92848405851d3026c04e151ff74b37a1202c7febabea49dcdb7b1c938df0
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 0861c9f2cf973054f064f23b2a01cf15e8aa3c9b
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:91ac7be7f0559fc2f7e3fb82f318082876e04fe764a38c0c6e2c839639c6c037
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d12d5f1431cc016bb16f09ef9221bb861ca8c119
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:90204c2b71dca0e9d1b311662faa0d305000bdeabc85a78bfcb502efb3374255
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:0748a43e12dffe289b213ab4e2b743c66bba7f2eb8c527646daf56d2a56f538a
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 98f49ccb459ae1d087e3e331072f2880b10035ec
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:5500fd9aed2b05db6a014f4722164d478677c5492fda56b004977b7c93f0a178
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: e1eafe67c67eb9d3f40f12fb335cb67a31f4b274
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:ce0e6ffb5244175118c5b344250a3e4bb70b97968a1f95fcf34e7501c5249f01
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 1bb58e295953bb78b761c14b91ec1fc25323a4af
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:7f228a734afc5017770a98a4a162fb245ac75b5d0aa772dbc47731f60500abe0
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:0a5cda6ce251b3d6a31808aedb2301e38691ff19dd728a9078e2d63dcd84e446
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 0861c9f2cf973054f064f23b2a01cf15e8aa3c9b
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:d4ff0432f318a1dc4a1d9a5386da151d7b427c88b149c8faee29c360c67ceba5
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 641aca53ea876756edb1f535e70d19199d26c958
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:8dd115d283b75bb92e93212f347fe9a4c54ca6db465dde5256147c6f41f21b41
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 820a5e07db5f1eb73ce7a0cc1935a95e4363c442
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:e55746b98118872ddfd12c567062dbc2e2e5cee40595edeef78688314f73e4ec
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c75985f045e37e62bed083c02146be8bdc7522e8
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:dc37d9ae213e9cf1c84527cf90cdefb53edbcb56b184eddd2ea86671f083617c
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 061c480263ab307b8138ac9091f95640125bf6b6
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:20ab6c921066f1590adeaa0e37ebe0d0d2cbfb9acbb5cf4209ef03419dded3de
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:6ed312873ebcdc4739070b4af802c34742543d199393d9df6e13372632305533
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fc931744d5468c03ec68b0578d16167d48d263e3
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:afa702fc8098b71bebc832e5d0d8b80bb0d3d1efd9e446ce9489a72a054783aa
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:1cb1ddf2bac0053d04fd580ae22555ef812782f50a5564e4bec7386ddbb1ec1f
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 93162edc5b6a2279dd9efe7d91b138d5f0aae86e
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:a1c75eb52b60e0bf68acaa1202cb51e34c7ad633c463bf9d53ff82d9532bf298
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 1bb58e295953bb78b761c14b91ec1fc25323a4af
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:127d629c5d57130e8579e17b14e478c5ee3771daba592518938571f577e61032
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: da3bf3598ab2323cfe2102d0dd3fe211ce1d6abf
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:ad071ee5ca1557f8c787837d13ebf3b5c7aa4fb4ebff8026529f962a061b6dfc
    name: backplane-must-gather-mce-29
    source:
      git:
        revision: d290d0a1550bf298c80af65078694df6c0f30f94
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:1475eeda9ae6ba7d1404567a2fd527d6736a8ef8c0832cc83b0f68768093dd31
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: fb24dcc9f868270098e478e8acc342f18b3bf42c
        url: https://github.com/openshift/image-based-install-operator
status:
  conditions:
  - lastTransitionTime: "2025-11-09T23:50:46Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-11-09T23:51:38Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-09T23:51:38Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-09T23:51:38Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
