apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/cluster-api-provider-kubevirt?rev=2ebd1e51bf7ef1d49391940015bdbeb47a8e69d5
    build.appstudio.redhat.com/commit_sha: 2ebd1e51bf7ef1d49391940015bdbeb47a8e69d5
    build.appstudio.redhat.com/target_branch: release-4.20
    pac.test.appstudio.openshift.io/branch: release-4.20
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "62593082018"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-zqfvlz
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-api-provider-kubevirt-mce-210-on-push-w96p8
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-4.20"
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-kubevirt-mce-210-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/cluster-api-provider-kubevirt
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-kubevirt-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 2ebd1e51bf7ef1d49391940015bdbeb47a8e69d5
    pac.test.appstudio.openshift.io/sha-title: |-
      Merge pull request #356 from nunnatsa/r4.20-sync_upstream_r0.10_2026-02-04

      [release-4.20] sync upstream release-0.10 2026-02-04
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/cluster-api-provider-kubevirt/commit/2ebd1e51bf7ef1d49391940015bdbeb47a8e69d5
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-4.20
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/cluster-api-provider-kubevirt
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-kubevirt
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-05T09:38:31Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-20260205-084535-000":{"lastUpdateTime":"2026-02-05T09:39:09.326025077Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1770281135000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/cluster-api-provider-kubevirt
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"TestPassed","lastUpdateTime":"2026-02-05T09:39:09.326025077Z","details":"Integration
      test passed","startTime":"2026-02-05T09:38:31.483626857Z","completionTime":"2026-02-05T09:39:09.326025077Z","testPipelineRunName":"enterprise-contract-mce-210-g4qsm"}]'
  creationTimestamp: "2026-02-05T09:38:31Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: cluster-api-provider-kubevirt-mce-210-on-push-w96p8
    appstudio.openshift.io/component: cluster-api-provider-kubevirt-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "62593082018"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-kubevirt-mce-210-on-push
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-kubevirt-mce-25
    pac.test.appstudio.openshift.io/sha: 2ebd1e51bf7ef1d49391940015bdbeb47a8e69d5
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-kubevirt
    test.appstudio.openshift.io/pipelinerunfinishtime: "1770284300"
    test.appstudio.openshift.io/type: component
  name: release-mce-210-20260205-084535-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "7088104571"
  uid: 808e1dd3-c4c0-47b2-a7d7-2e961199fed6
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-aws-mce-210@sha256:982f7b4a311a67c7fad41e6dac748ad7842fc8e40db362b9548d16fe8ad2887b
    name: cluster-api-provider-aws-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: 674c506e460a457840cd2717e955e0b2852d556f
        url: https://github.com/stolostron/cluster-api-provider-aws
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:5788b02b428e7b32800c78b624bffc376649d8f8d90fb63c57663d42f4228450
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cb12cff01c1f9ea6f744169524634f8f18e77a37
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:ecc07768d01ce8dd10bb5631eca30f13de3677f9c82d98e9443b85af4bd6f395
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: d422e678c60ed6250c870365cd48d50355fa472f
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:33e2a10bccb975d191577e114e2c6de329464881a960cb459b7604769600b5cf
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9c7b5291787f11a2a036ae81b79a3f802395113d
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:59cd2f973942aeea6ad675d57374958d14821f0758c216fa5e77ae44a6c18a85
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 0ef76e384d209f60bda25d044e9584de60049016
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:bc2d7d302dd41111cc948a946e481a2a04f3669bb3b91aa46d9b4cbf06847218
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 970de14d21dffdbd59d22c5a5b6abe6e10f3e1ff
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:fabb0058e7f697392f571da85e83e40f51361db97d74eec5de0b125a8986729b
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: f363d4e473b4fd75da49b23cfa86e10dc33210c5
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:c9a2ae1b861b3c11c6e420c81e1a2f4acb4c9bc6caaf83f70c928fd57de78e23
    name: kube-rbac-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 29f85dac5b8ec617a98bb28f59da2ff4157ae0ac
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:c23b5b74e4e9add32aaf59eb8e88e86767ae74e1f50de62b0564cfdfd364c606
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: bd9c3b3369b6d07d4b9e83496fd2beb1866c6709
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:4c1fd48a72c1474b6dc70383cc7c2ce49d92f723aefb73a030780e82d2021f15
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: d3583bc1470b46e2db7d962d5e0052432fc05961
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:42164c650d666c5b371e5c2cfd8ae4aaa367d957c7f411825c0461df4a198f38
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 233acbf6d394cd6255828cba7ea7bec8869fb62d
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:694e68a8c9a093370968aea857f7a4aed907e412cfcd8a14bff48d603ba6582b
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 0ef76e384d209f60bda25d044e9584de60049016
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:6d53413bcfba73a591e331e9de184be7e12fc5c97e0fe7777a98c55c8002091c
    name: hypershift-cli-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: d422e678c60ed6250c870365cd48d50355fa472f
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:71455745b1805c456df3a2592eb78b3a32f401ac667a74c311a88db57e068ebd
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: d3583bc1470b46e2db7d962d5e0052432fc05961
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:a12fb7f7917e1bbf972c284ec1b01414de1d12468803e01f5d7578d537aeee75
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: d3583bc1470b46e2db7d962d5e0052432fc05961
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:ea575d8cc14d728949ca77d5136daf56bc1c88a3ecd1e712fcfb3931e71078cc
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: f32ebeb5ded74424daef24c161a0c4e0c20e8068
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:33e8ca03b008da004eae43fbbbe8ea2afabe048f1eb70d9d7344ea66789ff219
    name: multicloud-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f2fe6c0964a953d42cef1843b26795d4fbc707a6
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:76e7640ffdadd27be4d48697f88610c53ea7efc372fd7bb56a11b98729cdb092
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e3e6deae5faf5089bee6a99ca137127d6ad23ae1
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:09b89b7303197aee5dafd0f0da6b3d448569fbe2c851fda24c4d512f261a0797
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bb9667e56bbd54a5e981792674df0da515c9449f
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:3700f0ea7fd981185be8522aa5ffb064e74f25cc21f3084b8bc4a31c59d395a9
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f84ae084477fc0a316c8f7b3b79c1ef49474629e
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:b396b97861d3d3f44876e717588f50062de2905ab7eda0d25e24b98402c3540e
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: afd2fd115a46136b9d636ebdea3884528725468f
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:0f886ca43b1f64f686b8610a49e2c5b147607656591ede96b9a1ff998bfeced4
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: ced28c6d527e72f289ba34f5d376557c6c8caa11
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:b8fef661c0acc1de9708d5737159f3cf178c0e96d93035a7f66e90350721c6d4
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d1a2f22161e4122bbe9ef3fb13fe77267c4b9409
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:13cec24d8588c78425ca239aab15bdfd9aa66d8629169908ce74f8a1ce878c4e
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 049c17a7b7f1a52e60e774a9f47a1091f1cb8307
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:92b0d54b579480d128f64425047252ed17142b02d77bf5013c1b2742d4a4b112
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: d3583bc1470b46e2db7d962d5e0052432fc05961
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:8089d0d3962c26d9fc9992248495bbb855db11f24e7fa8e42c0f5c98152d6fb1
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        revision: 2ebd1e51bf7ef1d49391940015bdbeb47a8e69d5
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:ac2a7b71f2e7da03cc31d4f3a5434f29a6997b3a360a263c08d961c9e19b4fb4
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 0fef90ed4b1776a10201edd2a5c4bbae68366439
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:fbf947c6835b66fa4a57290928b8ee2e19098853885e1adecc5ad9d7f12c0646
    name: console-mce-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: cfbb16e5be7e3992635e1146f8d0d3b3ae805da2
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:4cb5992b98277e8f09229b76e89f9d13f812b272f2228be438bdd044f7f4ea09
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cc613bcdb92a39c0d2253db723a71ee4c748287c
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:fc3983405271d2c74e0ead2abe597725a33225acbfed4b261d4ae0c75ea908b8
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: d3583bc1470b46e2db7d962d5e0052432fc05961
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:0214bba63b5283deb1eb8be1bbcd4578f0dfefc1b2f2742958efe792adc130d0
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2769c7762ccdf4c4acf55d5d6208810a5525ba8f
        url: https://github.com/stolostron/cluster-proxy-addon
status:
  conditions:
  - lastTransitionTime: "2026-02-05T09:39:09Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-05T09:39:09Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-05T09:39:10Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
