apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-image-set-controller?rev=f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
    build.appstudio.redhat.com/commit_sha: f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "53920351454"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-qwukqj
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-image-set-controller-mce-29-on-push-8s6dg
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: cluster-image-set-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "310"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-image-set-controller
    pac.test.appstudio.openshift.io/repository: cluster-image-set-controller-pbpe
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: xiangjingli
    pac.test.appstudio.openshift.io/sha: f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
    pac.test.appstudio.openshift.io/sha-title: upgrade go-git lib (#306) (#310)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-image-set-controller/commit/f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-image-set-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-image-set-controller
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-jpzq8":{"lastUpdateTime":"2025-10-28T23:11:20.191773274Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1761692401"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.9
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-image-set-controller
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2025-10-28T23:11:20.191773274Z","details":"Integration
      test passed","startTime":"2025-10-28T23:10:46.211134177Z","completionTime":"2025-10-28T23:11:20.191773274Z","testPipelineRunName":"enterprise-contract-mce-29-zhdzj"}]'
  creationTimestamp: "2025-10-28T23:10:46Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: cluster-image-set-controller-mce-29-on-push-8s6dg
    appstudio.openshift.io/component: cluster-image-set-controller-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "53920351454"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-image-set-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "310"
    pac.test.appstudio.openshift.io/repository: cluster-image-set-controller-pbpe
    pac.test.appstudio.openshift.io/sha: f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-image-set-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1761693040"
    test.appstudio.openshift.io/pr-group-sha: 3f5ad436ec9e59c9f4c91e27298a4c40745f9b3ecde6e100e6d73cf94ffb6f
    test.appstudio.openshift.io/type: component
  name: release-mce-29-jpzq8
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "5620806203"
  uid: 56006b90-e6ca-445a-886f-e3a65f2c87e5
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:dc37d9ae213e9cf1c84527cf90cdefb53edbcb56b184eddd2ea86671f083617c
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 061c480263ab307b8138ac9091f95640125bf6b6
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:358e8a39385d43077c2464d1cf037e3358c8eeb7e84958671acb1e996f070d25
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: cf5bdaa388e08141cbefd9131a1d6da056db55e2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:ef9d311b1f5b5b386a6fc224c0fbdd8794c0ccb4e6bff11939c8332f48da8fe9
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65c5657e14476c75ff6eefe921dbaaea620181c4
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:afa702fc8098b71bebc832e5d0d8b80bb0d3d1efd9e446ce9489a72a054783aa
    name: cluster-image-set-controller-mce-29
    source:
      git:
        revision: f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:6028387bdc2e8cb2cc62a22ff242d4c4315ccae94fd93fa9ffd7585b1bb324f2
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: ec63ac6a6d43aa1b58bc78755c2d325447305932
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:71714b7572bf855ea767da208b77cca1d556d8fb1f262d55c1c28660334bf350
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: f094ce7a03c38460a16d28d7142cd57df2d73d67
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:017152eb0d925805bf2e1ff4e7964935aeb5d25b31db47b26ea1062d7ccc73ca
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: dd7d4337176fd9e9086d9163ef517c1bd78ec300
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:e64008588ca273eb2c7e1ae9dd97bcc8c471049c6f2a481ef1079ec162613de2
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d290d0a1550bf298c80af65078694df6c0f30f94
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:6c07664542e644d026144ecff5bec27aff6cdd23949b1d79bcc356737d83496c
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 1607323b5260ddb5f430a774ff4f3020ae96bb81
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:b1614c7ff4d7b125cac315b459aa819a7f7918f70aeb2f6d6f6c4c17791ca600
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: cf5bdaa388e08141cbefd9131a1d6da056db55e2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:92bb8f1e74ca9d0938d92f84f85ca047e8abc6be6df54eb6d8cd506f9393f6ba
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 2b2831ad2a582ba986b164c5c29bc89c62eb6b68
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:f010248cc6ec6729f4f9e035998500f293f159fd192b64050727a383a9efdccf
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 61a5fb5d58056eb8cbc3885c4b1417e596b258ce
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:eee3c75b6eee3f1c0374cbbeff415ba8e28b9556edbc76d2bb01a10246c3bc6c
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ceb233e25cfb1626bb25887f1bd134ad07485a83
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:e9b9e2dba46fdced4d9276082956b34f1223dfaf7f6da600efeee5a42317754e
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5b74daded4750a2cbf0d4a5a6b5528d419d33d9a
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:b622c7a3e14a3d80b01c66fffaf5fee108767fef90976d7ae981d79bfdd1bdf0
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: cf5bdaa388e08141cbefd9131a1d6da056db55e2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:20c26b068b3146342455b9fcff612b4afdc27b4ab201ce6008b39aebc5085bf2
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a875352be0a241119334c5339c461d0a0d35a624
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:f1ac23f8cadb79fd5ca266c970207d764c3a0a1d9ed94dca74cba07cbd695fe1
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:e97bb0c19ad0075422f4afadf82e3a5d6bfa24bdcf484777486d0d52c9f294b2
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9dc1320909e0147368332a97611ff61d266d9f39
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:f3e25f411c1c21f088b91de50b729fc49ab0221e427ba878467e70b26c7cfbdf
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9359b998ac1769eca470bd0466a5b960357fd427
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:7c9fc8014eacde9e9e598823815acd4ea61d5128a84c79bce914fe77ae276aef
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 5eeccb93708bc2479d46ae02628103c16f2fd96d
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:0bbbe339bfd207c0ea117d100886aa3c737fb5ec685ea7dd4a06d1ae7810e6f3
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: fc3dac72b746bff19706dd4d6cc0854f522de086
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:b583869a3c3383670427be20a3b01fa5eba42c09fae0c8401063b0461831277c
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: cf5bdaa388e08141cbefd9131a1d6da056db55e2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:0748a43e12dffe289b213ab4e2b743c66bba7f2eb8c527646daf56d2a56f538a
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 98f49ccb459ae1d087e3e331072f2880b10035ec
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:99576d542b7a93e0e320f5db5fc61cf1ae5c484dca04a19da27a56c0ad3a7ddd
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 8516a9ba99100ed689ef115b0a81220d31962671
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:784df0936de8cb5aad0dec7c3b2948b3c785da1162ed640358da7781e99f4567
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: f094ce7a03c38460a16d28d7142cd57df2d73d67
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:61856d12d173d98c9cfa6596cc9b19be38e8f789712dd742dfa613a1d585f53b
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: cf5bdaa388e08141cbefd9131a1d6da056db55e2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:951773131a05b2eb4a39ccf568b23cb633c926546e43227d5f715e73441b0b89
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 5eeccb93708bc2479d46ae02628103c16f2fd96d
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:03466cbe5b770e1e7b124109dac09840cdc6ed1bec56de9b42dc7cb8278d7f0d
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 641aca53ea876756edb1f535e70d19199d26c958
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:ca2178056cfc338e309462fdd7aa811a653a9513d24959fe0842f56e83c371b0
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0f9a3352b2d282029855f31cded9299f7515bbcf
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:e9f7e03889d1151381a65cc41a3fc24e97b7e0169c43c91bb8dff54a6fa7e837
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ebc7d18f4ac570019a6375403aff3e6e40342c26
        url: https://github.com/stolostron/multicloud-operators-foundation
status:
  conditions:
  - lastTransitionTime: "2025-10-28T23:10:46Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-10-28T23:11:20Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-10-28T23:11:20Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-10-28T23:11:20Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
