apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-image-set-controller?rev=6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
    build.appstudio.redhat.com/commit_sha: 6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
    build.appstudio.redhat.com/target_branch: backplane-2.6
    pac.test.appstudio.openshift.io/branch: backplane-2.6
    pac.test.appstudio.openshift.io/check-run-id: "49448485378"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-zkgyjz
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-image-set-controller-mce-26-on-push-rt754
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.6"
    pac.test.appstudio.openshift.io/original-prname: cluster-image-set-controller-mce-26-on-push
    pac.test.appstudio.openshift.io/pull-request: "297"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-image-set-controller
    pac.test.appstudio.openshift.io/repository: cluster-image-set-controller-pbpe
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: xiangjingli
    pac.test.appstudio.openshift.io/sha: 6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
    pac.test.appstudio.openshift.io/sha-title: move to konflux common pipeline (#297)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-image-set-controller/commit/6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.6
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-image-set-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-image-set-controller
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-26-release-mce-26-k4j74":{"lastUpdateTime":"2025-09-02T22:24:20.356137865Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1756851209"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.6
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-image-set-controller
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-26","status":"TestPassed","lastUpdateTime":"2025-09-02T22:24:20.356137865Z","details":"Integration
      test passed","startTime":"2025-09-02T22:23:32.109788428Z","completionTime":"2025-09-02T22:24:20.356137865Z","testPipelineRunName":"enterprise-contract-mce-26-sslvw"}]'
  creationTimestamp: "2025-09-02T22:23:31Z"
  generateName: release-mce-26-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-26
    appstudio.openshift.io/build-pipelinerun: cluster-image-set-controller-mce-26-on-push-rt754
    appstudio.openshift.io/component: cluster-image-set-controller-mce-26
    pac.test.appstudio.openshift.io/check-run-id: "49448485378"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-image-set-controller-mce-26-on-push
    pac.test.appstudio.openshift.io/pull-request: "297"
    pac.test.appstudio.openshift.io/repository: cluster-image-set-controller-pbpe
    pac.test.appstudio.openshift.io/sha: 6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-image-set-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1756851806"
    test.appstudio.openshift.io/pr-group-sha: 6bcc694fe541a2971f5773273020072b3ce40fd30e8a5a5d4c01d89a29bbe6
    test.appstudio.openshift.io/type: component
  name: release-mce-26-k4j74
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-26
    uid: 43345c03-0b85-4096-aa0c-17856575797d
  resourceVersion: "4962082256"
  uid: a83febbe-4eab-42d8-9879-1d887039a4f4
spec:
  application: release-mce-26
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/discovery-operator-mce-26@sha256:676440c98d3d5ac28ae50b4d6d0ba80658cddc0083cdc28771d57ac2925dc5ad
    name: discovery-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0d7cb97d18e1d86282af08b093ac4ffe2a8ae796
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/kube-rbac-proxy-mce-26@sha256:dd0851911cc1d6b510dfd81e66263d3fb2e69ca6db1e582a0d74f8ef5ba777c1
    name: kube-rbac-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 62f9ccefe5fdf6f396385be838f8d6ee5ec2ceea
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managedcluster-import-controller-addon-mce-26@sha256:a176c03c75cae7613d90353164f1fc66f5dcce1b55a061abca65ce346e322c39
    name: managedcluster-import-controller-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: f3e0d912eecbd99f4816c36e20abd1a9b7fda3c9
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/addon-manager-mce-26@sha256:7cfa87b4d39b3a2e1857b128d3fdff8539c5d9cc704b0efe9e4308aed846a7c0
    name: addon-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-release-mce-26@sha256:800648e56376adeb9740bb433c8661dcefe315354898a3cdfbb0cbc927b1f608
    name: hypershift-release-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 770ac290747e0309c173feba256c9426d906f4ec
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/multicloud-manager-mce-26@sha256:f5cf1079ccfb38e4c2697b15b1a0f14cfcfda997d03ac59915a40ded51decd62
    name: multicloud-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e8b8f67c6faedb8a700f3d7f48d94882ebdad266
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/placement-mce-26@sha256:b57b6dd84b6f69888e4e2ec1feb634878260d8ce23a9cbacc93f7b32fd56d0a4
    name: placement-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/provider-credential-controller-mce-26@sha256:4728658809be9af01e7ae8256371c749e6253e1e0ce0cc053ca34142af27b729
    name: provider-credential-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1e8ade7ef0328175d7b8637508311f1a328c40d2
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-mce-26@sha256:3897a3edc2623dc085c205706671f0e15c9c581031eec64d0ddff91080d01bbb
    name: registration-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-operator-mce-26@sha256:c1e385af6f4f65250570480406e054341c2e58dbe9f49145b8235ed66e8db07d
    name: registration-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-must-gather-mce-26@sha256:b44f1453c1b948c9e4bc556b38af9ea3b1995e42a1d0c25268ce448dc56458a4
    name: backplane-must-gather-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9d38ea38e8e2c2de96a6cc03b0274a5578bdd003
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterclaims-controller-mce-26@sha256:0780ad017237cde391fde08a25c7cdc200741e7ad0ead2edb64e45db6f3ad074
    name: clusterclaims-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e25b2c04f52e34a73cd9d41ac1cc12d6eee58ba2
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-addon-operator-mce-26@sha256:1a20e80a0a580f07b355a752ba64cbdb2e0bd7a290cb8549fa80fbac7acb5d3b
    name: hypershift-addon-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 99952939eb5ef4f80ace12a58180f6d482036e05
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-26@sha256:ac37582b2d8c8062971541a48c581aa4efe1a0e799e452fe27233afd8e570e2d
    name: hypershift-cli-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 770ac290747e0309c173feba256c9426d906f4ec
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managed-serviceaccount-mce-26@sha256:60d332157ecd2dd4e7cb3cebee808a1c0382a9609b3cce355c647206f53bedf4
    name: managed-serviceaccount-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c7c8e4c541b6128f5e8031989b23e249a3e69b17
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/work-mce-26@sha256:1a28f1b83f9d0c843f709c16c3372c86509c02aedf869a21b3c7267ea833c9d3
    name: work-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-26@sha256:9da85e4198484d4a22b84504b1a3f86f731d45f7b7feba9064c8e6a2f2eb588e
    name: cluster-api-provider-kubevirt-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 015c9830a89aa5308294e354be60cf25ff95ede1
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-curator-controller-mce-26@sha256:d7a47b584b2196ee40de9ca0f895cedd43f3d7252ec908a40fb3603ac0a3f282
    name: cluster-curator-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dc4eae41f4f1ac38518913711acd6c057c1e4dd5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-mce-26@sha256:4963cf899602f1cbb43ccbbba7368b95d409cfefe8f3b013fbe742a5083c8264
    name: cluster-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 60449a85cc2593007c20b74f79f583670342846f
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterlifecycle-state-metrics-mce-26@sha256:1e4a988f2cf9552b2dabc8ded82293763d615eea4cc9e091545acb05d273241a
    name: clusterlifecycle-state-metrics-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 660cd1722f1345300ada86df8b21ecb45b2d9225
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hive-mce-26@sha256:635b5b7fa58a2a1e642f84cca8d812a20aea9a441795eed14893f475ab5b63ab
    name: hive-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 301f422f81d68812a27dd4b1fa9c49a3474dafd1
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-operator-mce-26@sha256:e9791553231b6a5fd60c383ee278e0665a60994591be620fe72c91d948628ffe
    name: backplane-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 027db70916067023b67a304fac9de182cca8cd8b
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-26@sha256:711290a899d3cc73bb171c76d4b87d7edb88aba19b68377778a8018d6d70c5da
    name: cluster-api-provider-agent-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2d1bfd25e7b6f04da2ec4036b90d0df8a51ccd42
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-image-set-controller-mce-26@sha256:afda4cfe374d5e3d8052ec0039ceec7282931ad6d9be0a85ee867cd233881260
    name: cluster-image-set-controller-mce-26
    source:
      git:
        revision: 6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-addon-mce-26@sha256:def34a66ecea41bf57c1b1a4e311ae4839a6a28709365d51a5d2a2734dc5db88
    name: cluster-proxy-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2ff4f0c8c87bc942d07b7b6bb6d30fea28f288a2
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/console-mce-mce-26@sha256:23412d04acb476ffd2dc430cd90028b5b7ea382b1864d76b977c5994cab72f09
    name: console-mce-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 042cb69e17448fb7308bf998b9ae4deae84ab3cf
        url: https://github.com/stolostron/console
status:
  conditions:
  - lastTransitionTime: "2025-09-02T22:23:32Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-02T22:24:20Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-02T22:24:20Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-02T22:24:20Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
