apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/cluster-api-provider-agent?rev=9b5454e7a1c2139982d61fadc9e38bf4d65530be
    build.appstudio.redhat.com/commit_sha: 9b5454e7a1c2139982d61fadc9e38bf4d65530be
    build.appstudio.redhat.com/target_branch: release-ocm-2.11
    pac.test.appstudio.openshift.io/branch: release-ocm-2.11
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "89614817084"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-ennice
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-api-provider-agent-mce-26-on-push-nbs5c
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-ocm-2.11"
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-agent-mce-26-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/cluster-api-provider-agent
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-agent-mce-29
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/secret-created: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: 9b5454e7a1c2139982d61fadc9e38bf4d65530be
    pac.test.appstudio.openshift.io/sha-title: 'ACM-27508: Upgrade Hive to fe9c66be8e113d4268ab744ca708860d0b4cc6e1
      (#796)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/cluster-api-provider-agent/commit/9b5454e7a1c2139982d61fadc9e38bf4d65530be
    pac.test.appstudio.openshift.io/source-branch: release-ocm-2.11
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-agent
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-07-24T23:46:50Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-26-release-mce-26-20260724-233649-000":{"lastUpdateTime":"2026-07-24T23:47:50.362861831Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1784936209000"
    test.appstudio.openshift.io/result-chains-git-commit: 9b5454e7a1c2139982d61fadc9e38bf4d65530be
    test.appstudio.openshift.io/result-chains-git-url: https://github.com/openshift/cluster-api-provider-agent
    test.appstudio.openshift.io/result-image-digest: sha256:afc7a6c9c11c4a99acc6c81187d7b7bb76b4fa489aad908904e415448e1a5efa
    test.appstudio.openshift.io/result-image-url: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-26:9b5454e7a1c2139982d61fadc9e38bf4d65530be
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/cluster-api-provider-agent
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-26","status":"BuildPLRInProgress","lastUpdateTime":"2026-07-24T23:47:50.362861831Z","details":"Integration
      test passed with warnings","startTime":"2026-07-24T23:46:50.50140883Z","completionTime":"2026-07-24T23:47:50.362861831Z","testPipelineRunName":"enterprise-contract-mce-26-z2cv9"}]'
  creationTimestamp: "2026-07-24T23:46:50Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-26
    appstudio.openshift.io/build-pipelinerun: cluster-api-provider-agent-mce-26-on-push-nbs5c
    appstudio.openshift.io/component: cluster-api-provider-agent-mce-26
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "89614817084"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-agent-mce-26-on-push
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-agent-mce-29
    pac.test.appstudio.openshift.io/sha: 9b5454e7a1c2139982d61fadc9e38bf4d65530be
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-agent
    test.appstudio.openshift.io/pipelinerunfinishtime: "1784936804"
    test.appstudio.openshift.io/type: component
  name: release-mce-26-20260724-233649-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-26
    uid: 43345c03-0b85-4096-aa0c-17856575797d
  resourceVersion: "10144466111"
  uid: 2b2e4f52-eaf6-405a-ba6f-7c0a9ef36487
spec:
  application: release-mce-26
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-operator-mce-26@sha256:75dcaed6550441f43c524698321ee74e221ad92a262ab72d7c148f18fe711884
    name: backplane-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9fce9b4445ba9842287f6acd196c66e6e4df9b5e
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-26@sha256:7807d7d99b913277a48f8d623f7de82ddee3729e5d397d5ca6778ae72037c5e7
    name: cluster-api-provider-kubevirt-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1657485e8500c31b4e4d759bceff5b480cf2395b
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managed-serviceaccount-mce-26@sha256:2234c685fff4bc830f607137209fe0053d3a7bbfd488d216f9c22b66727e2e1c
    name: managed-serviceaccount-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: beb522146bee0c07d731ad36f2f27e9bdd1051f1
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-mce-26@sha256:75a1d0c4c9e37216ccc8b6b58926a0e95746cad7753252d1c51ed97cc67e0549
    name: cluster-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: f984904b1d5027fdcac82e36f50d5dadedf57ebf
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managedcluster-import-controller-addon-mce-26@sha256:b434ef53fa773ae2c714eff97ac59f1334a80b6df53f35f141e79a5dc458c4af
    name: managedcluster-import-controller-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 16a80f62a4fac113d1a68aa18de888c150614d9b
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-release-mce-26@sha256:50eb90204c4e43912f83fc2fb9f91846a76e0239602bd43da50bd81a7957d471
    name: hypershift-release-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 9f79ec9a8b77b41a6485924f42d74ffa9d902507
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-addon-operator-mce-26@sha256:390ad2713f7eb5dafa33ac995b47686aa8efc7d2c1e21663e424a8b182be861a
    name: hypershift-addon-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b535b02ac358bd8c47b2632ff65967743d8adc2e
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-operator-mce-26@sha256:bba2a1a145361e336c20adebfc716eb5fa3e1db039ca1fa669d15ad3a30e4bd0
    name: registration-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/provider-credential-controller-mce-26@sha256:bd599777a78e2ab6ed4d449c1eb2fb7a1ab5a338a347b548374cccc45ae804a9
    name: provider-credential-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 705bc41b58e2e75c21f1b99be39192304b2d0c05
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-addon-mce-26@sha256:ca49f9e84e12bc16212c4cbcbf38449d34ef07ce1a809a6677ec0537ef23153d
    name: cluster-proxy-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 71e04e09242c39ccc9e493b2f11e50716aaf7afc
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/discovery-operator-mce-26@sha256:aef0f870b71399b43e5240b5a6d648482cedd493e3ca8d6eb31af4950f46dd85
    name: discovery-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f96ab0b6ca2c0e8b4abb97113985a1603f4a8158
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/console-mce-mce-26@sha256:60e21a793648cb06cbd24276659f4a6f1b54b49ae9fec6b57ed0ae5fa5996784
    name: console-mce-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 1c83e227582f2b14ba81ce1177dbef0bc032d5dd
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/kube-rbac-proxy-mce-26@sha256:8535ff9f163e1853a4046c167cb8dced67d0eea66caee2289b4902a46cd8995b
    name: kube-rbac-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 880bd3a0f40d0bd97ad6800e75d8a7fe7224347f
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-must-gather-mce-26@sha256:967b68e5f9d09ccad2e8b622bb1b095dd27aaa6324bfd0cd834dfb4a7bbcbbbf
    name: backplane-must-gather-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 566a6925a65f896d25c4163e11972f0e043e5ae2
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterclaims-controller-mce-26@sha256:5b569f2a6a10c4bbd3de78b6337d7886a7e57ea8780742764178cf9c59ba1383
    name: clusterclaims-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bce79a23baf1269d050ca29561c50eda535a9f56
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-image-set-controller-mce-26@sha256:db61562401ceec515922ce0f24851e752d727293906828f8da28181e0dfeef45
    name: cluster-image-set-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 35f5ebb5b933ee41bce79b60bec1c22fd0613bf1
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/multicloud-manager-mce-26@sha256:1bd2ae30e8cb0d0747d4f774aa55123d3d4542dac38d3702a4c3ce0021c99e5f
    name: multicloud-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c786e36c6878c9e6b7ed5bd5e2dbaabf3be1050a
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/addon-manager-mce-26@sha256:5ccb10264b206d85e735add8522c0a57e2b08c79257c464f4ee65a339debb00f
    name: addon-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterlifecycle-state-metrics-mce-26@sha256:a7d61edc90fd4608bc8bf623c5319dcc0c70f0accee61da28595ff78d874c729
    name: clusterlifecycle-state-metrics-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b846582ed4781433bf4fc07869e0d53df97625ee
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/placement-mce-26@sha256:846ea6a8378374bff03a59fa1e3cbe798c1433d3ead41bdb4cad1cce85263b31
    name: placement-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-curator-controller-mce-26@sha256:f357c02e000cf78b0ab0283497f2ff9419957f678b3c57685cb91b648bdb58e8
    name: cluster-curator-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ea63a952c1da060550baf16656026804cc1f022a
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hive-mce-26@sha256:48fa6f822201c209f42a89e580712f90b6596ec5d57850fcfa3f803a3203defd
    name: hive-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: aa851cbbab20caab15f9caa6e108ac54692a7e8d
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-26@sha256:d822616f8c0edd9d439a9c6c61026a48c7f564329c2962f1f998fb39abf188b8
    name: hypershift-cli-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 9f79ec9a8b77b41a6485924f42d74ffa9d902507
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-26@sha256:afc7a6c9c11c4a99acc6c81187d7b7bb76b4fa489aad908904e415448e1a5efa
    name: cluster-api-provider-agent-mce-26
    source:
      git:
        context: ./
        revision: 9b5454e7a1c2139982d61fadc9e38bf4d65530be
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/work-mce-26@sha256:05b50fe4f8ca0cd2f8d328bbfe4e0de2022cbc0132353f38f4178dc4d58352b8
    name: work-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-26@sha256:d854621640979a7baaf4594e6c823379a7e3de0d81e819410d493037aa3de2d5
    name: image-based-install-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: a8be761018365a98bd1c8310f230dd8843060c41
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-mce-26@sha256:7b7bd16498b100c47009570f8dec01d57176917f578009c0432194c7b153797f
    name: registration-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6c13e21c944ac7238d60aee39e35522269fddbcc
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2026-07-24T23:47:50Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-07-24T23:47:50Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-07-24T23:47:51Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
