apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted?rev=17095fc0e43421661611acb88f6d4eba9aaa5a74
    build.appstudio.redhat.com/commit_sha: 17095fc0e43421661611acb88f6d4eba9aaa5a74
    build.appstudio.redhat.com/target_branch: backplane-2.11
    pac.test.appstudio.openshift.io/branch: backplane-2.11
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54865048237"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-ccqfoc
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "37784342"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-api-provider-openshift-assisted-control-plane-mce-bhhkj
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.11"
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-openshift-assisted-control-plane-mce-211-on-push
    pac.test.appstudio.openshift.io/pull-request: "450"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: rccrdpccl
    pac.test.appstudio.openshift.io/sha: 17095fc0e43421661611acb88f6d4eba9aaa5a74
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #450 from openshift-assisted/konflux/references/master'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted/commit/17095fc0e43421661611acb88f6d4eba9aaa5a74
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.11
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift-assisted
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-openshift-assisted
    test.appstudio.openshift.io/create-snapshot-status: Component(s) 'cluster-curator-controller-mce-211,
      image-based-install-operator-mce-211, kube-rbac-proxy-mce-211, clusterclaims-controller-mce-211,
      cluster-api-provider-aws-mce-211, cluster-image-set-controller-mce-211, cluster-api-webhook-config-mce-211,
      provider-credential-controller-mce-211' is(are) not included in snapshot due
      to missing valid containerImage or git source
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-211-release-mce-211-kxvhm":{"lastUpdateTime":"2025-11-08T09:10:15.740039963Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762592311"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.11
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-211","status":"TestPassed","lastUpdateTime":"2025-11-08T09:10:15.740039963Z","details":"Integration
      test passed","startTime":"2025-11-08T09:09:32.486320373Z","completionTime":"2025-11-08T09:10:15.740039963Z","testPipelineRunName":"enterprise-contract-mce-211-w8p85"}]'
  creationTimestamp: "2025-11-08T09:09:32Z"
  generateName: release-mce-211-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-211
    appstudio.openshift.io/build-pipelinerun: cluster-api-provider-openshift-assisted-control-plane-mce-bhhkj
    appstudio.openshift.io/component: cluster-api-provider-openshift-assisted-control-plane-mce-211
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54865048237"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: api-provider-openshift-assisted-control-plane-mce-211-on-push
    pac.test.appstudio.openshift.io/pull-request: "450"
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    pac.test.appstudio.openshift.io/sha: 17095fc0e43421661611acb88f6d4eba9aaa5a74
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift-assisted
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-openshift-assisted
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762592925"
    test.appstudio.openshift.io/pr-group-sha: d3d233f3fe798771cc747d8e4d1cb64136c24010434c2327047ff408066d5b
    test.appstudio.openshift.io/type: component
  name: release-mce-211-kxvhm
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-211
    uid: 921a3f28-4836-45b7-a77b-5415074a8225
  resourceVersion: "5758262020"
  uid: 332e14e1-5fe0-4374-ab87-11a862908355
spec:
  application: release-mce-211
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-211@sha256:c2b059188f9a441aa35b4546ef1d67407389f3b0c021b99da6151bbcfd5f0605
    name: discovery-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 44a7ba709c9e93451e70399c8f3931d9f9f58ae7
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-211@sha256:adc69660e1d781fcff10890b7520d41256a28c3adb260f831a2e0f70fa853a26
    name: registration-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 2dca53d740a97dfeb5aa810f82367969a8c2e2b2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-211@sha256:5b8c7f4b62992f2eef525ed10722354177c8e382b4bae141394d80145113c733
    name: cluster-proxy-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: ac4e6519cebe1140839f89d9fdad5736e6c75e4d
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-211@sha256:252c62c5e0ce33fcd07797af8d7873c59db71f21ea94c18c78ed03c46799cd14
    name: clusterlifecycle-state-metrics-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: c5e40d45fd7937e33994bbdf5e65cc2e99558059
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-211@sha256:85818431bc1a949330b96a082b09d16f0da642ea2ab6f97863eb0638d1671fc2
    name: addon-manager-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 8d22ff48cf46e95bd9d58bbc81b070e57dcda5e6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-211@sha256:740fc4402878f18fb01a223d608f0f4f1d5d1e1099250b6aec8227d08172e4ad
    name: hive-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d12d5f1431cc016bb16f09ef9221bb861ca8c119
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-211@sha256:4f538dc36b7fc2f0fa0261c9947cc7c1fb9ac8aa31b145e8e1079f1d5b86ff7a
    name: hypershift-release-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 7e919e276ff99be4dec5050778e77c099dffc239
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-211@sha256:0ffa7204dc64dc438e91d8805c867c66ae33e50b974f94f922fe28b330f8a649
    name: cluster-api-provider-agent-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 71ee46c677cb0518fc117a768b701a5d5ad72685
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-211@sha256:00f87ae5df11b768d7b954e063d2e782becbc6dd8ec0125c7f3240a82b0d17a5
    name: cluster-proxy-addon-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c5bb0a211e672b20d4d0815b7c7e75750d6865fb
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-211@sha256:c30903e9a8f5e4207a3f3abee35a5b017e42200ae781822551595f1ef0f6cf97
    name: cluster-api-provider-openshift-assisted-control-plane-mce-211
    source:
      git:
        revision: 17095fc0e43421661611acb88f6d4eba9aaa5a74
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-211@sha256:cf2acad7bae48edeb4bcddf34faad839c9e937548647053ca80a5005404be06b
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 17095fc0e43421661611acb88f6d4eba9aaa5a74
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-211@sha256:56a09a07d5b145e42907510070ca42bbda45d2552fd5412fff9ff380983bf798
    name: hypershift-cli-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 7e919e276ff99be4dec5050778e77c099dffc239
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-211@sha256:e2e7c17c6e179771d70e16d4d8f62ef3ed7752adab4616391e2b1afa52920a64
    name: hypershift-addon-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 28660b759bbca70b193efd6c418ccf43ec8f0d99
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-211@sha256:f686b66f898128f4b60fdba76b39332d31fa6d9632948cc0502ab7905e3198e5
    name: managedcluster-import-controller-addon-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: a009d9df9e8d28add65a9654bb1a1881cb8664cc
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-211@sha256:dc637be05fae061aa20e9007347fe1dade182d6342c8832a6f9eeb0ec93123db
    name: placement-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 2dca53d740a97dfeb5aa810f82367969a8c2e2b2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-211@sha256:628aa3a557a5ba14468ca4806a65fa4630e0e4a332d98a54ee3e076b13aa5ae9
    name: managed-serviceaccount-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1795b5ff29e011619d721a52a16647f4ac3af6de
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-211@sha256:f96f5ec754abf888d28c8ee2eda091a8de208b7a13185ed292ea1b9138904626
    name: registration-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 2dca53d740a97dfeb5aa810f82367969a8c2e2b2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-211@sha256:e94518abc04ad333bb12f2a2760faea71c86e9e0c23de3e86ead4a9580185562
    name: backplane-must-gather-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 203bec98599e722d93d3de4efe8bcf7e3fc074a7
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-211@sha256:a1eaf4d3ca7effb8f149fcc45e7572ba2ce015466e16a7f7e1aa139403231b91
    name: backplane-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a59a70742a5b8231f17492bd74785517b72d3d7a
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-211@sha256:4d690bc1bbe16108dec778b78aead4aff01e381adcea97c8120454aec7bf08f8
    name: console-mce-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 71bb5d09f9816a24941ce599370e0b6762c10bc3
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-211@sha256:e35f6c9e0902083e4889ba4ca7dfff735843cd082021f4cf9001670f593b9777
    name: multicloud-manager-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d34f63c995703f466a6856e8ba11070caf8c5564
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-211@sha256:1ad3263eb685f1c02cedf0e32539f3fc85db3438e606d823f304ba4b0c47bb4f
    name: work-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 2dca53d740a97dfeb5aa810f82367969a8c2e2b2
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-211@sha256:abdfd29a5a722d388c047f805c10233e1e4885beb8697c4d1a8770d2f12b0038
    name: cluster-api-provider-kubevirt-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6bc63fc9424fa6509063519042882828a9e141dc
        url: https://github.com/openshift/cluster-api-provider-kubevirt
status:
  conditions:
  - lastTransitionTime: "2025-11-08T09:09:32Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-11-08T09:10:17Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-08T09:10:17Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-08T09:10:17Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
