apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hypershift?rev=c7d9d5f2d0d6f856d5e7cec8f94fc4557bd39c50
    build.appstudio.redhat.com/commit_sha: c7d9d5f2d0d6f856d5e7cec8f94fc4557bd39c50
    build.appstudio.redhat.com/target_branch: release-4.20
    pac.test.appstudio.openshift.io/branch: release-4.20
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49226298405"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-cjnvnj
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/hypershift-cli-mce-210-on-push-vnww9
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-4.20"
    pac.test.appstudio.openshift.io/original-prname: hypershift-cli-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "6709"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/hypershift
    pac.test.appstudio.openshift.io/repository: hypershift-manual-merge
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-robot
    pac.test.appstudio.openshift.io/sha: c7d9d5f2d0d6f856d5e7cec8f94fc4557bd39c50
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #6709 from muraee/sharedingress-infra-node'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/hypershift/commit/c7d9d5f2d0d6f856d5e7cec8f94fc4557bd39c50
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-4.20
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hypershift
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hypershift
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-cpnj7":{"lastUpdateTime":"2025-08-30T02:00:34.556781821Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1756516948"
    test.appstudio.openshift.io/pr-group: refs/heads/release-4.20
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hypershift
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"TestPassed","lastUpdateTime":"2025-08-30T02:00:34.556781821Z","details":"Integration
      test passed","startTime":"2025-08-30T01:59:41.825137313Z","completionTime":"2025-08-30T02:00:34.556781821Z","testPipelineRunName":"enterprise-contract-mce-210-rbl5s"}]'
  creationTimestamp: "2025-08-30T01:59:41Z"
  generateName: release-mce-210-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: hypershift-cli-mce-210-on-push-vnww9
    appstudio.openshift.io/component: hypershift-cli-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49226298405"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: hypershift-cli-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "6709"
    pac.test.appstudio.openshift.io/repository: hypershift-manual-merge
    pac.test.appstudio.openshift.io/sha: c7d9d5f2d0d6f856d5e7cec8f94fc4557bd39c50
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hypershift
    test.appstudio.openshift.io/pipelinerunfinishtime: "1756519176"
    test.appstudio.openshift.io/pr-group-sha: b56d2184c0a5f82a7f19076698ed0b0e898ab8a650d23db9d2f8f2ce358d34
    test.appstudio.openshift.io/type: component
  name: release-mce-210-cpnj7
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "4927206772"
  uid: 2444af0b-feb2-49af-bc2b-d3cda028269f
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:d0bc38b482fac55cfb9a294af8710f84bd7225447dfc4760c585c2f4b7783242
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dde69fe2003915cfc534d3a0b282e518841262ac
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:ade3eb4be44221af932011c0bd2cffd175a2b35dbcecd5dea91b4dc97413003b
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: e4a1cb2a8958409902c250a228435ae0b1153dac
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:1d270dbed73559bcb3652d79582891957aae9c059cea059b9c4aa6001b1e43d5
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 0dec87579f836b1598bfcc5f5b230b83a6e0acf9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:9780e9f771cce53c449f414029fc33111876b00cc124512f91b0b4189c31737d
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 7483a4a51b70c13fc6e479aa2bead1e75021d4a0
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:5c3f6cb5c7738ed6183083726f5248dd585c06c2800fc8e1ce31e91b39f9d378
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: d7db78cce5ac886dc5366fdc2abb74e0eb49fc87
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:b52a432ce9be60c5ae449b7f0c099b44198398dcb3d8f8f6fcaac7a0565f72c8
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: a9a0fee34723a136e359ba77c7eeee1f42042076
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:70a66b2a7f4c6bb8f7db979a71d85f8adee612f0598e224e2c46d79a86caf2ce
    name: hypershift-cli-mce-210
    source:
      git:
        revision: c7d9d5f2d0d6f856d5e7cec8f94fc4557bd39c50
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:e59163f36b6d8a7ff394caa6ff3e08de3b25bd3edc258aec39838930d2169fa0
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d0fd925bfe36507187da55b08fccc26c662963a1
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:03ce57edc846902c8eabe02723cfa3b0d28b886d50346636c14914181fac2cc8
    name: multicloud-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 458e6688b1a20bc5c3d32d6df0ffe125c51de85d
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:98059ad73d1e9b069c4f94560d88ea6203de24fc3379d81cd46ec7f930221078
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ffaaa2936ae6dd60ea1d9337e580695cc4619e61
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:7901c3b5f5cc173339e8f952088b6eb40aad14e73c1bee7981a6140f15b8c70c
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: b8527096b1dfe818d176ba549fe60ba5e5698123
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:8d2ca62f2b0b3582d31cf89bffd0980ad8ace35bcc092c827cc0e67642f9287e
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a6212f44f64d8dc1f454d1946f336bdca29c18ed
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:c358741ac8eb6b7a3ad57f9efee49f784fcfeffb4ff7c87bd88ab4dd6fc22b65
    name: kube-rbac-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 29232f81fe535e11646513eeb2ff01fe601f6eb3
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:2e43c752cfdb1c1b410bd1d9b539c49e29ba01f4964eb56dbef02f7c58ea9cdd
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 7483a4a51b70c13fc6e479aa2bead1e75021d4a0
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:2e3d8fe5af990ddacf48de292ad13339132bd31bf57d62814f4376cd8e2d14b3
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 76a65b6f3c5d04b90081f90eb901ad9a9c1d90cd
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:290bb57a536187ef2f2e5796550d6cd88e11b1a05bc40f63e78d5724b0953e60
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: c7d9d5f2d0d6f856d5e7cec8f94fc4557bd39c50
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:e53b4e1646df1053b9175763829f0b0ef24327825524215218b88e13cb6944c3
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d430978bca78b616070ddf148df9f206a8f4e110
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:3a002821f31c88fb94a970fe22d8600e84259e1f0be87bbc00c0f38a97bb3f97
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: cb428201e6b3c3e176e8ecb6f44735c44ea9dead
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:c9c8fe43f0197999d8838286834f9105ea0ad757f6c20c18a1c6844b1eaa0b3f
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 0dec87579f836b1598bfcc5f5b230b83a6e0acf9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:9eb9d3e1089c93eeba56a1960b15541655d0dd2f483e91476682921557d6d965
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 0dec87579f836b1598bfcc5f5b230b83a6e0acf9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:49fd7189adde32268d6a0334cba5596fb23e70fe47ddf78c5ee83c27f21e237e
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 0dec87579f836b1598bfcc5f5b230b83a6e0acf9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:bee5d5f7fae0262ee9d97706d7a21b0cac950027c2047857912d8b5ed4e03266
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 0dec87579f836b1598bfcc5f5b230b83a6e0acf9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:bc21c7151900bf07430a7097697c006e697ee4c400bb0bd857ceb1f41e2d6e55
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 476907bc363882b9a940bcbca0ac8b570934bca4
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:627ed8750248ead340c389513cde2f4be3733b4aa67c9f0684533d9734458024
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b0237a356c830b986b6de9dbae2450ac804bb77b
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:e49e090b483424070cff35ef846f601a973055a6274680a76fcea6e9f03df76a
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0c318ff67dbfc05b89292410c5ff496faedc22b5
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:7cfc61ba153ab7ea7b100c3bd833d66b5ea0c3a20dc238eafc5ff59b3c732485
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e1910872a55100232153de97e560e8c3ef5a97f0
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:75a9254da9595401aab78ad0b11877e5a4318fa4d1f69399169a90d8132f96e0
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 681b7b00da89f5b977a232b05bb4127bb3d2882d
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:4945e884601178633259a057457b7aa79afbee154a1a5991c74e4b48fff6e35d
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f229667dd04ee4b38fc58f1df4a49dabbbeb2e54
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:9e787dc8233dc596993d2f8fc79a65c6dd7be23f81592edcaf9e5b93d2257fb5
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: baee5f665ebdc4a17ab11920d62f3521db1b4ec7
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:5454095445ab2860c604eb0f5ff93ba66d5f1ec1b0d042abb0bafe115baa9d23
    name: console-mce-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: c834994f72f9ff2edafcd41827beaa781ec6884a
        url: https://github.com/stolostron/console
status:
  conditions:
  - lastTransitionTime: "2025-08-30T01:59:41Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-08-30T02:00:34Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-08-30T02:00:34Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-08-30T02:00:34Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
