apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/image-based-install-operator?rev=511a0bd1ae08458840ef4183f8d07498ba9249dc
    build.appstudio.redhat.com/commit_sha: 511a0bd1ae08458840ef4183f8d07498ba9249dc
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "57322947195"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-xaoxpx
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/image-based-install-operator-mce-29-on-push-wzfbz
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: image-based-install-operator-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/image-based-install-operator
    pac.test.appstudio.openshift.io/repository: image-based-install-operator-mce-27
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 511a0bd1ae08458840ef4183f8d07498ba9249dc
    pac.test.appstudio.openshift.io/sha-title: 'NO-ISSUE: Update Konflux references'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/image-based-install-operator/commit/511a0bd1ae08458840ef4183f8d07498ba9249dc
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/image-based-install-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: image-based-install-operator
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2025-12-06T10:54:15Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-kcmsz":{"lastUpdateTime":"2025-12-06T10:54:45.5758555Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1765017096"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/image-based-install-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2025-12-06T10:54:45.5758555Z","details":"Integration
      test passed","startTime":"2025-12-06T10:54:15.841111697Z","completionTime":"2025-12-06T10:54:45.5758555Z","testPipelineRunName":"enterprise-contract-mce-29-6lhcx"}]'
  creationTimestamp: "2025-12-06T10:54:15Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: image-based-install-operator-mce-29-on-push-wzfbz
    appstudio.openshift.io/component: image-based-install-operator-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "57322947195"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: image-based-install-operator-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: image-based-install-operator-mce-27
    pac.test.appstudio.openshift.io/sha: 511a0bd1ae08458840ef4183f8d07498ba9249dc
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: image-based-install-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1765018451"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-kcmsz
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "6170635796"
  uid: 7b53a3d0-f291-4ccc-b2e6-86815ade65d1
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:f08e727b308a2c0f993f812f2ac1f76d80c5cc8e41c655c73945e9b91c520235
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 159dc9a2035c30ebb8d358d5a2aea8d43c8f6686
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:21529b086a6f90ed67c928b1c220f661af562b867fb95ec5f7fbad556b3dc346
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 641aca53ea876756edb1f535e70d19199d26c958
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:9ae12cdc6582b8fccf1017c890990a61fffafa38b745b5584f3780b348e8e4fb
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 16b37c7d9289483390c376c6ae469a4964d9a82f
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:132e32d43003021d3c56ad137c8c024b50cdbf8ef1178131682b62e1c81dc3a1
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c3d45e76ac5ec82986a669d82618d20c8ac83806
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:9e63d20926cef484400e543cf2f1bf91a2c32a8f31f2afd3724ba73e6b0e500f
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ceb233e25cfb1626bb25887f1bd134ad07485a83
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:d272be7f25cf39b3b4f377cb82d0394832f0389361d4e9023950decf6a886373
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 83f5de1b4ce2de190180c84891b9ef1c592be800
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:cdb76d2945500049a82f80a1bdf048f1d228219b41b906d9d091bd008ac78980
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 408b5e013fbf770af39c6b65091d849b491706ed
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:2f67b376951d152957965240291999f7ce816c7a53407dd797caed2ea95d5c2a
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 97e8b7f8f67e4fe4b03ee2d440beff6a6f6ffb7e
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:c8a851e3557bf4dcd48dbabcf12e12ec9631c89d13ef6ce3207330eccd18b166
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8854bc5532968fe8df674285a757f8eeb94fd4c2
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:ade8e4506cb3262f3e55f5e796ef64b9461e6d6403e82c62ec44e0cde0018ff5
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 93162edc5b6a2279dd9efe7d91b138d5f0aae86e
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:99e38fedb7dc4c91be1e428e9be844dd2d436a003efb5689c1e91cd12739fb18
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 8876f8545cdf6816a1c685210a249a337bfd0118
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:12c9b05db1b296f5abd61d2815f68f9f8ab86824231799ae671a486f8ee4c0d1
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:94e0f5bff4b950d2ef54c94d6586f855a03f166459008bf5e1929b973f0a23dc
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a47e81c36d91f55ebe6465a8bb78d714ef3424ee
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:27df31cfcf48268544e06ef8e13887ad0878fa11d8515c6a72493ec8bfb2d873
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 52611e2742bae17f6acf5dc8cf065950872e1f57
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:ce47a9823370d30bacc1819387bb3ff619437c8dd3c6f508bebaebacf199ebdf
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: f6b7d716b2add5d5da046165b5d322db7a477727
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:4ee5e8a522ed8a224c620c5f2793906e7549738f0313e4ef55f36e14c1356e9b
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1f211175b1a2bfbe59ddebb842a19723f08acdb4
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:738600e6734d4e2890f4d548c1cd2cf292e041249695dc14517596494043a18e
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:32b71853a177ac9190ea096953dad6550d9d47ffa2a77e894528a77eceba835e
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 29a69a6b98e99aa38fcc6b0ae3b77f883ab8b545
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:13714b5969fb0e44cd5a9dfcd76157157c3e69c65cf05d01320f8dade99cdeb8
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:03402adf779f6689694a08721d3f21ea3a5071d2569469368d9608fccf5236c4
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8d638542a691da818d959babf6cf455b9465d351
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:e66d8d0d6f03ae70a910719c91c747e0eef4277f99f7277738723f5093e4cb5c
    name: image-based-install-operator-mce-29
    source:
      git:
        revision: 511a0bd1ae08458840ef4183f8d07498ba9249dc
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:164cf2c42ad619aca129cd737edc83ce9bc18d44e281f35e88101f9220dbcbaf
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:a27a535e6316f0769ef587e75d2dafb00f24dc5e588a4a814ce4925df59a9df0
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5d76db4010d1e65dc7d8a1f8b7a8c5ca28821f5e
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:1ee7f72c979e03695c48c7a1c94154c4afb275440b135ac8e0af8c3e62221f85
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: c618aebf0abc49c96901d8061e06f58b707f6d1b
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:e6945a16e50a34b341d84d3a2d6660c41cf01134df37e4a2109ee6d83b742ddb
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 8876f8545cdf6816a1c685210a249a337bfd0118
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:332f8bd25e1c109d912e999fc35e0dc518e2e0db41302ea181fddc49216bbbac
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9fe966d79fa63b0c1cc6511b0ad37252300972f8
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:3196572f3fa6db9cd3a4f5b944f1cdc0b936f1bbac9b884eaacd4fbd120bf629
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 52611e2742bae17f6acf5dc8cf065950872e1f57
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:b0e2af788bfc1a338b327e2a0ef45f15f4ac7ded9af40d17bc29e6b85f346039
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 30a40514daa57535b8dcc73ff4fd6a849af99a10
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:24270f6cb963814c5e8e97b259ab23783502bf32685469d8c4cc2971ac2f532f
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: d3ab4cae51c6b18a3fc00a19aca979f57903e196
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:167ebda38668745dff46777880dbac48d5aa8f35413419de1091300eeea2a279
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f22ab37d14a00bb0cb2ac0bfb303a7166cfce4fb
        url: https://github.com/stolostron/cluster-image-set-controller
status:
  conditions:
  - lastTransitionTime: "2025-12-06T10:54:45Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-12-06T10:54:45Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-12-06T10:54:45Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
