apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/clusterclaims-controller?rev=f621572a90022969cbe9e2052e734e60ae903258
    build.appstudio.redhat.com/commit_sha: f621572a90022969cbe9e2052e734e60ae903258
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "40612161565"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-mzdxbf
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://console.redhat.com/application-pipeline/ns/crt-redhat-acm-tenant/pipelinerun/clusterclaims-controller-mce-29-on-push-5dd7d
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: clusterclaims-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/clusterclaims-controller
    pac.test.appstudio.openshift.io/repository: clusterclaims-controller-crbt
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: f621572a90022969cbe9e2052e734e60ae903258
    pac.test.appstudio.openshift.io/sha-title: Update Konflux references (#256)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/clusterclaims-controller/commit/f621572a90022969cbe9e2052e734e60ae903258
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/clusterclaims-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: clusterclaims-controller
    test.appstudio.openshift.io/pipelinerunstarttime: "1744750464"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/clusterclaims-controller
  creationTimestamp: "2025-04-15T21:01:55Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: clusterclaims-controller-mce-29-on-push-5dd7d
    appstudio.openshift.io/component: clusterclaims-controller-mce-29
    pac.test.appstudio.openshift.io/check-run-id: "40612161565"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: clusterclaims-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: clusterclaims-controller-crbt
    pac.test.appstudio.openshift.io/sha: f621572a90022969cbe9e2052e734e60ae903258
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: clusterclaims-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1744750894"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-66dnp
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "3638258619"
  uid: e8bdb391-62af-4610-857f-e342f758624c
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:70669c97de58ce95beefe0f88a15d2ab7e1ddad37b261745f1ac867e84a6ccdc
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a54ccb8e5f4ca78ab060abab4a1fce75953e1f98
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:116bb0edb62549da68b0dead5f881704e3d04e9ec773e4440ecced8013630ab2
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a3822f4c12d756cb31d5e3dd9116d1d4301f1b25
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:637b077ceeab5c6693283a7f8a6173286d06a9aaa1c74e0a94695d3ae9263c12
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d8efb9c7d910fec7c42cf2fd0adf7183563a4bcf
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:405f0ead18f5deaeb15cd26dc2612ad0f3ccaf6c457a8550f803949afccbcec2
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3ad9b9f8e3306a0c5835beb44ee52950fab2658c
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:63b50e792e55dd986a3f51ba52ad566b2bf6bec1167c1240fcb0bdd2b061970a
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2cacd5f052b1be2343a110f80741064432100f4f
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:6a1379c9aacc0edafa1820b8f9e4ce779ff82f919a0b602f1154410481d5c1fb
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f3dd3f783f5749e01aaafe1f77f554bdab48bccc
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:04f74381332f0158968743980b5b46c9f3578a734cbc708900a251369bff702e
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0b4ff1ef2a5695608c236e657e56fb4eb5aa7bb5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:9067e32b13d77be0e720ba0c7f4256e624ae3d79859921b6552d9950fc5292f2
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b16c24571a6d3ec72faf0b370900e3679edbab48
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:5326610524d94b862f0514b20e0bba3cae0e1e3e4878da9c747bc60d119c0386
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 69ad577802b105ed054a80e327090c166d7a5d0e
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:50b9f10cf12fc3c90214fd3d1deee4cc2f7294f0c7503ef32a045308fe125ad4
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: ec1e2e926a5d617ba4463daa4f71a9670c9969e1
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:ca06577248b37946214a86b67e1b6ee1e457380705cd30f3f0cee61f970e1aec
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 50d7920e42a9424565b95774d7a2059b41c31b53
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:2ea68e91d34b001e300b35c8e62dcb048f0a8991e90e3962d60fe01d76528cfd
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:ca718ff843b2817cfda55deba55ba9e3db9ae88ab4ef9fc43f2353a89be96afa
    name: clusterclaims-controller-mce-29
    source:
      git:
        revision: f621572a90022969cbe9e2052e734e60ae903258
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:606bdad96b7457a070198f9b399fb2ed2957dcb9d170278848b069d4dc7ebd96
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a15a7ca492d93dd5e1776ebd2ab99c18e8de6f65
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:5964aa8e9347f034494c52215b25b6c2075dc90d876d1b978373640119a633ce
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d16c93b7777a4d1f3e9d8addfea6caafdf3c8d53
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:f4a00dae51a6fe1c035d91fb16da5f14cd572a3ac797524d793132b4f5f5dd24
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: be1ddfe67a6b75fc8947aae24f9011fa74b14dd5
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:d59ce936cfba4f386d4904442da4b121184ce419d5a63c59d325eef9475a712b
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:b50f04f6e24066f63b08c9d8b103baa83698dbb244a8ef77dde51df167ab63d9
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:01a8d590d731893cdd3bdef83891e65de3c0d6be5c87be1488aade6265d0b51a
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 5a77f879c75e648bca2748ccccbb6a12a580d3c4
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:3f990f195b869206cfd52658bd5ad1dc7960c71129f2c0a861204c85deeea445
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 75c03db0ed3c71b0459dab9b7c78612e5c79cc51
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:5fde151ce032fa94a22f17bb0572547048cdb2ad1c410ee83d0483e6e61ac1c4
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:e1689387b51f276c0b7ae4e4e5d437e3420c96de3bb7b44d7465409ae150d686
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 28994b48ef01fcc8cc591015e9495ad5bbf194de
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-04-15T21:01:55Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-04-15T21:01:55Z"
    message: No required IntegrationTestScenarios found, skipped testing
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-04-15T21:01:55Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
