apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hive?rev=03dc322fee4c3a510f7ce8b60d6014c633ee1769
    build.appstudio.redhat.com/commit_sha: 03dc322fee4c3a510f7ce8b60d6014c633ee1769
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "58150435740"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-ixvkxg
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/hive-mce-26-on-push-v72xf
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "master" && !files.all.all(x, x.matches('^docs/|\\.md$|^(?:.*/)?(?:\\.gitignore|OWNERS|PROJECT|LICENSE)$'))
    pac.test.appstudio.openshift.io/original-prname: hive-mce-26-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/hive
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 03dc322fee4c3a510f7ce8b60d6014c633ee1769
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #2814 from openshift/konflux/references/master'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/hive/commit/03dc322fee4c3a510f7ce8b60d6014c633ee1769
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hive
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2025-12-16T02:11:30Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-26-release-mce-26-qr2xw":{"lastUpdateTime":"2025-12-16T02:12:09.564814986Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1765848939"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hive
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-26","status":"TestPassed","lastUpdateTime":"2025-12-16T02:12:09.564814986Z","details":"Integration
      test passed","startTime":"2025-12-16T02:11:30.66807805Z","completionTime":"2025-12-16T02:12:09.564814986Z","testPipelineRunName":"enterprise-contract-mce-26-czk52"}]'
  creationTimestamp: "2025-12-16T02:11:30Z"
  generateName: release-mce-26-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-26
    appstudio.openshift.io/build-pipelinerun: hive-mce-26-on-push-v72xf
    appstudio.openshift.io/component: hive-mce-26
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "58150435740"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: hive-mce-26-on-push
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/sha: 03dc322fee4c3a510f7ce8b60d6014c633ee1769
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/pipelinerunfinishtime: "1765851082"
    test.appstudio.openshift.io/type: component
  name: release-mce-26-qr2xw
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-26
    uid: 43345c03-0b85-4096-aa0c-17856575797d
  resourceVersion: "6312552549"
  uid: 4d02cae7-af17-4701-9c1d-a3b422856508
spec:
  application: release-mce-26
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managedcluster-import-controller-addon-mce-26@sha256:54eaf137780d164b66a1f964b5b44593471a5dcd1a1a941eeb2cc599e34e734a
    name: managedcluster-import-controller-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 51eb1f95ca9473e985f85229ea73b5537d8bf0fa
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/provider-credential-controller-mce-26@sha256:7bdccdd66af7830d29e41aaa49093deec02e84a60bb08df1dfb874a7f6ed80c9
    name: provider-credential-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a902ccb6acc96f9041a639ff43e047da313ceae9
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/work-mce-26@sha256:1a3650e93a489bbea6b03d8c8fc5092c5e78645aa2c7494a8de04b00fe337065
    name: work-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hive-mce-26@sha256:290374722b4ad1906c320d72380a858b1a59eaf03af78145c9cbf710e8c98f02
    name: hive-mce-26
    source:
      git:
        revision: 03dc322fee4c3a510f7ce8b60d6014c633ee1769
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-must-gather-mce-26@sha256:f29c9c57e884eca6cfcedcf6c2ef7794c9af620ee10de0505eb80b96d23887e8
    name: backplane-must-gather-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a8ad71a5754ec0c67b10e760aaf56a2b09fd00d4
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-image-set-controller-mce-26@sha256:77a246c3b16fd2b1250a75df645afab0549abe2a3778dbbf8acff3da9bc00260
    name: cluster-image-set-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-addon-mce-26@sha256:caefedf582cb0eb9c9dd0656f023a1e783364ee44ae8ee16e23b277f386a2625
    name: cluster-proxy-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2ff4f0c8c87bc942d07b7b6bb6d30fea28f288a2
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-26@sha256:3f8be2767f108477e44b58cebadd9b43d57de22ac0a2e90b03ebbc78927e0968
    name: hypershift-cli-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 15dc3b5da0676c6022e2e73ebcd177c254cf9352
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managed-serviceaccount-mce-26@sha256:605dc406ae1e0d401a6d9fdca24322bf1777081e9e380da07a42cb9ddb7fdc7b
    name: managed-serviceaccount-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ce098276c4944b6365f4d33912ee37f41a3b259d
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/multicloud-manager-mce-26@sha256:9350b5aca47b776f581cf34c3e2955d7131ef1d3e5dd6a1f3507dc670bc09a86
    name: multicloud-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 39fea113bf5ececc8497cbe99111afcddfb7a553
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-mce-26@sha256:eefa5e3090b145168af489aca4b8e33ef207af7270d09ddf7d6d216cdc9cc8ee
    name: registration-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-26@sha256:d591dfb88240e5b504079dd4535541b7af3e5b743ed82f78b02374529d8934ae
    name: cluster-api-provider-kubevirt-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1657485e8500c31b4e4d759bceff5b480cf2395b
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/console-mce-mce-26@sha256:987fc608b802e0ce33638f0b5589a62e3eca72a7fda402abb0eb5e970ce97adc
    name: console-mce-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 6cb954ea444d06b54adaf6d1439d8c13b128494a
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/discovery-operator-mce-26@sha256:d433ecf72ffd01c5af6a29fe86ff7444455564111c408542ab903201ed021c01
    name: discovery-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0d7cb97d18e1d86282af08b093ac4ffe2a8ae796
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-addon-operator-mce-26@sha256:0ab5fe2275ebb44f038f54b5f96ceb5eda7f118eada8785608e430a2cfda7fff
    name: hypershift-addon-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 640621b4fecaaa648a50995a7691c8508aa7688a
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-release-mce-26@sha256:8233cf5d42937a8650a827603df4e1564e8708dd7046011f3a1f22f60d6b4264
    name: hypershift-release-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 15dc3b5da0676c6022e2e73ebcd177c254cf9352
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/kube-rbac-proxy-mce-26@sha256:d22ffe47dbb5fc3e1b43efef4dc4d499f580ecc2cc6af8f2c55b54d461d6a770
    name: kube-rbac-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: a067744adde7fbf8d165f57e50f7d3d889d956d4
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterclaims-controller-mce-26@sha256:c44b0cd077187dc6d85703e277e6fdc17f9eb5e16d4eb03cc5eceef1d07f31e7
    name: clusterclaims-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7ed85ec72b6881ddc5811fd22b77ca2afda910cf
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/addon-manager-mce-26@sha256:a7f6c97e6060f4f40746e1db2e78f74f48eaa72d22b516695f45ed5343cc9e7c
    name: addon-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-operator-mce-26@sha256:3ca8a4f80daee67ebc9b3c1cfed96a9793cd5eaa69d475c6f6ff99ac5182c0af
    name: backplane-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bff3368d69a84d8503a38449ce56b51ef149571d
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-26@sha256:c6cf5a003b90bf17ae9b0600041c2d8efea1d9d037c14acac6948aeef545d9eb
    name: cluster-api-provider-agent-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b7ebc3c18295db2457f6ac97244524fe67289327
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-curator-controller-mce-26@sha256:dac1c36948eae2e8c2202977c9d3bd01f88d4c44581e3f64fd8a51f35ba34b86
    name: cluster-curator-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d87be84e54db85fdd586d417fdb8e2412c51062a
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-mce-26@sha256:d6e4e005ac648f23cd82fa856827a2a346b0e403f8abeefaf18afd24b8810a07
    name: cluster-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 16d33710abc1e1ec32db9bc6c36d74a414fb14dd
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/placement-mce-26@sha256:0c776a8d2baad7e80c5d893225402516d6160bdbfd98892f88d0e0e09f30f4ee
    name: placement-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-operator-mce-26@sha256:bd1f7e6b0eec02e29d07ba9bd09386db2ed336c720fe675cfd25b5bc24f5e126
    name: registration-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterlifecycle-state-metrics-mce-26@sha256:fc46797554859df2ea5d09850e230c81e933b2f3a7f2f2098ec4af0cafb61f30
    name: clusterlifecycle-state-metrics-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 87b8d77b18c407a5e2e13455c544fe880940f27d
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-26@sha256:d8b346e04bf21a29894a9ed5f1dd7c4e52d2e515db99cdf3100d515197b730e3
    name: image-based-install-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 31b20f881d10ccc4eae3e9c12e7bb39a267a8f7a
        url: https://github.com/openshift/image-based-install-operator
status:
  conditions:
  - lastTransitionTime: "2025-12-16T02:12:09Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-12-16T02:12:09Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-12-16T02:12:09Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
