apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/image-based-install-operator?rev=f65e593b80798f13bd748fe595e19b7b52f63775
    build.appstudio.redhat.com/commit_sha: f65e593b80798f13bd748fe595e19b7b52f63775
    build.appstudio.redhat.com/target_branch: backplane-2.11
    pac.test.appstudio.openshift.io/branch: backplane-2.11
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "60844367298"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-wqiewg
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/image-based-install-operator-mce-211-on-push-p88xl
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.11"
    pac.test.appstudio.openshift.io/original-prname: image-based-install-operator-mce-211-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/image-based-install-operator
    pac.test.appstudio.openshift.io/repository: image-based-install-operator-mce-27
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: f65e593b80798f13bd748fe595e19b7b52f63775
    pac.test.appstudio.openshift.io/sha-title: |-
      Label referenced objects for backup even if the cluster is installed

      Previously if/when IBIO was upgraded to include changes to add backup
      labels the labels would not be added for resources referenced by already
      installed clusters. To allow for this, the controller now needs to get
      the ClusterDeployment earlier (to find the referenced resources). To
      allow the conditions to still be set as before in cases where the
      ClusterDeployment is missing or the reference is not set, Reconcile
      specifically does not return when ClusterDeployment can't be found in this
      new, earlier, getCD call error case.

      This also handles labeling created resources immediately by adding the
      backup label to them when they are created in the credentials package.
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/image-based-install-operator/commit/f65e593b80798f13bd748fe595e19b7b52f63775
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.11
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/image-based-install-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: image-based-install-operator
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-01-20T02:48:12Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-211-release-mce-211-jt5q7":{"lastUpdateTime":"2026-01-20T02:48:54.52632403Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1768875535"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/image-based-install-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-211","status":"TestPassed","lastUpdateTime":"2026-01-20T02:48:54.52632403Z","details":"Integration
      test passed","startTime":"2026-01-20T02:48:12.989866313Z","completionTime":"2026-01-20T02:48:54.52632403Z","testPipelineRunName":"enterprise-contract-mce-211-6ncwg"}]'
  creationTimestamp: "2026-01-20T02:48:12Z"
  generateName: release-mce-211-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-211
    appstudio.openshift.io/build-pipelinerun: image-based-install-operator-mce-211-on-push-p88xl
    appstudio.openshift.io/component: image-based-install-operator-mce-211
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "60844367298"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: image-based-install-operator-mce-211-on-push
    pac.test.appstudio.openshift.io/repository: image-based-install-operator-mce-27
    pac.test.appstudio.openshift.io/sha: f65e593b80798f13bd748fe595e19b7b52f63775
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: image-based-install-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1768877284"
    test.appstudio.openshift.io/type: component
  name: release-mce-211-jt5q7
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-211
    uid: 921a3f28-4836-45b7-a77b-5415074a8225
  resourceVersion: "6765651756"
  uid: ee9a2fb2-39af-43ca-b661-6b16fb035ea6
spec:
  application: release-mce-211
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-211@sha256:8db89455769768745e004f72427e167a7699a6fffcd615f69c1a97130d7d2929
    name: cluster-api-provider-kubevirt-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6bc63fc9424fa6509063519042882828a9e141dc
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-211@sha256:59c32e063d41d3a6aaa090d6dab7f68dd4a56b61e94da516f5750a820e723831
    name: cluster-api-provider-openshift-assisted-control-plane-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: f553a90ebfc43deb991421736612fcf7395aac20
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-211@sha256:acd8982a527e322eb1275001db879733ff46efded26786837f68be6147d70432
    name: cluster-image-set-controller-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4dfc824645c145743a7b2e4da0c8c814dd971915
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-211@sha256:722e052e1cd9b811d9d16afdf4ae7c8cd692fd54aab0e347bcd7d239a4164cc9
    name: cluster-proxy-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 941015b2e7569dc2363a484659631a4bb8870aed
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-211@sha256:677e325a5fbc2ce4da8541b267c2fda9b90dabf6e960b110a45eda4036336f52
    name: hypershift-release-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 6fb603c54baa899b853e5761ecad55b5579a7c92
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-211@sha256:5d49c8115fab1ab38523f41d9c80a21591346daf85b30047b3e310f9c38d9539
    name: placement-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: cedb95417c6eca99b5a275b603cc1f45204a14eb
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-211@sha256:8efb7602bb9eeab16d84e5358f5e02c89003a87189a882af3a9cc2a4cf3f96c6
    name: backplane-must-gather-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1905e9fd927d5864414fa8ae39802bc6c830a193
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-211@sha256:9bf07a0c0e072b060a034be0f6fcd2fc1b90fa85bb12a943e53a4f62f3fdfcc2
    name: cluster-api-provider-agent-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 580088b306a501ea265ed1418e61f6294476dd27
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-211@sha256:8981b9dbef646e8333a164af3b07264847c6026d346128d3f191d61f5bbe2087
    name: cluster-curator-controller-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ebbd01acfa8b73111642aa48f6ed6abe35758bd3
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-211@sha256:955044eede63f600aff3e3fb42e6e4a8f3a5fd7917b7dbac149ae32a73af11fb
    name: discovery-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c607aa6a296270169bd9722ef40285c4346fe3e5
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-211@sha256:f7ce2f0fc7e9ec79ccb1054d52c12a136ed45ec682552e1d1a987494c0b05f26
    name: registration-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: cedb95417c6eca99b5a275b603cc1f45204a14eb
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-azure-mce-211@sha256:f2f18907416303af0abeb615270881e162695ecefd5091a2e23aa02fbf8f6f3e
    name: cluster-api-provider-azure-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: b271fff4f127a4ce37ec7f0e84cc778220a9a56b
        url: https://github.com/stolostron/cluster-api-provider-azure
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-211@sha256:18955adbd97a60521965a4b501ed412be821f284412c77e8d1e8a3c1a09fbc52
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: f553a90ebfc43deb991421736612fcf7395aac20
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-211@sha256:806e52b5d13e77518e03f1ec7d08d37dcf1f3b2a8d6aa355fe0840559dafe56a
    name: hive-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 26db04926f9963c6a4b9e94fdef7d648227bbcfc
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-211@sha256:854f60acaab6ae78ef4a02908cec2d63aa715491b9c936663ba5846652b57413
    name: managed-serviceaccount-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bf75da5d439e3fb10255f6dbc0f3c0c596a335a2
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-211@sha256:ca35c65297d2de067939f30b1d4df44698ff480261a3ae2653ff63ba4824ee04
    name: multicloud-manager-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e01e606386e8b317c5e21948e0501d4a3305511e
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-211@sha256:dd05117051f460a746d24ad2f71667a20ba5c3709346c98ad3e5843bfcca8de0
    name: backplane-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 25ecd403409b349d54c9413c70264a3d23e5478e
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-211@sha256:beb93b9817312ecce57b2a084e027e34e4c9f1881c8dd11103cfebe1f66900ee
    name: clusterclaims-controller-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 40522171aa2ab5e7c2772ab88a2cb2619c977a0b
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-211@sha256:e486daa9a2359138692fb1f7554df8fe3e5557bf2e1ee17aad4065c95e203df0
    name: hypershift-addon-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9dc65c7fb940d316ffde978e9d459091a551804b
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-211@sha256:88ec3b50135080024a57a1ce85aaf0ca1eda89a1135db42c7e8cc3eb8e807c20
    name: kube-rbac-proxy-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 9f1d349c35a98646b912d2e50c3d8d00ed53902e
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/azure-service-operator-mce-211@sha256:413f74336fdcbe1853823c51948930e9c6921c7bc82bd1c81c60707a6b15fe1a
    name: azure-service-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: f2b430f1802f38c41f63e841f5ba4dc2765a6301
        url: https://github.com/stolostron/azure-service-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-211@sha256:22eb316bb5f1e0540353ee0bada9bad2b55df69a4b1c6c03ec618208dfb4d7c2
    name: console-mce-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: bf3981699a8438eaf1def95a8ff68c2d25f48588
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-211@sha256:e1c6e9601d06f25592b8accea7d927aeae6225d24103f64c1b7040056cba770d
    name: image-based-install-operator-mce-211
    source:
      git:
        revision: f65e593b80798f13bd748fe595e19b7b52f63775
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-211@sha256:9542cc9b6b84a205f96aae93cfabbd015f29e868103c11581cd5a5bca0479d7d
    name: managedcluster-import-controller-addon-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 8f3c67c3735320a389813f9831d1366614987c22
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-211@sha256:31acc87e684fba46e43ce7c65d85cd18a7be4cba497b97136608a4553fcb51b1
    name: provider-credential-controller-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 28c6d16bd9263cf281c657bcff6e55ba8c4f6387
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-211@sha256:abee610c5aefcc55d3f7c718ce46723f929fd80c7e4fb340e40351130e87dbc9
    name: registration-operator-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: cedb95417c6eca99b5a275b603cc1f45204a14eb
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-211@sha256:bd00f2617ab47cedb1c6774b6029d118110b8e2ad3cce732698b47b1251494e6
    name: addon-manager-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: cedb95417c6eca99b5a275b603cc1f45204a14eb
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-aws-mce-211@sha256:7edca623c5c71d1976093c289af82eaa155ded37c4e5442be19a02a9d23b8fd6
    name: cluster-api-provider-aws-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: 17567091d5b263053b2fbd6674da98b8c08e0aa6
        url: https://github.com/stolostron/cluster-api-provider-aws
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-211@sha256:621ecdef30604652042807cc49902b9e08c7222332e2d991d9c9795385f47ab7
    name: cluster-api-webhook-config-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 98ddd943694a68b1e0c7a6feabcbb1fb63fd9753
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-211@sha256:4f7a6f494f4ce8fa8c740169d7bf1c3e0105a26ddf1f596176ebb298e0ff95dc
    name: work-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: cedb95417c6eca99b5a275b603cc1f45204a14eb
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-211@sha256:b66eace65c5f0789f98cfb78fc38036a3206584af90adc4f7c92f3911adda40e
    name: clusterlifecycle-state-metrics-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 60dea6220fe4d15a366c17958ca684211074862a
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-211@sha256:3e57d9f3326f263dce26b5838d8ea00aa96b8db712fc0dcad3e1dd80a1cc3880
    name: hypershift-cli-mce-211
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 6fb603c54baa899b853e5761ecad55b5579a7c92
        url: https://github.com/openshift/hypershift
status:
  conditions:
  - lastTransitionTime: "2026-01-20T02:48:54Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-01-20T02:48:54Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-01-20T02:48:54Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
