apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/kube-rbac-proxy?rev=45af4674a5957dfa597d9931d31698d3c367992e
    build.appstudio.redhat.com/commit_sha: 45af4674a5957dfa597d9931d31698d3c367992e
    build.appstudio.redhat.com/target_branch: backplane-2.10
    pac.test.appstudio.openshift.io/branch: backplane-2.10
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54925873177"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-clpnqc
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/kube-rbac-proxy-mce-210-on-push-q975s
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.10"
    pac.test.appstudio.openshift.io/original-prname: kube-rbac-proxy-mce-210-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/kube-rbac-proxy
    pac.test.appstudio.openshift.io/repository: kube-rbac-proxy-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: 45af4674a5957dfa597d9931d31698d3c367992e
    pac.test.appstudio.openshift.io/sha-title: Bump golang.org/x/oauth2 from 0.13.0
      to 0.27.0 (#245)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/kube-rbac-proxy/commit/45af4674a5957dfa597d9931d31698d3c367992e
    pac.test.appstudio.openshift.io/source-branch: backplane-2.10
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: kube-rbac-proxy
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-jpddj":{"lastUpdateTime":"2025-11-09T23:53:24.805648157Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1762731375"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/kube-rbac-proxy
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"TestPassed","lastUpdateTime":"2025-11-09T23:53:24.805648157Z","details":"Integration
      test passed","startTime":"2025-11-09T23:52:47.461325887Z","completionTime":"2025-11-09T23:53:24.805648157Z","testPipelineRunName":"enterprise-contract-mce-210-jfxjh"}]'
  creationTimestamp: "2025-11-09T23:52:47Z"
  generateName: release-mce-210-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: kube-rbac-proxy-mce-210-on-push-q975s
    appstudio.openshift.io/component: kube-rbac-proxy-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54925873177"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: kube-rbac-proxy-mce-210-on-push
    pac.test.appstudio.openshift.io/repository: kube-rbac-proxy-mce-25
    pac.test.appstudio.openshift.io/sha: 45af4674a5957dfa597d9931d31698d3c367992e
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: kube-rbac-proxy
    test.appstudio.openshift.io/pipelinerunfinishtime: "1762732361"
    test.appstudio.openshift.io/type: component
  name: release-mce-210-jpddj
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "5771420595"
  uid: 2e8181dc-c578-4ecc-a572-82c50e0ec163
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:e69e1d8dc7b0f8a94302280893e3e029ef52cab98d0f23db4563a7fb481c5b8a
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 90db2f3f4407aacda682c410aae9e6906383d4a8
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:fab39328da82d9aed856455211748064e379c481e62e878815f10bb902b0b14e
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 23e2a1ac1fc8bbefa065eeab055ae42138f0e237
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:9ce7c782670a9e37280bd4da194cfec3ac6629786d3f66875e758d871a689af9
    name: multicloud-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 21b96fdb0ad9f2248da52c1429f3b1ff2888cea3
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:3521206a11c2b0c043265e899ae6f470c7429903bcfb8ef16b6bdcee827afecb
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4bda37dec8f060b2c69051ec98d8f2c01ef75e72
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:b3e97be7a8627b9477880701bcca76d49d8728b3abbd23f2d479f1824b03381d
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3c59204843fa13ad7143075c2d2831e8a73e7a32
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:906420ffd7874c4ea993e09cfd2029a638ae41748c0eee2ae9f9630ade9a402e
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 00a5e4e6307c32c4c64b2cb7e10fa6918fa6bf19
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:6961503866daf80308683a6fc68f0684f90cfe4faad9b0ae80c95418429227e3
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8fb7f7277953e9a5ebd364415a33f6cfe34ca548
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:8080c07d5c8e3b9261c7710cf36121bd1bee8669793e74f2d566c75d4822b9be
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6bd0c8a98a172d6d8ca3c1f48b38fbd94ad7dcfb
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:eb6593851516800bcaaf5da0d011a7b61f11261e5b134ec2e600f87e9ded61a9
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 8f9bf20fc02be4b0fd1dbd6c1d6e540f16ac002c
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:550e488db301bf9c73c3e8d127307f0f915e417f62fb1e0b1a4ee06a5025122a
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: ac4e6519cebe1140839f89d9fdad5736e6c75e4d
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:03aa5a6132d9f732cebc9b3d6865c24a22fcba6a06fc37e32a286120ddf0007b
    name: console-mce-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 345603eb85cdb6b5b0bc9fec8e394c7a294a37e2
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:b642ee8ff76e7e6695a5294524a3ad5a3ca82ffd5b3f67774acbcfb52e9948b0
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b47f470c74c68a1153a0f9ae2c46f661752cb4d2
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:c0a47ebe66845b743d8c30f05e9b180d8f959885d18d0f2c06b77a02e88345b0
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 0acf852b51f2aaa551c833c5e6743996d69fd832
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:52b556657d740d243864114eba485902c9edc32238102c3ff3994244cf7d19ff
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6bd0c8a98a172d6d8ca3c1f48b38fbd94ad7dcfb
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:135222bcff5cbc5897640754e86ada54fa51512c2372b9860e46e4f1acf6413a
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3018b639d11a5753ac5f3f8ee6c19819786176c2
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:a9d567d73ca5a3315b7b3f13fe067de168a895d9dfb95c5837315317e6d68cf1
    name: hypershift-cli-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: a28b548128e1963b2e4166268471957a3457f70b
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:9c76f202c1d1421350c05b7860db54e50925e3c590e91b081e6d37d169d43897
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d12d5f1431cc016bb16f09ef9221bb861ca8c119
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:946ff4f8eb5c5e9260d579ef09e1ca5122b700edca89bf701639375a7df0ba5a
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 273dd89940374999dd7e6a22270f17662ebf6a9a
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:b45eef403c84934699bbb1735b9f88c36fdebaaa49a03a501772e3d24c31a4fd
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 561e7233454a8583a16db184c6a2b3906780e9e4
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:395aaccc2b76449e242dc96b63df8e55389a202e2bd3c0fb23fbb24ccd8f9d1f
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 22a6f8bc2a1418f241455f516eeee4a1e9803345
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:cd3615261421c22a3737694bf1114f03df69d0e062a4f3be9abb761af09a8fb9
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: bd5dc6a0776bc6552352af7085f76858a2133c6b
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:6dbc7d52751b483dc8587f2381ca434617fe96167efecddee2d26ca3a4fd6c9d
    name: kube-rbac-proxy-mce-210
    source:
      git:
        revision: 45af4674a5957dfa597d9931d31698d3c367992e
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:1641c05bacfd677b5062aaecd76220e194524bba7a4bd5ff40b9fd19a04cd70f
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 94b2d14bd59034e07ff4ea2111156b00df3a504b
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:81f3c6bc4cfd047a1a974506afcda6be03b871f3ccfc85c63b77e3c96712c62f
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 21f721a0d8921ec8bab33fd472efe37d368513ee
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:6a2ae26362596f057e5ee52b3c2beb107bda39598aec6966a4701dfc2a9469bf
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 273dd89940374999dd7e6a22270f17662ebf6a9a
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-aws-mce-210@sha256:c0df6dc26da04549daa1a2e1e6f9c7eef56e29f77e911ea13e68e34aa8bca3f7
    name: cluster-api-provider-aws-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: 19e57de3fa10a489da0265e61cbc229ca30166b2
        url: https://github.com/stolostron/cluster-api-provider-aws
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:6eeba0c8c366c1a4e4242108f2ce8929aeac98f9de87cdef229ac21feeebf1a5
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ac20e9ef54eac5824b7a3700d6c5d6d388e42f88
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:03d378de2668a1ad0d1b9a7c6a27d6a4600a5c05d40e87a4d8ca5117a423578b
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 9d675eeb2f81591721bef1a4c100a57d9fe69ad0
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:e934be370a870abdd0d7d8b3cdfdad7902c64bad37de8f1748aa6a6980bb3819
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 73e8a0ef65aa019bad67eae70987f5ca71edda52
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:e96d2cf6727f5a953eb4895fadda07e50a6a734f062f995a0d7e2cf31380828c
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65467dd9b9c74340d6bfbc4a321603b299f77bf0
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:d90257cca04bca589fb927f0db59a56f0c91e43b0b2472d69a500a14ac5447e7
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: bd5dc6a0776bc6552352af7085f76858a2133c6b
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
status:
  conditions:
  - lastTransitionTime: "2025-11-09T23:52:47Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-11-09T23:53:25Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-11-09T23:53:25Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-11-09T23:53:25Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
