apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/ocm?rev=3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
    build.appstudio.redhat.com/commit_sha: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "61680339240"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-tnkvww
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/addon-manager-mce-29-on-push-2l5tq
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: addon-manager-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/ocm
    pac.test.appstudio.openshift.io/repository: addon-manager-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: xuezhaojun
    pac.test.appstudio.openshift.io/sha: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
    pac.test.appstudio.openshift.io/sha-title: |-
      Unify tekton pipeline path to pipelines/common.yaml (#562)

      Previously, different branches used different pipeline YAML files
      (e.g., pipelines/common_mce_2.9.yaml). This change standardizes all
      tekton PipelineRun configurations to use pipelines/common.yaml for
      consistency across branches.

      Signed-off-by: xuezhaojun <zxue@redhat.com>
      Co-authored-by: Claude Opus 4.5 <noreply@anthropic.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/ocm/commit/3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/ocm
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: ocm
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-01-28T01:44:33Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-zfx2t":{"lastUpdateTime":"2026-01-28T01:45:06.580579631Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1769563225"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/ocm
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2026-01-28T01:45:06.580579631Z","details":"Integration
      test passed","startTime":"2026-01-28T01:44:33.602239968Z","completionTime":"2026-01-28T01:45:06.580579631Z","testPipelineRunName":"enterprise-contract-mce-29-cscxk"}]'
  creationTimestamp: "2026-01-28T01:44:33Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: addon-manager-mce-29-on-push-2l5tq
    appstudio.openshift.io/component: addon-manager-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "61680339240"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: addon-manager-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: addon-manager-mce-25
    pac.test.appstudio.openshift.io/sha: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: ocm
    test.appstudio.openshift.io/pipelinerunfinishtime: "1769564668"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-zfx2t
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "6922367965"
  uid: 31cf0942-1447-49e3-a5b1-96f9b0a11087
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:aa47367397f1d476924fb0635d28e99061d1766556881c215ea5021ca19b1588
    name: addon-manager-mce-29
    source:
      git:
        revision: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:0b25e58ef559430e6ea8288b5aae9915f5c20b23fe93d7502fb5e1770a045420
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5d76db4010d1e65dc7d8a1f8b7a8c5ca28821f5e
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:4488901b848662336c0196d7991b22234bdbbad53c3f0d958c2e4c2f82692716
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e5d05c664956d89267a17bd4459ae9651b79a5ce
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:c2d1b1ac1f94b21f609b1130a31b76fc08279250ed7ed46f2657d0579f4d6a0f
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e4252b67edbbd5fe55b859de6af1c0ea4e40c2dd
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:d4b368961c4910056f0aab6cce9dc5d156a61fd75649e0f301c0b430af12bc59
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 551463c28230dd34d69673ab26a424007fd89de5
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:fe9ef9e7202774296d41a3fa24db190d0d54467a37a77f12c62e73da3779c2a4
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6d2c89a1291c4b3845351621ded209ee280b7c9d
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:18a7ab614217d9d861f9d5ba362582ff60abb2d8c7c83df3d6195e15442029a6
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1b97ddb484ac550a65f469c3c64575487a584991
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:fd146b74a90435c8f646f19e87dab2ab1823683532b520e35b086df800f9e2f3
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:d91081ac2e1f691434e9fbc2c6127324adb888e116dbe159b51cb603c2c856b0
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 71b85abfe1756a80d49d1f8758eb643ed41d6ef7
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:284b421a5f21ccdaac266b07496b4ab5e6f7be396a768f194a8a138c053b28b3
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: e10a26e9d62fcb2eb0ebe83c57fdfd1815e7354e
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:c3016b97ddb6297f0c8c49056612c8b2d11f8a54d34ac14479b5e64d1844f00d
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:11f8f0889fb2a4292b866e0c745f80fae259a9c4f24a73afa2b206243b261cd4
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:149bf23dc1293b418b1304ed2d1805a0b04ebd1ae94a17bd173be8d2920f8cdd
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f1c0b2c05be9dc714055f5edd0e95d2d5c21ca47
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:69431760c7c73e5bcb3529df1edf560089c32d24b20df6acc405aaf0540926e7
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 22b14789e713f38556fbb74da2d65efaaf15d07b
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:b674ad89d24aa6be24b3bc8cf1ba3ac6c06652e1008cdbd927fe12ed1687b067
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 1d99e6e1ad7d3ff82a575875381b141d0ae3dc7f
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:7517ec7ca8771e11ef85aba4b0c35c40d84ad1d2d7711b716fe5452fc7edf6eb
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 50e79cd7431dea3455b165136758cab7c793b8d2
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:291b8c1eff59e08f241004ac8e2241c43b4d3fcf43fde13df75dc56a39e7f37f
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: e33d70397d57878e44d511ddc9ecee5521267d8a
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:6bce431c082538c1e1c6873ed90ba61ece04c3b546c81472a664ad5b6fffabed
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1a1446370771fbeb8112ad75ab136ce50f5c91c2
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:981e159dce66e25877a7c34d28bce253b4edcb0b9f90646d6b466d1a19e948bf
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 2e17b9413b58b131908ca601f7653b9cfd00b122
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:cc394e71774f05a8a91462cb37f8a40c61aa1f3abd7c2fd39cb3b97bf84fcb10
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 29a69a6b98e99aa38fcc6b0ae3b77f883ab8b545
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:ebe04809ba5e2cb6d427257fa419c2e472ea638dddcee7f07feacead64c5c533
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: eac42c24b18c1c009c9d34977acc07f13d9c9f2c
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:5624377c3363065ca5dcaff2db4ad33358512329d7a815502df0cfe6a73e7f2e
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 960cde230fcfc17da8d679f89ff23b078e9ab92d
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:ac7fa983f91dc7c59ce4021a079d417bae2d9eee45fcd000cd5e513b973761ea
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ee5fcf31caa9ba5a3b48e35b92f35f3917699eed
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:a7a912374abd942b5db99908ec5c0248db347ace1c170d89f6d5eb7948bddc4b
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 95eca4f9bd6d9a6006e643cb661f3320d418b119
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:288fc8910022fcbc6cba65e6f534e9c5c10978081cc815770e38dbf96b987599
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 3883c2eedf4d1fe7c77ffbb2ff3fd9fdaf36503b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:33efb5729e083246e2e67ecf46dd8b260a02963465e3a97f9d869ea04c0ebcd6
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: eac42c24b18c1c009c9d34977acc07f13d9c9f2c
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:6d5be6ea256b0c7762ebdf6aa5d3c813607fcae6eb97d40e42b4e68d2447e557
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 975e1e494b7c4d8bbdda164528af9a200441b9cd
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:18175d81d8623eb41b4f3bfcc73e5053a74f65d64b09d2da127710ad549f080e
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: e10a26e9d62fcb2eb0ebe83c57fdfd1815e7354e
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:5987928a21968a5166ba8ac4478b1308abdafc756a7b0acc2cdec2bb88cb97ce
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ada7aa2563622e4fe77d50bc3e6be3d17fbcbe6b
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:00a83c4465ce876e4cfddda2a2bc9fceb3d10e1b45a13a7288aead8e6d1e2076
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d7672302496aa3328609a817e2e6b722b33afe9c
        url: https://github.com/stolostron/provider-credential-controller
status:
  conditions:
  - lastTransitionTime: "2026-01-28T01:45:06Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-01-28T01:45:06Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-01-28T01:45:06Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
