apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/ocm?rev=502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    build.appstudio.redhat.com/commit_sha: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    build.appstudio.redhat.com/target_branch: backplane-2.8
    pac.test.appstudio.openshift.io/branch: backplane-2.8
    pac.test.appstudio.openshift.io/check-run-id: "54139159031"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-qxbsqr
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/placement-mce-28-on-push-w9ksq
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.8"
    pac.test.appstudio.openshift.io/original-prname: placement-mce-28-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/ocm
    pac.test.appstudio.openshift.io/repository: addon-manager-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    pac.test.appstudio.openshift.io/sha-title: Add MCE_VERSION and SOURCE_GIT_TAG
      environment variables to registration-operator Dockerfile (#475)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/ocm/commit/502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    pac.test.appstudio.openshift.io/source-branch: backplane-2.8
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: ocm
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-28-release-mce-28-4222d":{"lastUpdateTime":"2025-10-30T23:48:52.962266061Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1761867341"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/ocm
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-28","status":"TestPassed","lastUpdateTime":"2025-10-30T23:48:52.962266061Z","details":"Integration
      test passed","startTime":"2025-10-30T23:48:18.983339394Z","completionTime":"2025-10-30T23:48:52.962266061Z","testPipelineRunName":"enterprise-contract-mce-28-mcvj4"}]'
  creationTimestamp: "2025-10-30T23:48:18Z"
  generateName: release-mce-28-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/build-pipelinerun: placement-mce-28-on-push-w9ksq
    appstudio.openshift.io/component: placement-mce-28
    pac.test.appstudio.openshift.io/check-run-id: "54139159031"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: placement-mce-28-on-push
    pac.test.appstudio.openshift.io/repository: addon-manager-mce-25
    pac.test.appstudio.openshift.io/sha: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: ocm
    test.appstudio.openshift.io/pipelinerunfinishtime: "1761868092"
    test.appstudio.openshift.io/type: component
  name: release-mce-28-4222d
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-28
    uid: 1bb16185-3532-42f1-8819-a53d8cfd38dc
  resourceVersion: "5649480023"
  uid: 9a64c016-469e-4db7-bcef-e9479213293c
spec:
  application: release-mce-28
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-28@sha256:ed9818a6df290f43cbe726695dde0c9d265a2d34ece2e59af27570da0692063f
    name: cluster-api-provider-agent-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 30182ceaa8ce4bbe37137274a734329a50f63271
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-28@sha256:05b6e9f42b50249065ffb01ef369ef5645ad154cdb2ce4aa687f23e948a03d95
    name: cluster-image-set-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fe9bc44701aed182cdd7ccc427dd8e0c3b6cf0d0
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-28@sha256:69eb2a0455116a9a4a9c7220eae9410e0446e87c71f0dbf0f5017b59fceabb5a
    name: hypershift-addon-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ed3155ed984f69f2f4e5d1b5f78f54b2cb09ffc3
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-28@sha256:16f9d8ab07e8c0165d9afccd22a90e959d41ef37574b771cf8cf5496ae73966d
    name: image-based-install-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 510c7535d9c5cacc934b1baa6448b0a40502d01c
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-28@sha256:542e3c1fc30cc32242c382a3fa95b7c716ab3d43cfc86ca93856aac3a60297b9
    name: registration-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-28@sha256:3214da73bfe8bfe1e3af7d3eca96cdfe38ae0cd61deb304c9f71933d7f77214d
    name: work-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-28@sha256:8e69bf62e865b7b26e64a3f2caa50e424e10aa1f84ec8284d082bcf835e829b7
    name: backplane-must-gather-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ccc2321a183c5c33ea7f3cfa84d1726d7042e2d6
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-28@sha256:ca2e77c6a79142a4021401913be52a62c332dadf4e55ff907cf0c62b52b82fe4
    name: cluster-api-provider-kubevirt-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bf9721135d98560e9840aa76cd8ccb8d3b7e3ff1
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28@sha256:d620769e731f4517cbc9e8a1b1f8bce2e201d15c771b5d5ee2d45bc9e6a398c3
    name: cluster-curator-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c66264d417949884041d549f0bfdae65a011ca77
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-28@sha256:95b9c6e4d99eaa96420eb01c32ea6c6d4d7fb44c82f4dbddb3c1f7d7bf3e1a40
    name: cluster-proxy-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 85a828b91eda63beb30ba2104c21718f5de74305
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-28@sha256:668a79e61e09d7feb8dbc390038d7a8b32d54dd7acb6d73c5549fd58cda2dad7
    name: discovery-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 740753a9cf15d15857f22089f82627bf5f3e4088
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-28@sha256:32329a1a6c2d5a31700c0ace7e20e9130645bffde659109b5c1a8d1e6edfb113
    name: managedcluster-import-controller-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 72be166c28a115ee5f104afb5081da59acd01be6
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-28@sha256:e8a6fc082eeaf4e8bb110d36315ccb829379826a9161cc5c4e4250b8f801d32f
    name: provider-credential-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ac181e585fd81be1f0285291ab7d2dd83c2c1452
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-28@sha256:8e36123793bdf029d200e2e92f5590847c9517ed59a718ebaebd5114ea9eee3f
    name: backplane-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cbef8482b875b55cdd7f50b2d439172fa6db2cba
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-28@sha256:eeb210a85c73ee423fd8ef465438ec469835a2e0b4b6d407491bd3b6faf08ec6
    name: clusterlifecycle-state-metrics-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7c5d1b94fed1c79d4c3179d0be7bddd1e9c08892
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-28@sha256:07d89c67e25d70b8b5d2e26f51c7c4493f851101695815baab40bbeaab10f70c
    name: console-mce-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 0dda8e3244fec37ac749aa9e90d523a9becb67b5
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-28@sha256:ff6710ffdd73e686114dbc9193ffa33d34a83f741e8520de87a1cfa8e3ee5e1d
    name: multicloud-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 88fc6e87964fe89682d7e740ebbe31ae27e91888
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-28@sha256:0d22f447acb5c1270e369ef784f8dcfb50c10cabcfd263f65f4d7071f02ccd64
    name: placement-mce-28
    source:
      git:
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-28@sha256:c0b4e5d46543b3387c06e0bc504d863f928406db920996d9f4cb0b504f29626c
    name: cluster-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 974775787c8f27de637f454f5bc51446ac75370b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-28@sha256:01d6a1e31cc6ccda49a3a5eb3a02bdfe3a17d14cc2d610895c2882997bdb3a13
    name: clusterclaims-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0458daeb54db76bc4b95853a6cd22f6212ac5252
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-28@sha256:4a77d108cafc9284aeb479cc6d23dc58ab9970aa0238900902a00ac78df2a3a8
    name: hive-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: e46865d5ef1c8caa295847bac9764dd11e661421
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-28@sha256:72744c5cada9d5c9da53ea7d8297ee8f1624ae6bb9d999d89d83d4ac8e2a8bf0
    name: hypershift-cli-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: ae78f0350757280025bb35503606cdbbedccf9e6
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-28@sha256:41b28abc0d5c4dc707e3c56b0549201c7fba72f2080830ac25248c9334b024af
    name: hypershift-release-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: ae78f0350757280025bb35503606cdbbedccf9e6
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-28@sha256:8d1839a897ad1a796a03ed2089fe43bd07781a9971a30401b47b81de63b1fdd6
    name: kube-rbac-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 7c18f8b5519a2d04a920679ed9faade52fec02f4
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-28@sha256:6e53392d66ce2168d64aba0613b44534030c9fb28f2fc245d98b703c4d1dbe71
    name: managed-serviceaccount-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f6f650cba5c5fd71afd110fe9c8b9e5603686fa8
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-28@sha256:c2092405af37d7c52671eb84ca02343b81c0e7f6223d9ae61c2337b1081cabc9
    name: registration-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-28@sha256:5ef734610442f45e12f83698b6448c91c073aa21fdd7dd9f2656d6609d61fb0b
    name: addon-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-10-30T23:48:18Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-10-30T23:48:52Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-10-30T23:48:52Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-10-30T23:48:53Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
