apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicloud-operators-foundation?rev=5443fbd85ef366f87eb30a12d3319d2c5ff1b5a7
    build.appstudio.redhat.com/commit_sha: 5443fbd85ef366f87eb30a12d3319d2c5ff1b5a7
    build.appstudio.redhat.com/target_branch: backplane-2.10
    pac.test.appstudio.openshift.io/branch: backplane-2.10
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54160601763"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-tsnekt
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/multicloud-manager-mce-210-on-push-n67wj
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.10"
    pac.test.appstudio.openshift.io/original-prname: multicloud-manager-mce-210-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multicloud-operators-foundation
    pac.test.appstudio.openshift.io/repository: multicloud-manager-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: xuezhaojun
    pac.test.appstudio.openshift.io/sha: 5443fbd85ef366f87eb30a12d3319d2c5ff1b5a7
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #1058 from zhujian7/konflux_update_backplane-2.10_backplane-2.10'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multicloud-operators-foundation/commit/5443fbd85ef366f87eb30a12d3319d2c5ff1b5a7
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.10
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-operators-foundation
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-operators-foundation
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-fl8mk":{"lastUpdateTime":"2025-10-31T07:40:19.106363258Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1761894168"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-operators-foundation
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"TestPassed","lastUpdateTime":"2025-10-31T07:40:19.106363258Z","details":"Integration
      test passed","startTime":"2025-10-31T07:39:45.45523646Z","completionTime":"2025-10-31T07:40:19.106363258Z","testPipelineRunName":"enterprise-contract-mce-210-c9tmk"}]'
  creationTimestamp: "2025-10-31T07:39:45Z"
  generateName: release-mce-210-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: multicloud-manager-mce-210-on-push-n67wj
    appstudio.openshift.io/component: multicloud-manager-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "54160601763"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: multicloud-manager-mce-210-on-push
    pac.test.appstudio.openshift.io/repository: multicloud-manager-mce-25
    pac.test.appstudio.openshift.io/sha: 5443fbd85ef366f87eb30a12d3319d2c5ff1b5a7
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-operators-foundation
    test.appstudio.openshift.io/pipelinerunfinishtime: "1761896379"
    test.appstudio.openshift.io/type: component
  name: release-mce-210-fl8mk
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "5653752378"
  uid: 284aed47-b462-4376-ad18-1f0a04194a76
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:bbd31bba8a9760e74b6572962e81010269c7ffd2aba0a85239a07e9fa51c8320
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: db0c5ecc7e93078c55aa9e63a7a4237afdf8df7a
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:92d71fbf9a9e30a987c3b0363245c11cb785929b9ddd88443626abec5264e678
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 93cfe2d9693afbed685a343dc8762eb9e0b8a6d6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-aws-mce-210@sha256:5c6a96b53b608e9c0b817a5b10f8fe7fae190f67b5bfc96899d4d2a6854a50ae
    name: cluster-api-provider-aws-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: 19e57de3fa10a489da0265e61cbc229ca30166b2
        url: https://github.com/stolostron/cluster-api-provider-aws
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:acb2faabeafb445fa6dd9b9652775a20f517a0f5747af27ea6e5e97d0b49ba56
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ac20e9ef54eac5824b7a3700d6c5d6d388e42f88
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:148e75520220fe5c91e532454b1012e805d46639aabf8fbb98d9f8ea3e9ae402
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: ad96bb1380b3d8e8d98644782d1ffd5581811c63
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:755249d5cb9ac2af1373957a65fd8b65114c23bce3d57e5d3a0e99c2dade7d44
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 14be17ccb7fbc772a701aeecf32ee623b41858d0
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:0c7a79d2d71c36053b0644e249934ea95245c08b79ae98e4653880687a6d2bde
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65467dd9b9c74340d6bfbc4a321603b299f77bf0
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:dd6d4ca5e34a61ae57e16506f777eb16fe0b556500bf8c5202d8d7fc9cdea795
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 60a0ba97d5a4b4419facc2eff1f202765f08d4d5
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:088b3e48772aa4aeca782fd8214d32398de413f81c06417a5fe610f7832b136b
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f5bb1414d7de83938bce03688dc4cf64565be64a
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:11f572ed782e24ce34d0904069dfb89e8dccd35028aba0e2868fe894fa2d5b66
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 32ae3b23f3170293f2dfc0d910ac2898102a5b70
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:17d0e210c52b73a68fe19e404d9b81c3ce7f84466cedc47d4addecbba1839875
    name: multicloud-manager-mce-210
    source:
      git:
        revision: 5443fbd85ef366f87eb30a12d3319d2c5ff1b5a7
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:d0495aacb6011f043bd81e2b12bf0199dbb3ba518ec1dc8d83e8d41aaa81ba77
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ac2370f62deefad989cd76f8119c2bcef1630592
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:06f6c68ee79e1dfaefde756634343968b774ecaede488ad9fe5c8d103374ed5d
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3c59204843fa13ad7143075c2d2831e8a73e7a32
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:a356d4ea12733c5790d77ebdb67888c5dc90f207faffb0300544efdff07345eb
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b2312c44f2b6ef7e3ea02912d5c57aa544c24496
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:596d34c36cda2d4b75d39353b1f047a16458f757a2a0be969bc438f72da5a3bf
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4238ec88f6624ae7a12c9713cc7b04ed10b33743
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:df1f3442b1e080b94731eb5019d26c3074e78780f10960de9d74c70c08c19c4f
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 93cfe2d9693afbed685a343dc8762eb9e0b8a6d6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:f2971a489293d2f12fd39f4c0cdc918bea37b5db710ae13b90c2a46dc7056191
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: a1b67e37c54d45cca0a72cedaa9cc5b95c60d4f7
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:330b0488e11124561a99fae302a23a670c909b6807eb5f19a2be46e482d0d766
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 769a3e51118a6388ba7d9f501cb3250a001f5987
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:7efc2464dcc8a9e2bd1a610a9b4b0d1881ba1ea4e5f68afabd0088b6fabd06a5
    name: console-mce-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: b1b863d0a8529eae999eb331dca5a1b074753c24
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:4560634cf0197d60f78356dfab38a746323e093eb31c114afa468df1e602062f
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: c6a71dcc3f4a3d821a8823e75224c2caf5700098
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:36704bb23f8bfa81b26f3bdbc0f30ed78919742eb88c35e52f7181c5ee08b855
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 93cfe2d9693afbed685a343dc8762eb9e0b8a6d6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:81d0e011216fb245fde6c707509aa6fcc45caabcd4a34c3453c51c05c1b1d5a9
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 93cfe2d9693afbed685a343dc8762eb9e0b8a6d6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:cc3c603d68a4461430be4af76db3094a0a9a2093fb944221cfa2e2dc9352474f
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3b8540cf5fc042f2e27ff85afcf337d623f121c2
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:9bec6f64c7b61339082d51b08ddcf6d12db8e74297bcb658575e27ffb843c13e
    name: hypershift-cli-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 14be17ccb7fbc772a701aeecf32ee623b41858d0
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:039ecbb91eacb1f5058ad200605980deb903ac06c68cb46f9473aed12c6de7b0
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: e46865d5ef1c8caa295847bac9764dd11e661421
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:a3c7faa61f544b2796d7ba17e5051fb513668be180c273f0bcf99255068be488
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 93cfe2d9693afbed685a343dc8762eb9e0b8a6d6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:4d533ff808f0af40075fc45abc0536b1e58ef04d6096543b684a373b5a387962
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: edc48da7eae9f82248616520bab2fa15f6dda1cf
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:716ed9040daaa4951ee47d65f202717e3ccbbe1c69f14d1600f476d1ce7c4b61
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 29e32aaefce64322045cc9a4dafc1cbd1ff800e3
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:b08613781760b7f4b20995092e584fe448087c84fadbb1875176d97b781e4525
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 60a0ba97d5a4b4419facc2eff1f202765f08d4d5
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:76f4108a8e1f2fab06ce70ee30cdd0f102e2c267dd165007f57ad9f9293a7e45
    name: kube-rbac-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 45af4674a5957dfa597d9931d31698d3c367992e
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:8799b78603b12754411c5c87671f0a1e9ec66363264123fe815e658a6d90fae8
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 94b2d14bd59034e07ff4ea2111156b00df3a504b
        url: https://github.com/stolostron/clusterclaims-controller
status:
  conditions:
  - lastTransitionTime: "2025-10-31T07:39:45Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-10-31T07:40:19Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-10-31T07:40:19Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-10-31T07:40:19Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
