apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/hypershift-addon-operator?rev=640621b4fecaaa648a50995a7691c8508aa7688a
    build.appstudio.redhat.com/commit_sha: 640621b4fecaaa648a50995a7691c8508aa7688a
    build.appstudio.redhat.com/target_branch: backplane-2.6
    pac.test.appstudio.openshift.io/branch: backplane-2.6
    pac.test.appstudio.openshift.io/check-run-id: "53922350951"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-qouqqf
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/hypershift-addon-operator-mce-26-on-push-4zlsb
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.6"
    pac.test.appstudio.openshift.io/original-prname: hypershift-addon-operator-mce-26-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/hypershift-addon-operator
    pac.test.appstudio.openshift.io/repository: hypershift-addon-operator-backplane-24
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: 640621b4fecaaa648a50995a7691c8508aa7688a
    pac.test.appstudio.openshift.io/sha-title: cve-2024-26147 (#607)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/hypershift-addon-operator/commit/640621b4fecaaa648a50995a7691c8508aa7688a
    pac.test.appstudio.openshift.io/source-branch: backplane-2.6
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: hypershift-addon-operator
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-26-release-mce-26-dssw8":{"lastUpdateTime":"2025-10-28T23:58:17.678140722Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1761694484"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/hypershift-addon-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-26","status":"TestPassed","lastUpdateTime":"2025-10-28T23:58:17.678140722Z","details":"Integration
      test passed","startTime":"2025-10-28T23:57:43.231248057Z","completionTime":"2025-10-28T23:58:17.678140722Z","testPipelineRunName":"enterprise-contract-mce-26-8gqh2"}]'
  creationTimestamp: "2025-10-28T23:57:43Z"
  generateName: release-mce-26-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-26
    appstudio.openshift.io/build-pipelinerun: hypershift-addon-operator-mce-26-on-push-4zlsb
    appstudio.openshift.io/component: hypershift-addon-operator-mce-26
    pac.test.appstudio.openshift.io/check-run-id: "53922350951"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: hypershift-addon-operator-mce-26-on-push
    pac.test.appstudio.openshift.io/repository: hypershift-addon-operator-backplane-24
    pac.test.appstudio.openshift.io/sha: 640621b4fecaaa648a50995a7691c8508aa7688a
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: hypershift-addon-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1761695857"
    test.appstudio.openshift.io/type: component
  name: release-mce-26-dssw8
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-26
    uid: 43345c03-0b85-4096-aa0c-17856575797d
  resourceVersion: "5621105441"
  uid: fb0727a5-f239-4c63-86a3-3e127b1bb0cb
spec:
  application: release-mce-26
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managed-serviceaccount-mce-26@sha256:689b166eb6292513be51aa5540b9f30240c735c7fa017a8631ff350e9cb0a114
    name: managed-serviceaccount-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ce098276c4944b6365f4d33912ee37f41a3b259d
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-operator-mce-26@sha256:f1cbb1bc484a59ac6b671ade22891549e704b6d1c7b2d4d85d37678de8c550f3
    name: registration-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-operator-mce-26@sha256:49f8159f78b23df4b569292e4b3c63e027550b5a3ff59cc6914523e93506eee4
    name: backplane-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 940d13fbe091770100412cf6bea8db3de54c5079
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-26@sha256:37c0dd6c4927a2f1e0fd07a9930ca6898935cbebaba059b6dede1626c9b806d6
    name: cluster-api-provider-kubevirt-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bc8f78c60dc98395d7e6d340c77e8bdc2a78125b
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/console-mce-mce-26@sha256:cb2575e7b655280e998117762fc026dd8bbda549afff2b5b6498f209d99d894f
    name: console-mce-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 6cb954ea444d06b54adaf6d1439d8c13b128494a
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/discovery-operator-mce-26@sha256:886d2bc4b3166a261535591fe432ff3193ed7291f66a4359e29b0738ee82e89b
    name: discovery-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0d7cb97d18e1d86282af08b093ac4ffe2a8ae796
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hive-mce-26@sha256:c208f6f65601b60e3525c9307b49bdad7f5d560081c460181fb758c415a724f9
    name: hive-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: fc3dac72b746bff19706dd4d6cc0854f522de086
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-26@sha256:23e97ee0120f65fb1d53b4a9c2f6a9b888b02215a67e4114d21e0305805191ee
    name: image-based-install-operator-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 738615fa3eabddd0a5e025707685a114ad2a0cc6
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/managedcluster-import-controller-addon-mce-26@sha256:eab56499822b5dee474564bbfdb937eefae7912e23d7384a5c44bd885cf37fe8
    name: managedcluster-import-controller-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 51eb1f95ca9473e985f85229ea73b5537d8bf0fa
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/multicloud-manager-mce-26@sha256:dc7a8b3e7af1dc0dadb8acadce8656f43ab5e02f9bdf4b4bc4521424aba64fe0
    name: multicloud-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e8b8f67c6faedb8a700f3d7f48d94882ebdad266
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-26@sha256:1c29b365b7a0cfff9d5cf2bfc5f088858d533e6e9baaffa840594bb0cc5775f2
    name: cluster-api-provider-agent-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 288c313de4f44e200f47ba99a89818d5cb462e13
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-addon-operator-mce-26@sha256:e3dac3b62badf3bae57acffd3772ef9512c6da2149f76b4ddf4268599f5eb298
    name: hypershift-addon-operator-mce-26
    source:
      git:
        revision: 640621b4fecaaa648a50995a7691c8508aa7688a
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-26@sha256:e3da9891628cc4b4f283d131603beb8b36a4e84d25d191d2c978ab42f38a7f76
    name: hypershift-cli-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 7e33d8351a4e924e5b39f15cde7736bb193782ee
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/placement-mce-26@sha256:531934c6a122f84ba07faa5b11e1b0e270ad286890fa56e712365b0b8506b834
    name: placement-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/provider-credential-controller-mce-26@sha256:6b7b98c97e79454f4696d64d324d22e865144bd41c180084c8d62222cfa5990f
    name: provider-credential-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 07088723d86c6be44e9b7f1689b026c84153969c
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/backplane-must-gather-mce-26@sha256:219e9aba03d8aaf1b650ae21df12bdaa438ce852c0e9527b8079615aa9dcbf7c
    name: backplane-must-gather-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: afdeeeea98604a995b897400d132b7d654212450
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterlifecycle-state-metrics-mce-26@sha256:555a0416358d9363350674e0b79023d6096903f6aeafadfba3ac0b2dd28d1430
    name: clusterlifecycle-state-metrics-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 87b8d77b18c407a5e2e13455c544fe880940f27d
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/hypershift-release-mce-26@sha256:a5cfc95a5fb641e67c166ac81720bd425aceb8945de53ad9ed85011abbfbe6b2
    name: hypershift-release-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 7e33d8351a4e924e5b39f15cde7736bb193782ee
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/kube-rbac-proxy-mce-26@sha256:6e68b23e19fd3d47afa7472b5387fa1963d2730be6b4f7848585af8d72661713
    name: kube-rbac-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 62f9ccefe5fdf6f396385be838f8d6ee5ec2ceea
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/registration-mce-26@sha256:9593677a76dd32bba37f16cd91841864b9140d68dd13fee7e974df88f5215d2c
    name: registration-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/work-mce-26@sha256:69897ed4da0d1035910af34de90eaeca9984b047b85641aaf666d744205d3a8d
    name: work-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/addon-manager-mce-26@sha256:c729f4aac4f9c1f29cf147a413e52faaeae91bd18ec038eb2063362250078261
    name: addon-manager-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 348466e00a47c3303aef21439a44dd0883864254
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-curator-controller-mce-26@sha256:61ca2a5516c971c60da357d97a253dec6bd528f4131fc5494d02e2c9b5fc224e
    name: cluster-curator-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dc4eae41f4f1ac38518913711acd6c057c1e4dd5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-image-set-controller-mce-26@sha256:81d8f01ea465dffd067c6fb094119bd8fd640a43e09ee60e0a996e5a6822d4a1
    name: cluster-image-set-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6c033d8c4555acf9bb3c1db49dda1a9b0e4533a2
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-addon-mce-26@sha256:4b6437973e6c6663a292b5842231ce99efba3d6b54c0191e84836109959cdd4b
    name: cluster-proxy-addon-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2ff4f0c8c87bc942d07b7b6bb6d30fea28f288a2
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/cluster-proxy-mce-26@sha256:b91fb378c713dec9f3bc463eb587c16f1d96e202a8040cb3c52b01b3965e9e53
    name: cluster-proxy-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 18963aee595b0afd2620d67236bfe6960d804cd1
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-26/clusterclaims-controller-mce-26@sha256:4dd025072f413f6d89766d8ecc006a6f03d8e25713dae6d477a7062d9e0ebd9f
    name: clusterclaims-controller-mce-26
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0f2608d267a6ea253e443046a93be43cc5fc2938
        url: https://github.com/stolostron/clusterclaims-controller
status:
  conditions:
  - lastTransitionTime: "2025-10-28T23:57:43Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-10-28T23:58:17Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-10-28T23:58:17Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-10-28T23:58:17Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
