apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/backplane-operator?rev=3e7dbed25fe2478e7da64e0e51933776eb564afe
    build.appstudio.redhat.com/commit_sha: 3e7dbed25fe2478e7da64e0e51933776eb564afe
    build.appstudio.redhat.com/target_branch: backplane-2.8
    pac.test.appstudio.openshift.io/branch: backplane-2.8
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "64576404786"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-kghwjv
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/backplane-operator-mce-28-on-push-8zpdh
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.8"
    pac.test.appstudio.openshift.io/original-prname: backplane-operator-mce-28-on-push
    pac.test.appstudio.openshift.io/pull-request: "2819"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/backplane-operator
    pac.test.appstudio.openshift.io/repository: backplane-operator-qa7p
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 3e7dbed25fe2478e7da64e0e51933776eb564afe
    pac.test.appstudio.openshift.io/sha-title: |-
      [backplane-2.8] Bump Go version to 1.25.0 (toolchain 1.25.2) (#2819)

      * Bump Go version to 1.25.0 (toolchain 1.25.2) to resolve CVEs

      Fixes:
      - CVE-2025-61726: Memory exhaustion in net/url

      Updated:
      - go.mod: Go 1.25.0, toolchain go1.25.2
      - Dockerfile: golang:1.25
      - build/Dockerfile.rhtap: rhel_9_1.25
      - go.sum: Updated dependencies

      Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>
      Signed-off-by: dislbenn <dbennett@redhat.com>

      * updated Dockerfile go versions to 1.25

      Signed-off-by: dislbenn <dbennett@redhat.com>

      * Update helm.sh/helm/v3 to v3.18.5 to fix CVE-2025-55198

      This addresses the YAML parsing vulnerability (GHSA-f9f8-9pmf-xv68)
      that affects Helm versions prior to v3.18.5.

      Also updates related dependencies:
      - k8s.io/* dependencies from v0.33.2 to v0.33.3
      - sigs.k8s.io/yaml from v1.4.0 to v1.5.0

      Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>
      Signed-off-by: dislbenn <dbennett@redhat.com>

      ---------

      Signed-off-by: dislbenn <dbennett@redhat.com>
      Co-authored-by: Claude Sonnet 4.5 <noreply@anthropic.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/backplane-operator/commit/3e7dbed25fe2478e7da64e0e51933776eb564afe
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.8
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-operator
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-23T19:02:25Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-28-release-mce-28-20260223-185347-000":{"lastUpdateTime":"2026-02-23T19:03:02.971674091Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1771872827000"
    test.appstudio.openshift.io/pr-status: merged
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-28","status":"TestPassed","lastUpdateTime":"2026-02-23T19:03:02.971674091Z","details":"Integration
      test passed","startTime":"2026-02-23T19:02:25.921869693Z","completionTime":"2026-02-23T19:03:02.971674091Z","testPipelineRunName":"enterprise-contract-mce-28-v627z"}]'
  creationTimestamp: "2026-02-23T19:02:25Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/build-pipelinerun: backplane-operator-mce-28-on-push-8zpdh
    appstudio.openshift.io/component: backplane-operator-mce-28
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "64576404786"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: backplane-operator-mce-28-on-push
    pac.test.appstudio.openshift.io/pull-request: "2819"
    pac.test.appstudio.openshift.io/repository: backplane-operator-qa7p
    pac.test.appstudio.openshift.io/sha: 3e7dbed25fe2478e7da64e0e51933776eb564afe
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1771873340"
    test.appstudio.openshift.io/type: component
  name: release-mce-28-20260223-185347-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-28
    uid: 1bb16185-3532-42f1-8819-a53d8cfd38dc
  resourceVersion: "7438442099"
  uid: 8b2532ee-0e4a-4ca2-b39f-7dd91b6e0100
spec:
  application: release-mce-28
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-28@sha256:24f2dd9e46b3b136422890c179900f58f580055079be42faf2a13337762857ed
    name: backplane-operator-mce-28
    source:
      git:
        revision: 3e7dbed25fe2478e7da64e0e51933776eb564afe
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-28@sha256:bc6a481c722e63152809ee0e6814f5773b36202e12fdf6a375592fcc0f4f1aaf
    name: clusterclaims-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5020ff9adbe2e5a36a9c6fcea671ed30f1c0e14d
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-28@sha256:4f28b53b531661c418621ad1e40150b82715c96a4ec5a370a97777bfdb39551e
    name: image-based-install-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 0a61a7031928e52ed2475f86f02c6e86fe14bcbc
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-28@sha256:a5983d94230c2cdbfde633a5a35e5b2d38ace3c6c8aa5d5f24071c76f65e3862
    name: kube-rbac-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 029c4143b89321a8eea4f9eea84d3e861fe095b0
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-28@sha256:d872404c0761135e7d1a6a539849cff2caa11e4bd55cc25b59331bcf8a275bb4
    name: managed-serviceaccount-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3c4993a467298be8ef8f5c0af6f973c07b9f9d44
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-28@sha256:8afdbde36e167e9f3cde8f8a34881c120d35cbd68d38770bc760aba05ccd0677
    name: managedcluster-import-controller-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 79800e5db58d2350c5178fbce7fc5562ec4315e8
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-28@sha256:4e0b2399539bca95a548eb4020796af096e98ed4e53b546c60433fbaf7fb43e1
    name: provider-credential-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: df73052c0b11b6dd1912da94dd7f8af713ed9818
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-28@sha256:7bcee0a7e82ca752502c7d8ed8485cf174973bca9657765bcd02f1ff8c312a3b
    name: cluster-api-provider-kubevirt-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c7b45c1b5b0534cae7952e3c37df67645623ec86
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-28@sha256:f6714ecfd0a40a8fca123b3a0344c35edb239f8e20778453609b8d4d567f44cf
    name: registration-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 5d21ec7665d4ab8893000d687d507852de3995c7
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-28@sha256:fdb54ac58faed8cb0b17156bf0c7e7d858aa265d5ea1e856772759ec3fc99133
    name: work-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 2b2e59df42f472ffd3efeaca1950521b402bbd25
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-28@sha256:56aaceae72bf24bf20a6d544bbd66c84fe8b085df03c0981c206853451ba2ed1
    name: addon-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 5d21ec7665d4ab8893000d687d507852de3995c7
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-28@sha256:c07a36abe2780aaba814377d3ac64e47bffd5f0461721db26a8f7c2d786bed68
    name: cluster-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: b7aeb90761c3589eba0ea05f076b9bd8c79d828b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-28@sha256:364ef37b83fa4f008c489c36967c6d9b54459c8df3d9c7c35aac7b1e4b296fac
    name: console-mce-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: db57689b0dbbe147cb28a9f465558d25b6924f9f
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-28@sha256:0cdf7d6e706334114f8377b5cc8b654377142e26c37376a42c3e05aaf8f7da97
    name: discovery-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65c5a887a03890ea1ac6066b7d2578e8e5affc7d
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-28@sha256:bcace772b94d75a5dbe6859fd2d1a02d8431a638f2599a7153a8bd35d5d12174
    name: hypershift-cli-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 345a264afcc02ab915c2973f6917ca5d1d68eb36
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-28@sha256:3cbc55f01008bdd60898a1f2a63bb510f8c8272a57ef48d7b1a2d399d5056549
    name: multicloud-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 24d265d5e884fd15f1ee535b3ecbd462a7e918ec
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-28@sha256:c4db15d0bbde8a6df5188bd95be2cd017e66a793aa8830256befc095040ba76f
    name: placement-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 5d21ec7665d4ab8893000d687d507852de3995c7
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-28@sha256:6afe112584e8bd75c8d14fd405ce82c503ed6499bea611e9d7c717d86e5e22f9
    name: registration-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 5d21ec7665d4ab8893000d687d507852de3995c7
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-28@sha256:19bc5e24980352052a1b2f962a99621dbefa8c97a3d0ebb70213e5f428937e7d
    name: cluster-api-provider-agent-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0983bd76e55320cac1be02ad5cd38df0a7aa8110
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28@sha256:bc50aa5a1749a634fc41330a8494eccc4e12e986dc3137a00a2474f344610697
    name: cluster-curator-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: af5f1f569331099ae358d0a25a926c5e50afa79f
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-28@sha256:11eaa1bf8b2b18ae5901d874cf09936171a106eaffe1e1c121acfec92e69c2ff
    name: cluster-image-set-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 525da0b6a08fa1c6745b772541b778db2a1eeb64
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-28@sha256:95397a21b30ceae443d61f01def55a6bb219fcb5ee8a6f3025e65523f9602bb5
    name: cluster-proxy-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 74e1ed8fe8fb544a9b235ea25de39f6d5cecdeeb
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-28@sha256:0c4c7bbc9886e8e9f4dafbf964992d805023f88c94cedc5b757ddbf300a23427
    name: clusterlifecycle-state-metrics-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1a0247a9c5f109854a0d953b1cb0cd388b40bfab
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-28@sha256:e65bce1b5e094637a6f97c3bc817828251ba536454b566a12eaf4ea9c8bc18da
    name: hive-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: eaffb16d20c134914d960258f84043dad85ba965
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-28@sha256:c52b2b42b1f0f5754e42880589b9e5e9c57c75bbb387070151b752944c6e2155
    name: hypershift-addon-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7bd03cc4d984032b6c65fe4af95dc1e24355c311
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-28@sha256:3a3af27e69d923f19631daa57ab0d8dcacac92c92019b084413ab2cdc7d4f641
    name: hypershift-release-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 345a264afcc02ab915c2973f6917ca5d1d68eb36
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-28@sha256:c6f370e182d8fd14bd54f0da3aa65c8da716f821f66aec17e117636bdc2673fd
    name: backplane-must-gather-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2276606be9ef843d23aaabf1b1808a297339b37e
        url: https://github.com/stolostron/backplane-must-gather
status:
  conditions:
  - lastTransitionTime: "2026-02-23T19:03:02Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-23T19:03:03Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-23T19:03:03Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
