apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/multicloud-operators-foundation?rev=c5554d9cb0c27f2dab1d99a7bfd0d2f98d0fd83d
    build.appstudio.redhat.com/commit_sha: c5554d9cb0c27f2dab1d99a7bfd0d2f98d0fd83d
    build.appstudio.redhat.com/target_branch: backplane-2.7
    pac.test.appstudio.openshift.io/branch: backplane-2.7
    pac.test.appstudio.openshift.io/check-run-id: "39271585475"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-sinbps
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://console.redhat.com/application-pipeline/ns/crt-redhat-acm-tenant/pipelinerun/multicloud-manager-mce-27-on-push-72ltx
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.7"
    pac.test.appstudio.openshift.io/original-prname: multicloud-manager-mce-27-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/multicloud-operators-foundation
    pac.test.appstudio.openshift.io/repository: multicloud-manager-mce-25
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: c5554d9cb0c27f2dab1d99a7bfd0d2f98d0fd83d
    pac.test.appstudio.openshift.io/sha-title: 'chore(deps): update konflux references
      (#908)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/multicloud-operators-foundation/commit/c5554d9cb0c27f2dab1d99a7bfd0d2f98d0fd83d
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.7
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-operators-foundation
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-operators-foundation
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"mce-27-placeholder-ec-release-mce-27-mgvw7":{"lastUpdateTime":"2025-03-24T06:34:43.851769271Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1742797189"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/multicloud-operators-foundation
    test.appstudio.openshift.io/status: '[{"scenario":"mce-27-placeholder-ec","status":"TestPassed","lastUpdateTime":"2025-03-24T06:34:43.851769271Z","details":"Integration
      test passed","startTime":"2025-03-24T06:29:58.092067353Z","completionTime":"2025-03-24T06:34:43.851769271Z","testPipelineRunName":"mce-27-placeholder-ec-872rm"}]'
  creationTimestamp: "2025-03-24T06:29:57Z"
  generateName: release-mce-27-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-27
    appstudio.openshift.io/build-pipelinerun: multicloud-manager-mce-27-on-push-72ltx
    appstudio.openshift.io/component: multicloud-manager-mce-27
    pac.test.appstudio.openshift.io/check-run-id: "39271585475"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: multicloud-manager-mce-27-on-push
    pac.test.appstudio.openshift.io/repository: multicloud-manager-mce-25
    pac.test.appstudio.openshift.io/sha: c5554d9cb0c27f2dab1d99a7bfd0d2f98d0fd83d
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: multicloud-operators-foundation
    test.appstudio.openshift.io/pipelinerunfinishtime: "1742797789"
    test.appstudio.openshift.io/type: component
  name: release-mce-27-mgvw7
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-27
    uid: 6e21dfad-3407-4ba4-9e28-db395322f882
  resourceVersion: "3441830380"
  uid: 6cd29394-5c7c-4122-968c-d596adfad80d
spec:
  application: release-mce-27
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/hypershift-addon-operator-mce-27@sha256:93374f994730b4a715aa904b4b2eebb278f5b2c458a9c3de23d14cc65014a967
    name: hypershift-addon-operator-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 49a5359abba74334d9054d04b3f0b86126690e4b
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/kube-rbac-proxy-mce-27@sha256:4c2f1b1b422563c84b08f0c0df38696502890fd9ffcd85b36a352b85287ad5aa
    name: kube-rbac-proxy-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 989e0e7be72a6863472eb019f8c4af98fd76c99c
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/work-mce-27@sha256:c399eea5fc20b5122fbebf3ec0157748c31ac24258e619d494ed6da82808da93
    name: work-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: acabdd3c6ef7a1a3532a14cd5fa4a45e77034cc5
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/backplane-operator-mce-27@sha256:04d353762e0d750b49b1d531e63a4848af12e157d931df60dcdcf0297224858e
    name: backplane-operator-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 62ce52380530e871680b3a8ccca18e230419cde9
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/console-mce-mce-27@sha256:480f4a9d5bc50220c2307b9a9f90524201b0c28ae807709687be27ec21fa6abf
    name: console-mce-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 39552e8dc7732a7523ee693b2ec9850eefc68f4d
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-27@sha256:2112735b10464052eba19dd36e9c11776815fc092c3e6ddc6e28e4cea3e6ecb4
    name: hive-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: f56c4bc5d67aa2b695f5d2e73e813b2f9efdc988
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-27@sha256:275b4b9b64fb6efc0f0290097a1e78e7b522ca52ed4265f750a4fc225037a3b8
    name: image-based-install-operator-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 9c93e7af7b83ad31ceb96c4b38e948403436c8a3
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/placement-mce-27@sha256:9cbcb38d4a2f9adbb5430346a28108431edab5d5d8d4b35dca53ea5027d71de0
    name: placement-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: acabdd3c6ef7a1a3532a14cd5fa4a45e77034cc5
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/clusterlifecycle-state-metrics-mce-27@sha256:78709bd1e02765f97f88231985609d2802a326f6a82f949d3e59412ae4d77dd2
    name: clusterlifecycle-state-metrics-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 3560155c0d1b8407398eab63cae621a072372158
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/discovery-operator-mce-27@sha256:b3dd7b6a8b5067a24d66b11de423f85f99acc7c05f02633fdf2049c7eb7eb4e3
    name: discovery-operator-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 25fb208d6f4fab4643583afcc3bcb294edb1fc50
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/clusterclaims-controller-mce-27@sha256:4ea7e3e1d81e8c1a95a077a72199bc5832aa18f0b51ed81ef656e31b39450562
    name: clusterclaims-controller-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0355474dfeda247bbb26524fdcd91a17ea75be6c
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/managed-serviceaccount-mce-27@sha256:0db79cb8c003adaea746fa8294c1ba604b0f67b66938deaafd12ad02c2981dae
    name: managed-serviceaccount-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 169a458eeb740c71edc85b96006ca4aa16f7a2a3
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/managedcluster-import-controller-addon-mce-27@sha256:a941fddc88be9af15e27e964da0a15748f64a6c8c9d81f8daf77d3fa66748522
    name: managedcluster-import-controller-addon-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 43c512c6ab5f5a03aa384da8687d2dae8967bcfe
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/multicloud-manager-mce-27@sha256:e00b4cdbc496997840b0bbcd6c1df98d4870643bdb410528b428259ef6404402
    name: multicloud-manager-mce-27
    source:
      git:
        revision: c5554d9cb0c27f2dab1d99a7bfd0d2f98d0fd83d
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/provider-credential-controller-mce-27@sha256:0d28ae663148a455189972423686bbb770318e0984b33ffb90e1d62407bb5455
    name: provider-credential-controller-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 58044a0647b6dd76e7d6782d64f5fe0163d2f8bb
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/registration-operator-mce-27@sha256:9e96a1a1d1314ebf832152e451136408bdb3cd3b9347d668c6224a9b46f84cb2
    name: registration-operator-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: f405425f25500a552bd9b499444ae57e16d51aa7
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/cluster-image-set-controller-mce-27@sha256:9049b75f022523222333e9528398070aaf6f77cdcc05b9ccb25712366e4b05e2
    name: cluster-image-set-controller-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f61057ac73212d0206046a23e73f13fb3276f237
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/cluster-proxy-mce-27@sha256:4fd7426f691f696e972173226b0d4b2d9498f5bede26f29f68eaba770cc537a4
    name: cluster-proxy-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 7637633cda2fbe63d1997d07a1eaeaf3c3c9cb7e
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/cluster-curator-controller-mce-27@sha256:25103953d5ca258c378222e88acbbdbf6d077d9f410ffa1b561a9b022e49365b
    name: cluster-curator-controller-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f20603da25a2fa233bda5acc58528c18ffd8499a
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/cluster-proxy-addon-mce-27@sha256:0b807cad8df9de51790b023608f5649796c8c0389805b3506368a77a63c56a23
    name: cluster-proxy-addon-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b82598706b29a045659171af959b7c0cad87ff2f
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/hypershift-release-mce-27@sha256:e7d9ba67777e284ffe80547047bad6ba19e03de062feb19d388fac9e7fe814be
    name: hypershift-release-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 75c08e06e95a4ae6bd272734c9a53140c9b423e3
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/registration-mce-27@sha256:9ab5556aa1ea594087926655aef39ef523388117213469121ed8408966bf2502
    name: registration-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: acabdd3c6ef7a1a3532a14cd5fa4a45e77034cc5
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/addon-manager-mce-27@sha256:874a55bd3d481794a5d4cc784f3fef5e34b8a541bc5f8ad2bf30746e839a9e7a
    name: addon-manager-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: acabdd3c6ef7a1a3532a14cd5fa4a45e77034cc5
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/release-mce-27/backplane-must-gather-mce-27@sha256:026759d5a94102c47199fab5806bc28b6152e83a8555902abcc8b4c9ced8d600
    name: backplane-must-gather-mce-27
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fe7049d0363891667738553cb25beee872dcb2d1
        url: https://github.com/stolostron/backplane-must-gather
status:
  conditions:
  - lastTransitionTime: "2025-03-24T06:29:58Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-03-24T06:29:58Z"
    message: Snapshot integration status condition is finished since there are no
      required testing pipelines defined for its application
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-03-24T06:29:58Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-03-24T06:29:58Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
