apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/backplane-operator?rev=97bb346cc05cddc1350f31c45257d4321a840118
    build.appstudio.redhat.com/commit_sha: 97bb346cc05cddc1350f31c45257d4321a840118
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "50393020097"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-vfhvvn
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/backplane-operator-mce-29-on-push-7n8gl
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: backplane-operator-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "1874"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/backplane-operator
    pac.test.appstudio.openshift.io/repository: backplane-operator-qa7p
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 97bb346cc05cddc1350f31c45257d4321a840118
    pac.test.appstudio.openshift.io/sha-title: '[create-pull-request] automated change
      (#1874)'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/backplane-operator/commit/97bb346cc05cddc1350f31c45257d4321a840118
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-operator
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-n6jf4":{"lastUpdateTime":"2025-09-15T14:26:49.292616335Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1757945737"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.9
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2025-09-15T14:26:49.292616335Z","details":"Integration
      test passed","startTime":"2025-09-15T14:25:58.515934327Z","completionTime":"2025-09-15T14:26:49.292616335Z","testPipelineRunName":"enterprise-contract-mce-29-r5zpn"}]'
  creationTimestamp: "2025-09-15T14:25:58Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: backplane-operator-mce-29-on-push-7n8gl
    appstudio.openshift.io/component: backplane-operator-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "50393020097"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: backplane-operator-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "1874"
    pac.test.appstudio.openshift.io/repository: backplane-operator-qa7p
    pac.test.appstudio.openshift.io/sha: 97bb346cc05cddc1350f31c45257d4321a840118
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1757946352"
    test.appstudio.openshift.io/pr-group-sha: 3f5ad436ec9e59c9f4c91e27298a4c40745f9b3ecde6e100e6d73cf94ffb6f
    test.appstudio.openshift.io/type: component
  name: release-mce-29-n6jf4
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "5099203554"
  uid: 0d74e0e1-ad06-4de7-9c41-d0b8db21c8d4
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:e2e1d3464e5d3330eb5645dbeff5d370ee3c3c1e40acf3b440123f344ae8332c
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e4095780afe8c619968a478331d357b5cf6d5574
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:3b2cbdcea0c8416523012785f007f2a463db78bb3cef33dd7cb93d8dd1f558d4
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:d48dc087e6cd76ed7c03d38d1004fef3a60390f0908177d9a54e177da5669bab
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:9980131f5860f3673c6865f2b7cc1df0b9250f9c88a5fe6a5790c44266e6011a
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: c271ffae35f09ff5958568fd685c9d4183a2317e
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:6479b87c55568dccdfe8f033804903406ba73ca3223e75c98a69f5e66267ed40
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4a2c8feef2255ba92e8e76046dbf16177907f76f
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:cb8836f2b75b67358c388b8c5dab1587a661c17dd270973b436d8171b8705055
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 18e4771f30788b1e780ba3ffff8f9ff6841f3123
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:e25ee4d80c712990a6c528f5f5e9959bacd908cff0b452be4ea24fb27d4e40b6
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: c1fa0769a32eb9fa9e0437971a24f4943f8262b8
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:71e0624fefd120102e843f11835edb4c64fa82c9d08c27034d4157aae684ce31
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: e20516a287f9c8a08080a36c1604187edeb8e685
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:e4547b48d5130c3258799513ddee13dbb7276b40736f9b05fe3d12a2d66504e6
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d436871a2add0c6dc03cc165ad99e21b64775396
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:20fdb55abcbafd51040e0b2958d488968eaf42d479262ee9e554c1701ecbab7a
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 501d43cb4983422fbee372af47ef134f3a9f5638
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:fccbc5e04cd83e5645767451c48cef349eb2387e571e87a951c64b63aa274c79
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 043ad9ce26197e52b0fe519279cc310459fd7d4e
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:42736911076d8f3254b329347d94a7e440b762418c8fefcc52ad8239970c4e67
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:3db9b3d7e9ed129730133e211024babb934a03fcb9880db3c23d124b4875cfd5
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: f491c6e9c9770bdf18abfd0e0803a27ae6358f21
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:a9f3961ff2a0ed3707481b62ab9ec8927fd0b8266d7990e82606508540b10a82
    name: backplane-operator-mce-29
    source:
      git:
        revision: 97bb346cc05cddc1350f31c45257d4321a840118
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:d1cb10bfae476184b2aefb8fbc584cbd613c9dbe559629a410f2cb146970d142
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ae6a863c58c1e44dfc37b0913dc8e361f8a7515a
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:d55c492358c276cfc07f4ba6ed068d78c852e9b0cfd33b97b59c0d6e0854eeec
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b26921fb30b146a778dcc73135db785077bf0f89
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:5e9547c326df058bf9dbf9e716321c0abc3f75a63d934175283356ea3facdb32
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 06a3783c03f53edf9f9601ee9b0c3141db622b7c
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:590c466eb36c3aad8adeb176464c671cfd57bcf9eddb48db5336760da9143fa3
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b83cdc2a9e2653138b66713cb01fb94ad6c56cf4
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:b741c46b48774e72777715e5c66fb1fd873e5c96ea69fbf06452cc59039d1bac
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: fa4b1e6996bc053b889fdbb2deadc014e55b5e2d
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:86a1e5898eb08e97f2865adb26a0b56f47c9b7245fae64f8e49e3c853fc2dfbe
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cb753172342f4dfdd7e022b24ffbda99c4aa41ed
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:afcebe18da2cc443eda7aad1c050183debedeecac26c333ff88302f4d33dc486
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c618f75439aa13f19607ef4a9c9e61af0124eaa4
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:6bf7d1c2005fc79785e7a4f814c65d55c3c02d69c4b6ef62678bcbbaef16666b
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:7b5adaab6b75b4d18b7f244de9508142961705ea81c046c127bd2788d175e996
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f72f75b656967073d68e91500511a8ef991c2d5d
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:8ff8497d38e7142b7f564db8b5aed85aea340772d585336714190330b5906e3f
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 282bb4fcdda5b1918f7dde577bd59773d8090bab
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:a4e7ea18fd13cc7c92c78c1a00de3eb56fa29aae0946ca1b07f5e80344730770
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 0bed2c5241652892d67d013a360ff4163207756d
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:318a016762548a68d163eeddf50b310c60efe7135c14d144213e5df1912beb76
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:8770e04f759aa7010019e780dd59aad1c3519af88f62fda0f4946b746b980478
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:6a1843a583709bd299f12d1919ce67b3381ae06e807789fd22eaa835054b134e
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 87dff4d321e53ecdffcfcd10c0f5ea51b0a2f15a
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:8f7d0048ba2141f19fa5a060b732434a19c967fd88dbffc301bc68f728ab8249
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 0bed2c5241652892d67d013a360ff4163207756d
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:572b7c6e9cf7fa2ccf3b7d605b25e6ac81b81df1ad411639f0e6c689a8a255a5
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: c271ffae35f09ff5958568fd685c9d4183a2317e
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
status:
  conditions:
  - lastTransitionTime: "2025-09-15T14:25:58Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-15T14:26:49Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-15T14:26:49Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-15T14:26:49Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
