apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-api-installer?rev=10b95cee12cbc537943a295cd461bed6ab582176
    build.appstudio.redhat.com/commit_sha: 10b95cee12cbc537943a295cd461bed6ab582176
    build.appstudio.redhat.com/target_branch: backplane-2.10
    pac.test.appstudio.openshift.io/branch: backplane-2.10
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "51265668954"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-zkrdsv
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-api-webhook-config-mce-210-on-push-tvdxd
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.10"
    pac.test.appstudio.openshift.io/original-prname: cluster-api-webhook-config-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "307"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-api-installer
    pac.test.appstudio.openshift.io/repository: cluster-api-webhook-config-mce-29
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 10b95cee12cbc537943a295cd461bed6ab582176
    pac.test.appstudio.openshift.io/sha-title: Update Konflux references (#307)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-api-installer/commit/10b95cee12cbc537943a295cd461bed6ab582176
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.10
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-api-installer
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-api-installer
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-28mhl":{"lastUpdateTime":"2025-09-25T18:51:42.548268019Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1758825618"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.10
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-api-installer
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"TestPassed","lastUpdateTime":"2025-09-25T18:51:42.548268019Z","details":"Integration
      test passed","startTime":"2025-09-25T18:51:06.650525909Z","completionTime":"2025-09-25T18:51:42.548268019Z","testPipelineRunName":"enterprise-contract-mce-210-v8zx6"}]'
  creationTimestamp: "2025-09-25T18:51:06Z"
  generateName: release-mce-210-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: cluster-api-webhook-config-mce-210-on-push-tvdxd
    appstudio.openshift.io/component: cluster-api-webhook-config-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "51265668954"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-api-webhook-config-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "307"
    pac.test.appstudio.openshift.io/repository: cluster-api-webhook-config-mce-29
    pac.test.appstudio.openshift.io/sha: 10b95cee12cbc537943a295cd461bed6ab582176
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-api-installer
    test.appstudio.openshift.io/pipelinerunfinishtime: "1758826260"
    test.appstudio.openshift.io/pr-group-sha: 72b3ef008256132a511ab42a799a5054c1b4087880cee879ab80db01c93ebb
    test.appstudio.openshift.io/type: component
  name: release-mce-210-28mhl
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "5228574979"
  uid: efa351e7-68fe-45b7-a21c-1876bfacc6f6
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:772aa9d462076f972c451d5381c6f34d903f34ee6edc4acb4711a338d1039079
    name: multicloud-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6b9ff9ebdd68b9985400252c381be3970f502acf
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:d27778700f2ba70f9323c71021dcc991b66311964b1793ccb0d88b30baa758e4
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 707a815152c4329312a0826eee72851ae9cc33e3
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:66fa74e34e58213b60d3adeca564f7962a9a2c41800784681ffaf93405d0ac04
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 05199d10b322273b0a9989a70f4a5260695fcf1c
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:9ec94ec16a5953b4f1abdab41d091daeb691677a90913ac6098f8c343613a4c9
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 466125c2c29227d573d693d06cd2c93b68071a0c
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:14d55652ec2c7c0056defcea7703037ef93e2cbc95df5b4dfc96d72bfecd8720
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d246cfa995ba64634a593d3a9b0875dae11a1b18
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:d3221b0ae129df26e4dcec2e5d1cf406a5ef835d42d1cc3234e5372388659387
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: cf0e04a37a552646b78a6a1a61f023f4bf7ebd33
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:b0c9cc856711ff9d4552df179b07e99bb6fb7fa8a66e396141b9eb0385a480a9
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: be7a2d7b8daf37459f7b6a0d8fb9d6bea3d237c6
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:27bc7a914bd696957c4cee58d50df5bf1efce56812e535c6be538f67ee7e6552
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        revision: 10b95cee12cbc537943a295cd461bed6ab582176
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:f6eba7010266199706474714344038d1bfdae9e0cea99fd179fdc51311342e6c
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 62c16fdf6db72f4496ab176047b99231fcb506d1
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:0138a51eef84269cf9a26a2a3abebea704c4af58202db3d8266f50ef68269af1
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b6918acbf0a63ec53800f49f21f47bb347ddf52a
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:43fa2a639eddbaa4e5adad0e25557f80b608592881c7834965863e80f884ce33
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1371e4a7af93197283228bcf6b25e4340499171d
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:6ab61733c0a87762e19e4a51b88a01db47a208f1304a6eaa62d9b704db2efc22
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 24c0f1084946df1a1c58368f07d22081a7a8b62f
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:8e4268075015e670314ea3746df8547638a4c632ff30865a62900e43fd4cf3ad
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3f8fcfddb7dd985199efc597b2d99e7df48d2878
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:3aa9b90e366dd51ce7bd8fdf29a6c016935af16d668222d4dbfe7fb692207e98
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: cf0e04a37a552646b78a6a1a61f023f4bf7ebd33
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:ba9320b71962b28dba49e0ae8c4e07943bb501222db824224dec19ea342b250c
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: cf0e04a37a552646b78a6a1a61f023f4bf7ebd33
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:fc0e14fd4586af542b6f22388eae6ba0eb643c5d5cdd35eaa7cbd6b6a60475dd
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 243bbe7fb9af578a883bcc2f4eebdbfd8365c7cc
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:328d593b177154eb5d637316bb67648f06aa9fd5ebd8f2d6e345c0fdf3cdf7f1
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c1b0e4c48e4e7a23c5bee26a17b89749f91341a1
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:1719a77beef4205311e4f0fb2528c579d3c6103e90d0b66e852184b8bddf1156
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 81b9bae7f65692991626e6a6c3a2e5af80bc20c7
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:330fe104a066995b7ac3d445f3f051ffa93b7e175ec85eaedbce77859d8fa0a9
    name: hypershift-cli-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 4f3fbb4b812c882f9b13a276cc4c727e0da0f350
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:19d0441fab4940fd96ea3b6e44299919083b406fd898d559054a48059027f201
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d0fd925bfe36507187da55b08fccc26c662963a1
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:ea2bd42afbe746f00253a961dca455d859c13a07bf2886594e3b72d0015a9e22
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 4f3fbb4b812c882f9b13a276cc4c727e0da0f350
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:c7e8dc69bc3e9bc11ae13cd0bfb9520ea3e49663f2f560c6c1b15ede080afc9f
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: eaed90475e1da59b52aefb725223c21a78591636
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:6b5e4d46e21bd9c04df1e202ee4c7f578d7db6884812013276c8b0e3d58833d7
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 05199d10b322273b0a9989a70f4a5260695fcf1c
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:eb9ef7da22300ce2662c65e7c1e82e0627137208c94cdc74a704987c219a5cdc
    name: console-mce-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 7911b433e3c8d52c5baf3d24c6f48af06a83710b
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:5f7167a58dcc219210c21a0a5657bc192774c31a82d7b47bfbfe7cd605bd6a9c
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: cf0e04a37a552646b78a6a1a61f023f4bf7ebd33
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:bb91922a7d31b1aa9132de80c25283c5fbd331262f368d72c5a061e564b86d29
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: cf0e04a37a552646b78a6a1a61f023f4bf7ebd33
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:c162aa18ddf042415cb4926283300a7c9d442fc88bf28ae16303312babf729ea
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2bc44cc6d363361aa889df323ebcecab47d28862
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:256af59c4c2e18a9bf613641f0e66bb75eb4e965d0ec5a27b10fa35dde4c8b63
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65467dd9b9c74340d6bfbc4a321603b299f77bf0
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:d0c36d9b057476d7c8f4380f6d6c99dc5bd1e94cf98b1e8ceee306118ee77b41
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 5a9aa545f0956438d47586f59682a86e4d1144c0
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:1e40f94d0a014e71b049cafaeb04a21c99e89b9628a6a12de505beb2b9b32348
    name: kube-rbac-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 582bdffe4e1303744e045783a188374708c3f316
        url: https://github.com/stolostron/kube-rbac-proxy
status:
  conditions:
  - lastTransitionTime: "2025-09-25T18:51:06Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-25T18:51:42Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-25T18:51:42Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-25T18:51:42Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
