apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/backplane-must-gather?rev=2276606be9ef843d23aaabf1b1808a297339b37e
    build.appstudio.redhat.com/commit_sha: 2276606be9ef843d23aaabf1b1808a297339b37e
    build.appstudio.redhat.com/target_branch: backplane-2.8
    pac.test.appstudio.openshift.io/branch: backplane-2.8
    pac.test.appstudio.openshift.io/check-run-id: "62913235952"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-epgily
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/backplane-must-gather-mce-28-on-push-mpw7q
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.8"
    pac.test.appstudio.openshift.io/original-prname: backplane-must-gather-mce-28-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/backplane-must-gather
    pac.test.appstudio.openshift.io/repository: backplane-must-gather-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: 2276606be9ef843d23aaabf1b1808a297339b37e
    pac.test.appstudio.openshift.io/sha-title: update openshift version to 4.21
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/backplane-must-gather/commit/2276606be9ef843d23aaabf1b1808a297339b37e
    pac.test.appstudio.openshift.io/source-branch: backplane-2.8
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-must-gather
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-08T23:48:50Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-28-release-mce-28-20260208-233634-000":{"lastUpdateTime":"2026-02-08T23:49:22.496343061Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1770593794000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-must-gather
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-28","status":"TestPassed","lastUpdateTime":"2026-02-08T23:49:22.496343061Z","details":"Integration
      test passed","startTime":"2026-02-08T23:48:50.767217058Z","completionTime":"2026-02-08T23:49:22.496343061Z","testPipelineRunName":"enterprise-contract-mce-28-sd75l"}]'
  creationTimestamp: "2026-02-08T23:48:50Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/build-pipelinerun: backplane-must-gather-mce-28-on-push-mpw7q
    appstudio.openshift.io/component: backplane-must-gather-mce-28
    pac.test.appstudio.openshift.io/check-run-id: "62913235952"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: backplane-must-gather-mce-28-on-push
    pac.test.appstudio.openshift.io/repository: backplane-must-gather-mce-25
    pac.test.appstudio.openshift.io/sha: 2276606be9ef843d23aaabf1b1808a297339b37e
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-must-gather
    test.appstudio.openshift.io/pipelinerunfinishtime: "1770594525"
    test.appstudio.openshift.io/type: component
  name: release-mce-28-20260208-233634-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-28
    uid: 1bb16185-3532-42f1-8819-a53d8cfd38dc
  resourceVersion: "7154261449"
  uid: b765a7b5-3fe3-46b3-b8ad-ff5305ac2a4e
spec:
  application: release-mce-28
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-28@sha256:8580f8e1fcf51eb61a85dc5b5837b3ad34946cfd924b0e1d6c60ae41bc25633a
    name: addon-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 6f746bdb56d427076e31bd138a1093bb937cd6ae
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28@sha256:5492b5e2c66cfd863d3ebe20c506543f8874af9fb120dbda3a644745f4fefd0d
    name: cluster-curator-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: af5f1f569331099ae358d0a25a926c5e50afa79f
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-28@sha256:c89c640eec50dc92b4180f28e6c66a1e941fdfb568a0cb55b5d950d09ca0e3b1
    name: cluster-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: b7aeb90761c3589eba0ea05f076b9bd8c79d828b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-28@sha256:b3911d2613f14078974fe740c1dd20ba805589325d2cdf996ab00101d4a7b88d
    name: image-based-install-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: bc2d05ee1f883691a19374dd2d1b3a18b85d84b4
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-28@sha256:fe7d42ec32d5779dee67a1711618e1a0671b555c441971d8c9101c53925ec6b1
    name: managed-serviceaccount-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bc151c5426959eca5ab12bdac351b78a18e51604
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-28@sha256:d5950d37d180a24f7573461ab9100b2a8f5a8f0760dae249b077847ac2333649
    name: managedcluster-import-controller-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 79800e5db58d2350c5178fbce7fc5562ec4315e8
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-28@sha256:0d831cfe08e7cfdd09b0942a0aa701bfc61634cf20a6ad02dbdf9181a4740e94
    name: provider-credential-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: df73052c0b11b6dd1912da94dd7f8af713ed9818
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-28@sha256:5823448705609490084706a2d9e108e04a7f6b0dbd20a57e4b66da0f97145bcb
    name: registration-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6f746bdb56d427076e31bd138a1093bb937cd6ae
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-28@sha256:39ba0668cf913474e26c6f836e6860b8a79d41635a2b8bd09b67df9bf9b71c24
    name: cluster-proxy-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 74e1ed8fe8fb544a9b235ea25de39f6d5cecdeeb
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-28@sha256:73769c5d9b21ebdd1b288e6a19107f53572ceae8788d833fd7d3d2023cda3ada
    name: discovery-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65c5a887a03890ea1ac6066b7d2578e8e5affc7d
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-28@sha256:9112828277b8ffb21e6d5ace2593a70c75c81f71db495152a369f95571fb12c5
    name: hypershift-addon-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7bd03cc4d984032b6c65fe4af95dc1e24355c311
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-28@sha256:f32e02d8ad7f3eb456462d63a3eed5da37b32b0a99a2358708ef174942afefb0
    name: hypershift-cli-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 345a264afcc02ab915c2973f6917ca5d1d68eb36
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-28@sha256:452a2f08cd27a8762ee930c65c030741e69f74ffdec1e4197f65492a01512f2b
    name: hypershift-release-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 345a264afcc02ab915c2973f6917ca5d1d68eb36
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-28@sha256:2a440ab476bc9001a61f51cd74db478e17d172f68ba3ba7bf710b7bdaae904dc
    name: multicloud-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 24d265d5e884fd15f1ee535b3ecbd462a7e918ec
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-28@sha256:af8d3323d768ce325b932068216010317bfa131912d04141fc60dc76eabbada5
    name: registration-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 6f746bdb56d427076e31bd138a1093bb937cd6ae
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-28@sha256:53134d66b98e7faf0301ddf7853f750532ca5220b9abbd69ee38969fa07e8f19
    name: backplane-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 38ddc60c8bd9d4d3bd142074a64f225882c71793
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-28@sha256:5556230bd29819b7ae76b142e679531debaa7aa6cdafd17552f460c5989e7cad
    name: cluster-api-provider-agent-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0983bd76e55320cac1be02ad5cd38df0a7aa8110
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-28@sha256:de06d2b4297d21ff98b083b22ed32f60a278d19bb751d9be334df95cebadc40f
    name: cluster-image-set-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 525da0b6a08fa1c6745b772541b778db2a1eeb64
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-28@sha256:c3e762d7296cc029dcb1d5de29665a043f23574b91876d881d2b89ff712b8167
    name: console-mce-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 963d9d2e942bbfdebb9a0e2a4243b1ca65de10bc
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-28@sha256:2184f4bde5d2cae5ced8661f046bd0d64c7e989b689e7c38988c3f392f683985
    name: hive-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: e2f8da6a8ee6fcdd3265ad50f7270feef8ca5a04
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-28@sha256:e2f12f0e24a1ed02d49889f9ef2ec3914c9bfbf8a8c165ac87d50d1b98f49574
    name: kube-rbac-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: e5fc3a780e46b81a30fb2b60df317804cfa9d485
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-28@sha256:f01d7c6b813c2baf23bbdc6d25500ecf7b120aa2e85269ae7713b219db2997e7
    name: placement-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 6f746bdb56d427076e31bd138a1093bb937cd6ae
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-28@sha256:3263e9bd89fccca8445b677c8ba180b87235024d34c8f6d334c46ece1527963f
    name: work-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6f746bdb56d427076e31bd138a1093bb937cd6ae
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-28@sha256:41579930074fe0170499c3de0d561146174d0e52db3b4e2cca84fbdbc24458dd
    name: backplane-must-gather-mce-28
    source:
      git:
        revision: 2276606be9ef843d23aaabf1b1808a297339b37e
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-28@sha256:97eb8d652570c9f39a83f5ddb38e24fb91daed0af3382c25ee4e4aba23c6c803
    name: cluster-api-provider-kubevirt-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c7b45c1b5b0534cae7952e3c37df67645623ec86
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-28@sha256:84aeafb3f572f484d416b0fba94d20b8204ad62ccd803cbc7164aa4f60c3e783
    name: clusterclaims-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5020ff9adbe2e5a36a9c6fcea671ed30f1c0e14d
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-28@sha256:d5a614884bcfc801407fbba77b24813e4fa31335e7cd4514571b03d91ae03d83
    name: clusterlifecycle-state-metrics-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1a0247a9c5f109854a0d953b1cb0cd388b40bfab
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
status:
  conditions:
  - lastTransitionTime: "2026-02-08T23:49:22Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-08T23:49:22Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-08T23:49:22Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
