apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/managed-serviceaccount?rev=424cd94c513489372e9aa70fe78015373bcb1f5e
    build.appstudio.redhat.com/commit_sha: 424cd94c513489372e9aa70fe78015373bcb1f5e
    build.appstudio.redhat.com/target_branch: backplane-2.8
    pac.test.appstudio.openshift.io/branch: backplane-2.8
    pac.test.appstudio.openshift.io/check-run-id: "63604353527"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-czriyc
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/managed-serviceaccount-mce-28-on-push-ktbgt
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.8"
    pac.test.appstudio.openshift.io/original-prname: managed-serviceaccount-mce-28-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/managed-serviceaccount
    pac.test.appstudio.openshift.io/repository: managed-serviceaccount-zbkr
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 424cd94c513489372e9aa70fe78015373bcb1f5e
    pac.test.appstudio.openshift.io/sha-title: |-
      Fix unit tests by migrating to modern setup-envtest tool (#473)

      The old setup-envtest.sh script from controller-runtime v0.8.3 fails on
      darwin/arm64 when downloading envtest version 1.19.2. This updates the
      test target to use the setup-envtest binary tool instead, which properly
      handles the architecture and uses envtest version 1.25.0.

      Signed-off-by: zhujian <jiazhu@redhat.com>
      Co-authored-by: zhujian <jiazhu@redhat.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/managed-serviceaccount/commit/424cd94c513489372e9aa70fe78015373bcb1f5e
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.8
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/managed-serviceaccount
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: managed-serviceaccount
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-02-14T04:19:15Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-28-release-mce-28-20260214-041025-000":{"lastUpdateTime":"2026-02-14T04:19:46.910937499Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1771042225000"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/managed-serviceaccount
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-28","status":"TestPassed","lastUpdateTime":"2026-02-14T04:19:46.910937499Z","details":"Integration
      test passed","startTime":"2026-02-14T04:19:15.619006824Z","completionTime":"2026-02-14T04:19:46.910937499Z","testPipelineRunName":"enterprise-contract-mce-28-jfnv6"}]'
  creationTimestamp: "2026-02-14T04:19:15Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/build-pipelinerun: managed-serviceaccount-mce-28-on-push-ktbgt
    appstudio.openshift.io/component: managed-serviceaccount-mce-28
    pac.test.appstudio.openshift.io/check-run-id: "63604353527"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: managed-serviceaccount-mce-28-on-push
    pac.test.appstudio.openshift.io/repository: managed-serviceaccount-zbkr
    pac.test.appstudio.openshift.io/sha: 424cd94c513489372e9aa70fe78015373bcb1f5e
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: managed-serviceaccount
    test.appstudio.openshift.io/pipelinerunfinishtime: "1771042750"
    test.appstudio.openshift.io/type: component
  name: release-mce-28-20260214-041025-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-28
    uid: 1bb16185-3532-42f1-8819-a53d8cfd38dc
  resourceVersion: "7271024208"
  uid: 06a54daa-dbbb-4051-a728-274ee5abb2ef
spec:
  application: release-mce-28
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-28@sha256:73769c5d9b21ebdd1b288e6a19107f53572ceae8788d833fd7d3d2023cda3ada
    name: discovery-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 65c5a887a03890ea1ac6066b7d2578e8e5affc7d
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-28@sha256:9112828277b8ffb21e6d5ace2593a70c75c81f71db495152a369f95571fb12c5
    name: hypershift-addon-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7bd03cc4d984032b6c65fe4af95dc1e24355c311
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-28@sha256:f32e02d8ad7f3eb456462d63a3eed5da37b32b0a99a2358708ef174942afefb0
    name: hypershift-cli-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 345a264afcc02ab915c2973f6917ca5d1d68eb36
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-28@sha256:452a2f08cd27a8762ee930c65c030741e69f74ffdec1e4197f65492a01512f2b
    name: hypershift-release-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 345a264afcc02ab915c2973f6917ca5d1d68eb36
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-28@sha256:d4a4dba15d94f43486e067422c4be386f4b66108aee65e769b62f2cdf2678e43
    name: multicloud-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 24d265d5e884fd15f1ee535b3ecbd462a7e918ec
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-28@sha256:14755141b2e1bb0a9d8f30c237e89369690d5932c0492bce3373fec35184cba8
    name: registration-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 2b2e59df42f472ffd3efeaca1950521b402bbd25
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-28@sha256:53134d66b98e7faf0301ddf7853f750532ca5220b9abbd69ee38969fa07e8f19
    name: backplane-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 38ddc60c8bd9d4d3bd142074a64f225882c71793
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-28@sha256:5556230bd29819b7ae76b142e679531debaa7aa6cdafd17552f460c5989e7cad
    name: cluster-api-provider-agent-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0983bd76e55320cac1be02ad5cd38df0a7aa8110
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-28@sha256:de06d2b4297d21ff98b083b22ed32f60a278d19bb751d9be334df95cebadc40f
    name: cluster-image-set-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 525da0b6a08fa1c6745b772541b778db2a1eeb64
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-28@sha256:364ef37b83fa4f008c489c36967c6d9b54459c8df3d9c7c35aac7b1e4b296fac
    name: console-mce-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: db57689b0dbbe147cb28a9f465558d25b6924f9f
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-28@sha256:725af9fc1b3bbda4ef8df7d647dd53ac6ebb791db39f510e5d43d33871005edf
    name: hive-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 7d52d803da275b900d2737d3676d575459b5a042
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-28@sha256:b602bfc81dade0034b0bfd1d5c5b339caa4a66d85c9f50fe8a836004e2e8d98e
    name: kube-rbac-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 029c4143b89321a8eea4f9eea84d3e861fe095b0
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-28@sha256:b5520409ed5d4fb62500056e8cf9376318053f8c9837e44334847f0ca667dc4d
    name: placement-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 2b2e59df42f472ffd3efeaca1950521b402bbd25
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-28@sha256:fdb54ac58faed8cb0b17156bf0c7e7d858aa265d5ea1e856772759ec3fc99133
    name: work-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 2b2e59df42f472ffd3efeaca1950521b402bbd25
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-28@sha256:41579930074fe0170499c3de0d561146174d0e52db3b4e2cca84fbdbc24458dd
    name: backplane-must-gather-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2276606be9ef843d23aaabf1b1808a297339b37e
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-28@sha256:97eb8d652570c9f39a83f5ddb38e24fb91daed0af3382c25ee4e4aba23c6c803
    name: cluster-api-provider-kubevirt-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c7b45c1b5b0534cae7952e3c37df67645623ec86
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-28@sha256:84aeafb3f572f484d416b0fba94d20b8204ad62ccd803cbc7164aa4f60c3e783
    name: clusterclaims-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 5020ff9adbe2e5a36a9c6fcea671ed30f1c0e14d
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-28@sha256:40d2beed811e9ed93bbe14d3ace23dba3ed1a4192ee11af2016be00840cc4900
    name: clusterlifecycle-state-metrics-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 1a0247a9c5f109854a0d953b1cb0cd388b40bfab
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-28@sha256:888955c5b6236e2d0f7ffca11bbb29c65e2bcbdfb1344b98aef8f7f974d1cfb0
    name: addon-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 2b2e59df42f472ffd3efeaca1950521b402bbd25
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28@sha256:5492b5e2c66cfd863d3ebe20c506543f8874af9fb120dbda3a644745f4fefd0d
    name: cluster-curator-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: af5f1f569331099ae358d0a25a926c5e50afa79f
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-28@sha256:c07a36abe2780aaba814377d3ac64e47bffd5f0461721db26a8f7c2d786bed68
    name: cluster-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: b7aeb90761c3589eba0ea05f076b9bd8c79d828b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-28@sha256:5b241e61c3dffe09ab24f5c216ea51e5bc64c4c75b34ad8dd20d5b817b2a5697
    name: image-based-install-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 15cd9a34534557bd4776971678a32d03ba351ff3
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-28@sha256:b2c7e35b688ac1c2796cbbc23ad574b2340add97ec7ce5026e24f0bdf02643db
    name: managed-serviceaccount-mce-28
    source:
      git:
        revision: 424cd94c513489372e9aa70fe78015373bcb1f5e
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-28@sha256:8afdbde36e167e9f3cde8f8a34881c120d35cbd68d38770bc760aba05ccd0677
    name: managedcluster-import-controller-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 79800e5db58d2350c5178fbce7fc5562ec4315e8
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-28@sha256:0d831cfe08e7cfdd09b0942a0aa701bfc61634cf20a6ad02dbdf9181a4740e94
    name: provider-credential-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: df73052c0b11b6dd1912da94dd7f8af713ed9818
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-28@sha256:78ad0d14e271feca5fa8cf2339a904d3be42d94aa25029cb9dc179399f40816e
    name: registration-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 2b2e59df42f472ffd3efeaca1950521b402bbd25
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-28@sha256:39ba0668cf913474e26c6f836e6860b8a79d41635a2b8bd09b67df9bf9b71c24
    name: cluster-proxy-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 74e1ed8fe8fb544a9b235ea25de39f6d5cecdeeb
        url: https://github.com/stolostron/cluster-proxy-addon
status:
  conditions:
  - lastTransitionTime: "2026-02-14T04:19:46Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-02-14T04:19:46Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-02-14T04:19:47Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
