apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-proxy-addon?rev=825a087897bebb2dc16bbc8442126b669970810f
    build.appstudio.redhat.com/commit_sha: 825a087897bebb2dc16bbc8442126b669970810f
    build.appstudio.redhat.com/target_branch: backplane-2.10
    pac.test.appstudio.openshift.io/branch: backplane-2.10
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "89588753966"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-ctcvan
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-proxy-addon-mce-210-on-pushnkkzh
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.10"
    pac.test.appstudio.openshift.io/original-prname: cluster-proxy-addon-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "660"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-proxy-addon
    pac.test.appstudio.openshift.io/repository: cluster-proxy-addon-ezmt
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/secret-created: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 825a087897bebb2dc16bbc8442126b669970810f
    pac.test.appstudio.openshift.io/sha-title: |-
      ACM-38220: strip client Impersonate-* headers in service-proxy (#660)

      Remove client-supplied Impersonate-* headers before authentication
      so callers cannot inject groups, UIDs, or extra attributes into the
      service-proxy request path.

      Signed-off-by: Roke Jung <roke@redhat.com>
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-proxy-addon/commit/825a087897bebb2dc16bbc8442126b669970810f
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.10
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-proxy-addon
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-proxy-addon
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2026-07-24T21:02:58Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-20260724-205323-000":{"lastUpdateTime":"2026-07-24T21:03:56.698960018Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1784926403000"
    test.appstudio.openshift.io/pr-status: merged
    test.appstudio.openshift.io/result-chains-git-commit: 825a087897bebb2dc16bbc8442126b669970810f
    test.appstudio.openshift.io/result-chains-git-url: https://github.com/stolostron/cluster-proxy-addon
    test.appstudio.openshift.io/result-image-digest: sha256:8f6edd2d936ab989dc56f655703a33b1e4ddefd0edf6f9e329a764e261fcbcbd
    test.appstudio.openshift.io/result-image-url: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210:825a087897bebb2dc16bbc8442126b669970810f
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-proxy-addon
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"BuildPLRInProgress","lastUpdateTime":"2026-07-24T21:03:56.698960018Z","details":"Integration
      test passed with warnings","startTime":"2026-07-24T21:02:58.759139589Z","completionTime":"2026-07-24T21:03:56.698960018Z","testPipelineRunName":"enterprise-contract-mce-210-crxnz"}]'
  creationTimestamp: "2026-07-24T21:02:58Z"
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: cluster-proxy-addon-mce-210-on-pushnkkzh
    appstudio.openshift.io/component: cluster-proxy-addon-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "89588753966"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-proxy-addon-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "660"
    pac.test.appstudio.openshift.io/repository: cluster-proxy-addon-ezmt
    pac.test.appstudio.openshift.io/sha: 825a087897bebb2dc16bbc8442126b669970810f
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-proxy-addon
    test.appstudio.openshift.io/pipelinerunfinishtime: "1784926972"
    test.appstudio.openshift.io/type: component
  name: release-mce-210-20260724-205323-000
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "10143070240"
  uid: 6b8d5540-0a55-48ba-9a4d-bb2795c1f01e
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:b31ce4bb22e349881a99cfb2948ceaa783bf10b586782e5c946ec90c9f066d95
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 487c5d2d8ec47a99e999f381b649eb0f9874e251
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:2d9443e42ea401cea10f381bf832a231e973405144ba0f198cbd6a4cf7a0057f
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: d21a2320df9d6194fa738aa9116c2a3860bce0c3
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:f3226df5fb3b946c5c986cd225b991debd51178308c57a7f1cbe5488d26e962e
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 29781d1ec45bf789d9900a667bd609422a40d0dd
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:ff266d4dc87cb9630b64603aeae91e0ec4cd2811d80c3b87e305027fc08a32e4
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e3e6deae5faf5089bee6a99ca137127d6ad23ae1
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:d2b04ea10d60c6c356cbdb4cbbeb3d06c27ae153c491024ee3962664c8178890
    name: multicloud-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4e9f7e2a000850d3c02d6fa640ca8c711ad298f0
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:9a2eb81cade166ab2ec130fc3fb435c97ba90b93cf1cdf64eb794d69447dfc97
    name: console-mce-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: b2cec7fea6545ed236cf2b973bde76ee90929fd7
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:a271dcbf3f51b0de08ed57d00d0565442aee6bdf4ea5195117d586eae1edc39a
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 487c5d2d8ec47a99e999f381b649eb0f9874e251
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:48dacea3a783a90735a024ccc9fc0a86eb31b8ea752ef28cbd8e008c66b3a3a0
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0608f32986a4bebaf9fa27918ac3ec86f388bcae
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:ab7b1e241c87e5a738a0b41974c0c34ef873a85deb15e748f1e2a6d01ae3bf14
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 41c2290e0712b04a4b0f3e705ef6908a02e0c961
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:576eab927a1f9aa24765ac2ac7dbc13a58eed09e7a1ac2a5136d61e9b7345132
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: aa851cbbab20caab15f9caa6e108ac54692a7e8d
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:840e11d9dc963f19b71ca3d0e26fdf1d2a36f9c9626187b9891dd2586880fea1
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c53f888c0c91b64c95d2abf85cd93ffe2295bbc8
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:e2ff8461fc1ac21963af1c23a003b094c577d93097dd093adfb54c6362230339
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 487c5d2d8ec47a99e999f381b649eb0f9874e251
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:257b0b4213cfd7fee0993752ac5f9a4ae9bdd954e5769d4b163b78a4d33bd53a
    name: hypershift-cli-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 36e967cafaf7cb978fd52263d173dede3f634362
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:3300ec7e39a5dbeefe7cfeb7eab54ce5399f8cdfa174809c20456db63c9f800d
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 92d2558ef5c062b686527e14bf96d1f690996e60
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:1767c7cac55206af53c026ffce8bf25cd1e8b566e9f8e2b5c138c71bc47da793
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 36e967cafaf7cb978fd52263d173dede3f634362
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:cc68a1d1ca6890ae69fc05e59d6fbd60128056c1a42cf7eb1d97fd0b3175e40b
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: a2f44a941cce11a527313e6a9e8585e9b8c0f20f
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:577b7b3bc52ff69df398e1d6be97aa4d1ef54f3e58c3a775c96910904142a005
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8da7a83c15ce2e732612edd5b26b8e0db3604089
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:d39d7a42edf4e564ee31af4a420d23b51f13f9f7d64e44dc7d6af2e009211026
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ab25ee3c80437ef4c8b55758f5ea1555efd6ce49
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-aws-mce-210@sha256:4a55e5d4b445a7e2e60b5f8f112e9e3c47fb5427a03cb19acd328cfdca5641b6
    name: cluster-api-provider-aws-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: stolostron/Dockerfile.stolostron
        revision: 5c8f63de889234c6dcaecdbeba895f321a472bb3
        url: https://github.com/stolostron/cluster-api-provider-aws
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:12fbafa4c43273dc6e9e5bace5dd3c3f27f0b08e967b0a57f45b37636454f30b
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 41c2290e0712b04a4b0f3e705ef6908a02e0c961
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:fe5e08fa27b38545c640592155cc222ba4fc0325db5ab1147d960af7ae0adf6b
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 487c5d2d8ec47a99e999f381b649eb0f9874e251
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:669811e67af838c8a03723279fa9bae2c320cde8d48968f4eca042dfa174dd6f
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 5e6c12ba2c9cd554b31af18ebb404ed79471460d
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:fb6daa36e8200ad01bd1dfcb464c15455923a062072a8b8c4e2defd6afc505b7
    name: kube-rbac-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: c64d306c8e72b5da944f744511cbda51cc200f3b
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:f89c3370c8a715a82b484ef3a15d8d965768ebdd642d835f18d78ec7930f7236
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ad8c18729bff1c9ef189767b82eb44d4091e8b04
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:449b88c4d11c8418c0a3a1de1fd05ee08cf438e85b5ef198a09657146e82be75
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c9e1cc7e5170dd33b931d9b5050047bbe8576008
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:1c5e2b922cad89dbfbb2e6fe9acfdffea756a62c3f7a5a6422090c9f9576812b
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 3a2a9adaead41459425e2e301ed73346edc0b0fa
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:7eddf1cc202e05ab7a4e9a77e9bd30986f264a37c306d97f06f467f42f5b2a32
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 70bd1833c8be6a1cca71c3d6b32f6e19dcf22fce
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:1671920ab1eb739a522ec46b16885f0d2ec606daaa08bba2de7b40cfe5630639
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 487c5d2d8ec47a99e999f381b649eb0f9874e251
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:8f6edd2d936ab989dc56f655703a33b1e4ddefd0edf6f9e329a764e261fcbcbd
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        revision: 825a087897bebb2dc16bbc8442126b669970810f
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:4cd09ed73d2df807385caf972c19b6a663d6b46348ec6a1a0ceb10dee13bdc3c
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 88f0e65a0950135dc8ed4846474a238185c0b477
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:20db2f80e1b70dab5f76c783046dbe65d3d0cafbae89cb5588bda29d3bd0f16e
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7eac70b5f0d1f8e8a97b8e6954270d31e4f04e60
        url: https://github.com/stolostron/backplane-must-gather
status:
  conditions:
  - lastTransitionTime: "2026-07-24T21:03:56Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2026-07-24T21:03:56Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2026-07-24T21:03:56Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
