apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/clusterclaims-controller?rev=1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
    build.appstudio.redhat.com/commit_sha: 1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49626707560"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-cqxifk
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/clusterclaims-controller-mce-29-on-push-qrqhp
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: clusterclaims-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "353"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/clusterclaims-controller
    pac.test.appstudio.openshift.io/repository: clusterclaims-controller-crbt
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
    pac.test.appstudio.openshift.io/sha-title: Update Konflux references (#353)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/clusterclaims-controller/commit/1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/clusterclaims-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: clusterclaims-controller
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-pppm5":{"lastUpdateTime":"2025-09-04T18:40:04.262095171Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1757010508"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.9
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/clusterclaims-controller
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2025-09-04T18:40:04.262095171Z","details":"Integration
      test passed","startTime":"2025-09-04T18:39:17.539604264Z","completionTime":"2025-09-04T18:40:04.262095171Z","testPipelineRunName":"enterprise-contract-mce-29-br2dx"}]'
  creationTimestamp: "2025-09-04T18:39:17Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: clusterclaims-controller-mce-29-on-push-qrqhp
    appstudio.openshift.io/component: clusterclaims-controller-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49626707560"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: clusterclaims-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "353"
    pac.test.appstudio.openshift.io/repository: clusterclaims-controller-crbt
    pac.test.appstudio.openshift.io/sha: 1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: clusterclaims-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1757011151"
    test.appstudio.openshift.io/pr-group-sha: 3f5ad436ec9e59c9f4c91e27298a4c40745f9b3ecde6e100e6d73cf94ffb6f
    test.appstudio.openshift.io/type: component
  name: release-mce-29-pppm5
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "4985603277"
  uid: 346de479-5cd4-4b51-97c8-7c9f6d557d64
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:afcebe18da2cc443eda7aad1c050183debedeecac26c333ff88302f4d33dc486
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c618f75439aa13f19607ef4a9c9e61af0124eaa4
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:caabbcc9de4ed289344bd451f682489a03a9831c4c3c35f1f7a9f158d9288bf4
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 717017d603724b9a70042a6d057ab0db379d76ee
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:0a94f735d7e683824e5cdbca94371db2b15b9de08ec1c59e706fa6f3390f4834
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 86764b3509e1b3329183ba879d3d6641ebe493f1
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:af3e9d6269ef8a578f69af5453e9a5bcba91b2cdf15531d4c6dbe61b0ff1bcc9
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 043ad9ce26197e52b0fe519279cc310459fd7d4e
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:1d0b4ce95990267bf2cc002bf156b0e71911ce5255948b80db2894b914be0f16
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:93cd0957d534e6218c3dde901291f09f0626e1f4f5292fb47390e47a2ef1dd80
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 2e99638ac0139ffe0aac8795eb2675a37e5a428e
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:f460d748fd17bf92b63f08460a5e06eeb04def79d4381650e4ab1cd529c1b5f9
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: edfa49d7396105759a6019f6ce16be00331c6440
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:6684290b745103fb378b067bac0e782350974511915495e15a6d10ebc2787756
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c584fc61feb9256543d706ce1dd8d17a7858b3ae
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:286bc0ef666f03b5fa253e3a3257246cbd4da4c51153bd14a1dba7288192f1ce
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f72f75b656967073d68e91500511a8ef991c2d5d
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:3332ec944ea12673a1e7c08173c5b99f7885c90ae15e196157dcaf09f0ba74bd
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 4ff22262ed476d4cae5fe8b1c73b1bd7cdb81cd9
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:573f18b4df2d843a1d9c9d84648dbd47d40802de46c4b5a5b71b70602ea88920
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:5e9547c326df058bf9dbf9e716321c0abc3f75a63d934175283356ea3facdb32
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 06a3783c03f53edf9f9601ee9b0c3141db622b7c
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:3b2cbdcea0c8416523012785f007f2a463db78bb3cef33dd7cb93d8dd1f558d4
    name: clusterclaims-controller-mce-29
    source:
      git:
        revision: 1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:3aac65bfc332223c49c787d966948790aa8c2f42e20b8a1357c85b59e30b088b
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 501d43cb4983422fbee372af47ef134f3a9f5638
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:4a73be68349cc6286d06236d128d3d61df8e7f14ca172d24682c914fc89ef7db
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d66e3b2ac0236fcd372d3d8905dc9b897b9677a5
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:c6392b18d6868285b1bb364942eb817d55b5aadcb93001f0a94d9ceaaec6a03d
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 2e99638ac0139ffe0aac8795eb2675a37e5a428e
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:af4fbee4b449bcba828b1f89f9174282afdc4d17a37fa8e83cbac96c38f2c34b
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: d58f3aaa7f758a4247a74a9d1438129da615359d
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:0f7e8eba2079619732b9370b009dd97f9972b3caf4a14e59195796a5a70a4821
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 41b971dd103fb052ce02cf4350585fc6400aa3ef
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:2ea5c6303fb4013914b50b925bffc4fa416fc37a4b2f443e673278289cecea28
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 62c67263744c603664ac38f076b99575978a6086
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:8ff8497d38e7142b7f564db8b5aed85aea340772d585336714190330b5906e3f
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 282bb4fcdda5b1918f7dde577bd59773d8090bab
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:0753ef817861975779bc99fd3aaefc0ea66be3b6ee051ea43b88e073eee8e354
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: f491c6e9c9770bdf18abfd0e0803a27ae6358f21
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:3942e730f120379ab3a1fe2aa63b83c3235b4ca966f5abbe2bf7297b997eac76
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 428b6bdf19cf50429db02833c02cbcd3e4d6e66a
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:8076db8ccd5578cb5aba2d66f53790563d3f42b93a6cfd14c7094d3a25707982
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 714c008c19e6de1ba1a47b03dda6bf89fc9bd333
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:d55c492358c276cfc07f4ba6ed068d78c852e9b0cfd33b97b59c0d6e0854eeec
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b26921fb30b146a778dcc73135db785077bf0f89
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:e466374e4e2e4861861afe48d33d511ff7364f83e88225aa11f7dce3fe6662a5
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cb753172342f4dfdd7e022b24ffbda99c4aa41ed
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:91c02475a47b312f2699770280438944b93b7337ea3127064c443365501f0486
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:23c2e20ee8a9e16ac71dde57ac16655fce65001719941b3a93ea1dac8502c15d
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 486a2e3997179a38badcb7f204a486b53f9a77c8
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:a958149d782fc98ade73ca13b7ce8e696f241ed6b1e99461b131771f32b8dc7c
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:dddea71d20dff988a20f84ca9b5277f23ff52510a97cfc2be5757f1a2ce45a38
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: edfa49d7396105759a6019f6ce16be00331c6440
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:11c04babd574a5a9b0df8b648049e7513e3464b9eb7211d07f507a139f2d7427
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-09-04T18:39:17Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-04T18:40:04Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-04T18:40:04Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-04T18:40:04Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
