apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/hive?rev=b061ef0a98a594fa2099647cf228495566317c5f
    build.appstudio.redhat.com/commit_sha: b061ef0a98a594fa2099647cf228495566317c5f
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "58485136766"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-xwqife
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/hive-mce-28-on-push-qkjkq
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "master" && !files.all.all(x, x.matches('^docs/|\\.md$|^(?:.*/)?(?:\\.gitignore|OWNERS|PROJECT|LICENSE)$'))
    pac.test.appstudio.openshift.io/original-prname: hive-mce-28-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/hive
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: b061ef0a98a594fa2099647cf228495566317c5f
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #2820 from suhanime/dnf_ophub'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/hive/commit/b061ef0a98a594fa2099647cf228495566317c5f
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hive
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2025-12-18T23:40:50Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-28-release-mce-28-vhjhh":{"lastUpdateTime":"2025-12-18T23:41:28.252888576Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1766098828"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/hive
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-28","status":"TestPassed","lastUpdateTime":"2025-12-18T23:41:28.252888576Z","details":"Integration
      test passed","startTime":"2025-12-18T23:40:50.724812312Z","completionTime":"2025-12-18T23:41:28.252888576Z","testPipelineRunName":"enterprise-contract-mce-28-8q465"}]'
  creationTimestamp: "2025-12-18T23:40:50Z"
  generateName: release-mce-28-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/build-pipelinerun: hive-mce-28-on-push-qkjkq
    appstudio.openshift.io/component: hive-mce-28
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "58485136766"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: hive-mce-28-on-push
    pac.test.appstudio.openshift.io/repository: hive-master
    pac.test.appstudio.openshift.io/sha: b061ef0a98a594fa2099647cf228495566317c5f
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: hive
    test.appstudio.openshift.io/pipelinerunfinishtime: "1766101242"
    test.appstudio.openshift.io/type: component
  name: release-mce-28-vhjhh
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-28
    uid: 1bb16185-3532-42f1-8819-a53d8cfd38dc
  resourceVersion: "6364755514"
  uid: a3c23c74-7ca2-41bc-a429-c5b44c02eed9
spec:
  application: release-mce-28
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-28@sha256:0aa7d60fd36def8c6534cba040711c66f7c9f6830c5f2a4d2c8dc0592ed596e1
    name: cluster-api-provider-agent-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 75cecb1cf1576855c3fe9e964254a2625e7ca07a
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-28@sha256:1c045f8b93e825d859d00957c883552237d98b77976cc01adbdfe54bee4c0274
    name: cluster-image-set-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f3fbb126db3a83783b20e9bba4312c5871ac1b33
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-28@sha256:289c55000857cc51add96bf1cbd8c8e94fd2052c04b2fe0a5978984230474b37
    name: console-mce-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 6df7c7320ed9b0b7dcb2faa960f34141b5ffd7ee
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-28@sha256:f2f6d1da89803efcd6fa604299e9c130a3925c786076ebded07dc7f2d2316da6
    name: discovery-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 740753a9cf15d15857f22089f82627bf5f3e4088
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-28@sha256:fee5f42ae1496fa13fd75c19ae3e723ca615fe33251bb0593e12ddeff6ed958c
    name: hive-mce-28
    source:
      git:
        revision: b061ef0a98a594fa2099647cf228495566317c5f
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-28@sha256:5e86e48a3c25a74d6938d371f04e293751f674a92c47b2569edbf579810df24d
    name: hypershift-cli-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 606691efff4a4e58b325c83bb27d93554f09aeb5
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-28@sha256:91f0e0e3caac962b4bdb04a601ac0a55a8e095d8d05bf7a9b962c37abfb1d539
    name: provider-credential-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a703b336222873a76746e10fd7ea2aa6314396e8
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-28@sha256:52c1da15bdce66e53efbf04e26bee45012cf110c2308fb5e251af9c04ba21575
    name: registration-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 53508a16286e180c892765b61665db1efad291b6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-28@sha256:8d6e59b6855b2ccb85555838657c48b137078597b8d3d7e568f2aad439a95017
    name: backplane-must-gather-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0849c35a22dfac09f98b1214eb9bd8c5decf58b7
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-28@sha256:0393fa078a895d7498354b1a373741ea253099df7832e0af0b15ff0023e070ec
    name: cluster-proxy-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 85a828b91eda63beb30ba2104c21718f5de74305
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-28@sha256:e6c446dbc56007a7be95471e3e7b22de8df6cd1ba6352843a802e718f4d88420
    name: clusterclaims-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 666cde55e31ff93358822df0338c78e95b680fbc
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-28@sha256:5d04cf5c17f4d6c5cb25313b384cb5537b0c670832a554866ea0cdee2eadb759
    name: clusterlifecycle-state-metrics-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7c5d1b94fed1c79d4c3179d0be7bddd1e9c08892
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-28@sha256:31caaac2707372880f9cc65daa2888ceb3bab23fbe9a674a5b850223c4bdea0c
    name: hypershift-addon-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fa27be884c3b9e0ed9fe5d0640964e122a6a1b46
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-28@sha256:1e82ad63293013dd03dc80642bea46c0eeff249ce8f0b3d7ce13ecaede0a11d7
    name: hypershift-release-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 606691efff4a4e58b325c83bb27d93554f09aeb5
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-28@sha256:1c1ac599b0e7c507cc607b3b6a5bca6da632858ebc062b91b3c9e95f5c0032fd
    name: managed-serviceaccount-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1a753bb5c9e079fc67bb0915cf045bc290225ffc
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-28@sha256:0dca871049f1b9c88f88f317e9a807c693d2b33b51672ea92b46dbee35c43b72
    name: registration-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 53508a16286e180c892765b61665db1efad291b6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-28@sha256:f28343a728f7a0f5e3eb4c7e45e28673cdd9a1e754321e7c07ef3456772ab9f1
    name: addon-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 53508a16286e180c892765b61665db1efad291b6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-28@sha256:e836ae9c00be3179dcccc77962fdacdc36f93da4c5298ecb221a216ee7858a51
    name: cluster-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 9d97095594447e063aa93333cf6f03e427a351fe
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-28@sha256:acf71d4bd1bf890ba7e9d07005e79bfabd57adba68ad1c446c7ecc609a6f518b
    name: kube-rbac-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: e5fc3a780e46b81a30fb2b60df317804cfa9d485
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-28@sha256:1c34a97f61ae7f19fce181e2040199a2da367f29ccd353bed50591c258806f6b
    name: placement-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 53508a16286e180c892765b61665db1efad291b6
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-28@sha256:6067120264dd307010858964b8a190464104e7b3ae797a3d40cfa197125cc09c
    name: backplane-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2cc962561037ab99652ebc34cae544b88ec6b699
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-28@sha256:4c9377c200bdb9d17ae7d8eabe95f89f6b0fbdbad92f7d36a6c8d1164367b309
    name: cluster-api-provider-kubevirt-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d2f49554325951653b7c0f0e11cbad167f1682d8
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28@sha256:2edb4a8798db6c9c99a3f394fbb22c38303c79497da894c5259090781475e137
    name: cluster-curator-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 77cd8de47003c4e94b88560955b4d5e7010179c7
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-28@sha256:66a0f66c6643e0039f4d32cf013ab997be4ec1387095e71545883d9879075125
    name: image-based-install-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 10f6b67235b7185e6f579c5f299a4a8e1a736689
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-28@sha256:8404e1f8ba2ddebc588973038e0f22fedf60c0478d9852e198370f0e3c539510
    name: managedcluster-import-controller-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 9dd4d3544d08e41a4cdb071e735ea619a44a1d91
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-28@sha256:c1597df3ff13de4401cc04c5cf9cc044eee13ad74cd4317574ee357d0f258bc3
    name: multicloud-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ce5c0ff0870a80d7c4c77df030af0651c82a18c3
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-28@sha256:0d54f9e886dca7898fcfd83a18fd1883e76e95dc828bb5f57f32a6de11fdbaee
    name: work-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 53508a16286e180c892765b61665db1efad291b6
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-12-18T23:41:28Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-12-18T23:41:28Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-12-18T23:41:28Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
