apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/cluster-api-provider-agent?rev=6419a4441d1b690bca2e166faeb4cb891bc6684d
    build.appstudio.redhat.com/commit_sha: 6419a4441d1b690bca2e166faeb4cb891bc6684d
    build.appstudio.redhat.com/target_branch: release-ocm-2.13
    pac.test.appstudio.openshift.io/branch: release-ocm-2.13
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "57692925757"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-sfvskk
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-api-provider-agent-mce-28-on-push-bwbmw
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "release-ocm-2.13"
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-agent-mce-28-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/cluster-api-provider-agent
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-agent-mce-29
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: CrystalChun
    pac.test.appstudio.openshift.io/sha: 6419a4441d1b690bca2e166faeb4cb891bc6684d
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #790 from CrystalChun/add-ci-op-file-2.13'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/cluster-api-provider-agent/commit/6419a4441d1b690bca2e166faeb4cb891bc6684d
    pac.test.appstudio.openshift.io/source-branch: refs/heads/release-ocm-2.13
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/cluster-api-provider-agent
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-agent
    test.appstudio.openshift.io/added-to-global-candidate-list: '{"result":true,"reason":"Success","lastupdatedtime":"2025-12-10T17:13:53Z"}'
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-28-release-mce-28-226mf":{"lastUpdateTime":"2025-12-10T17:14:32.887199556Z"}}}'
    test.appstudio.openshift.io/integration-workflow: push
    test.appstudio.openshift.io/pipelinerunstarttime: "1765386154"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/cluster-api-provider-agent
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-28","status":"TestPassed","lastUpdateTime":"2025-12-10T17:14:32.887199556Z","details":"Integration
      test passed","startTime":"2025-12-10T17:13:53.237574718Z","completionTime":"2025-12-10T17:14:32.887199556Z","testPipelineRunName":"enterprise-contract-mce-28-2qs92"}]'
  creationTimestamp: "2025-12-10T17:13:53Z"
  generateName: release-mce-28-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/build-pipelinerun: cluster-api-provider-agent-mce-28-on-push-bwbmw
    appstudio.openshift.io/component: cluster-api-provider-agent-mce-28
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "57692925757"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-agent-mce-28-on-push
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-agent-mce-29
    pac.test.appstudio.openshift.io/sha: 6419a4441d1b690bca2e166faeb4cb891bc6684d
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-agent
    test.appstudio.openshift.io/pipelinerunfinishtime: "1765386825"
    test.appstudio.openshift.io/type: component
  name: release-mce-28-226mf
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-28
    uid: 1bb16185-3532-42f1-8819-a53d8cfd38dc
  resourceVersion: "6235004240"
  uid: ce3a21e6-22e8-4f78-a697-a9e9dc1128bb
spec:
  application: release-mce-28
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28@sha256:36758b73d4141e85140c0fee1f2b2f7112e45b8da124edbe337c54590b5f2fa1
    name: cluster-curator-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 45d9624a622123660b81e10e6436b5a1d7742cd3
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-28@sha256:af7709df27a36fcf6ef1f42edd4d0cbb5a822622a02e738a7351dd112e4a12ec
    name: hive-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: e597cf4d18f7b3cd2a65add3ca42b4ce87976277
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-28@sha256:5080e0293939d035a5548e99f1b6814d5b852d00de9cac4549fddc6600252db9
    name: hypershift-addon-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a0dc6cbf5d58de99a8b6ab1babd848f33fb8a0f5
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-28@sha256:c45552d08e3e2ef1782adf3f629c7fb52fb6a8f7547915943f5de04b8eb8a096
    name: managed-serviceaccount-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f6f650cba5c5fd71afd110fe9c8b9e5603686fa8
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-28@sha256:6e76978e4edf688b36672b386c2616cc9d38b77748c614ec861473d578d2cecd
    name: multicloud-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2b55d9a319234ac08884257fab27dd2fe84d757f
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-28@sha256:b27885c8cbed341e7689ad5031087d09cada7e4357b504f465754cb0024e372a
    name: work-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-28@sha256:06b26d7fb96d1f01950bde29d3b000066ea856fb92c5179658e63559330ef730
    name: cluster-api-provider-agent-mce-28
    source:
      git:
        revision: 6419a4441d1b690bca2e166faeb4cb891bc6684d
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-28@sha256:4a88be8c253818ff1082dd1a166425ef1f6c954cc7406d4643d39eea7af6b9d0
    name: clusterclaims-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d1b7f9bcfd9b5416f7fe8ac2fadf27beadfbdc7a
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-28@sha256:4addfa03ad6ae48c90f0776b0ce1fbb5fe3243ade3cbd268fcf328334f113af1
    name: console-mce-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: a9723c5d94b2ffe307831bd7720aaca241f18c8a
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-28@sha256:c2ba4aa7a9a0cf0407186e97347df95074c8c9c6e8d6a822f2ca9ee7c8d945a3
    name: hypershift-release-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 9d91c812cffea9e985e8db57abcd445c951b5532
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-28@sha256:7dff28b399b679183b9c658284deeb37f32dbf2506846fed389e26fc880f1918
    name: managedcluster-import-controller-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 85d3d29d7dfc96e14fdf366505e9451190ffa0a8
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-28@sha256:6e86332f1d9c0654ccface2fa032eb0e9121e3bff7bce884144e707fb3491472
    name: provider-credential-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bda03fbcfa85a9f47e54ec377237cf0227b9eac0
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-28@sha256:acc002c8069a1ed03d369cb0d8857fe20d758543ce90a1a2f4f0d0a577354b01
    name: registration-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-28@sha256:f0d96ad8482247f93b550875e6e1db1b5052913a2fc71ddba1326f58548fb45e
    name: backplane-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7e4ca6683d93e8280061a0fdaef493fb5534660d
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-28@sha256:8a44e4e52c6a34c8a9271319cf4f104649e5981ba87ee99d09f23b16f6b51151
    name: cluster-image-set-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dfa26fcbd993ce9417cc15ca7729045341b6676f
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-28@sha256:84d911209ec0745bda7d9baab79aa2a175506fc8722f4a385d2e743bf83b05d9
    name: cluster-proxy-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 85a828b91eda63beb30ba2104c21718f5de74305
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-28@sha256:6c7cc7714142bdcfa6269e0f5819cabbeda0294aecf1e665f60f7097e9db464b
    name: cluster-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 974775787c8f27de637f454f5bc51446ac75370b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-28@sha256:88d3878748d693e784f428cb479d82f481977923070220f949b905dbf90e07b9
    name: discovery-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 740753a9cf15d15857f22089f82627bf5f3e4088
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-28@sha256:e157678a4ac9ba7cbcb2eb9ce70f19f796c1781bce6ef779118e28b8e585c80a
    name: hypershift-cli-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 9d91c812cffea9e985e8db57abcd445c951b5532
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-28@sha256:acf71d4bd1bf890ba7e9d07005e79bfabd57adba68ad1c446c7ecc609a6f518b
    name: kube-rbac-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: e5fc3a780e46b81a30fb2b60df317804cfa9d485
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-28@sha256:47ad13f3cf0719362e84bf4632951ea0f3078f6f86db40e215181948d4043d8c
    name: placement-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-28@sha256:800c2e017733f58552efff314e87044f2d6a3e24428cef028d1a2f13fbd186a9
    name: addon-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-28@sha256:8d6e59b6855b2ccb85555838657c48b137078597b8d3d7e568f2aad439a95017
    name: backplane-must-gather-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0849c35a22dfac09f98b1214eb9bd8c5decf58b7
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-28@sha256:5d04cf5c17f4d6c5cb25313b384cb5537b0c670832a554866ea0cdee2eadb759
    name: clusterlifecycle-state-metrics-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7c5d1b94fed1c79d4c3179d0be7bddd1e9c08892
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-28@sha256:35c3a0feda61fcffaaf3d6633aae847567f0c5e92a1553af63036338ac2075bb
    name: image-based-install-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: ed3b5d979a6320904b8f8e27cd8956f0fac8ef87
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-28@sha256:884132e13f140328519bc22cbbf71f44f5b89e25587476caff86c9df2c62c8fe
    name: registration-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-28@sha256:4c9377c200bdb9d17ae7d8eabe95f89f6b0fbdbad92f7d36a6c8d1164367b309
    name: cluster-api-provider-kubevirt-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d2f49554325951653b7c0f0e11cbad167f1682d8
        url: https://github.com/openshift/cluster-api-provider-kubevirt
status:
  conditions:
  - lastTransitionTime: "2025-12-10T17:14:36Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-12-10T17:14:36Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-12-10T17:14:36Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
