apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/managedcluster-import-controller?rev=4f6135994976f401de1e266c858ef5d4c1043637
    build.appstudio.redhat.com/commit_sha: 4f6135994976f401de1e266c858ef5d4c1043637
    build.appstudio.redhat.com/target_branch: main
    pac.test.appstudio.openshift.io/branch: main
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "41796063852"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-tfufth
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/managedcluster-import-controller-addon-mce-29-on-push-vzppt
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "main"
    pac.test.appstudio.openshift.io/original-prname: managedcluster-import-controller-addon-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/managedcluster-import-controller
    pac.test.appstudio.openshift.io/repository: managedcluster-import-controller
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 4f6135994976f401de1e266c858ef5d4c1043637
    pac.test.appstudio.openshift.io/sha-title: remove the auto-import retry limit
      (#649)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/managedcluster-import-controller/commit/4f6135994976f401de1e266c858ef5d4c1043637
    pac.test.appstudio.openshift.io/source-branch: refs/heads/main
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/managedcluster-import-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: managedcluster-import-controller
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"mce-29-enterprise-contract-registry-standard-release-mce-29-gz4rf":{"lastUpdateTime":"2025-05-07T12:27:53.416186931Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1746620517"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/managedcluster-import-controller
    test.appstudio.openshift.io/status: '[{"scenario":"mce-29-enterprise-contract-registry-standard","status":"TestPassed","lastUpdateTime":"2025-05-07T12:27:53.416186931Z","details":"Integration
      test passed","startTime":"2025-05-07T12:26:43.164945793Z","completionTime":"2025-05-07T12:27:53.416186931Z","testPipelineRunName":"mce-29-enterprise-contract-registry-standard-vzvrx"}]'
  creationTimestamp: "2025-05-07T12:26:43Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: managedcluster-import-controller-addon-mce-29-on-push-vzppt
    appstudio.openshift.io/component: managedcluster-import-controller-addon-mce-29
    pac.test.appstudio.openshift.io/check-run-id: "41796063852"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: managedcluster-import-controller-addon-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: managedcluster-import-controller
    pac.test.appstudio.openshift.io/sha: 4f6135994976f401de1e266c858ef5d4c1043637
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: managedcluster-import-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1746620796"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-gz4rf
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "3815514722"
  uid: db5befc7-b66b-4f4b-a495-7741e64b94a8
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:0d2ee30b3e338845f2f8d3373687c10ac0e1e80703e8bda7c7bf2f695a88f51e
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: c50bf4b92aed1b38ecba087b35916721b40ba47a
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:8f4ae3aef27bc597920d6936a6c1ae4fe793b46fb830d6ca2ecd3a48da287d2d
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        revision: 4f6135994976f401de1e266c858ef5d4c1043637
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:6519596ed0a3b4c58ecea89167d054b73c732ff958cc45c2c706189696352fc3
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b2a6244fcb6501825e5d958353ee34277370490e
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:bbf5628a973362ad6a434885442b28e5787604741bfaf89c529ef4b165272058
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7e7808fc9c4d7653ae38402a1971cc0a76b33a5b
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:ced3cf32ba184d183c29afdc7ad2e61d4466b14e4165276b0e9a928a5e2442ea
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: ebf637f1b75a7a171373665d8bdbe54e69355025
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:66d5fd4c82c0717756faef1653bb3ddd0d8d79913f2187ae17650637d4fa0ce1
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7f76a34ad68aead56ca9748ee16d3343a937fb42
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:6848d0cc41230727ff10b0c993dbf2afd4bb904cb68feaa8225bdfe92de23095
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: c50bf4b92aed1b38ecba087b35916721b40ba47a
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:7b1a14656bee601aae97abad0b8507354274793e31d7cca3f28641cb8786ddeb
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 6b8e5f822c9bb46a5fef256fa056a9b74b210610
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:88f453e73d49b46557baaadc4d21989c3125f1ac901dcd7e1eaa7df944c989ba
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: c9c2fc60801e77bbd4092e92c62a9a6f7ea7203c
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:bc5af98f8bce2eb7b6ad28ec11b528b1bb9185d12d6c7391cf2da0bd97b30be1
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: cd90dd57a744f0ed615446899a0790a6498902f9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:939b72edfc5662223248b318bd4fc8739116f40c4697de8d6d20e5dbdfbe5e63
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c429eac5fcd152111cd80ed531ea8973cd81a966
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:855ed837925f1176ea1746713b10b371a7b4060191b920d742f0ab6e51d4ed41
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0bd9b990e034e77aa8d6ce1e0ef952f7fe526b40
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:5aaf06ca19aa1741f919aeed61089947e0524e8c5f9398367f09dd352cf62327
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 857ab23b5f8c27657ab6bb962c2b1b6df8480d20
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:aa3210d5909d7d8e3329f4f91fb7235d0b9a06154652a31bcb87b0397b963ced
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dde8add6875e7e9a9fe9eeebab2e9ea7accde88c
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:a9eb3329adfd3f3f153a87c220619c694feac4b9dfa4aabae59d78fd715a4e94
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 8790a012d8d01424f8826a27c5db088595ad070c
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:1b49b5546c5e5e0544d5b64f991c4d458687225b170ed4c0d6174c1e94c99ced
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: cd90dd57a744f0ed615446899a0790a6498902f9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:17c676b555f92e9cf02879e8a3f9179c5e5dd4b93969f33887c633565a8f7b9a
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: cd90dd57a744f0ed615446899a0790a6498902f9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:e3ff1055c0c7c9d13b4bf6d84c4c4f029a1b3ddc39480f03f043f5f3e87f6dc3
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c0cf0393f69862e7f37d490fadc09b1a5ea977d4
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:4881249d3d120566c2bcab995fbdfb9da4393d846e97a39497f50e08a600c6d3
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: dd5f25531287cd9368aae435283b12be395b980a
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:55bc86752212e6d8e8e4cae0b967267a8ea78b79ffad0933e589cb13ff61376d
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a61680a98f77183d225649e8cdf7e93e7333501d
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:a6e3ab9d23f14736b52409197fdfabd67b6a700d50994121bcb45594ecb57cb0
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 01124adb2715bb91df75c621df9b4cdbeb40e5a8
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:cb6dfa92a0987b6123e7aad29d324953b5c76d70460752b286f7f53af3d8e2d8
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 76a2c06bdf258e9780967e47fb1cc1322e4dfaa4
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:4c2557583e50d693347d989b588f3fec72855a26d520c835fc9e85b9307d7563
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e525b1a46cd543aab3365060a010bd911babcd05
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:96647898932120ef02556b0b644cbe6b440fa3408e7012c0a75f9656a1cae26c
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 7bbf21e955bc71e0518c5499cae176cf8bc8a4af
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:646f1128553206dccbadeb5c2ea43f2a693e11d7fa65e8f01c76c182578ad765
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: cd90dd57a744f0ed615446899a0790a6498902f9
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:63b50e792e55dd986a3f51ba52ad566b2bf6bec1167c1240fcb0bdd2b061970a
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2cacd5f052b1be2343a110f80741064432100f4f
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:a6a0ef07a2e7701b6ce93b94a56130baf72ab804722de5f55908d67c8571c4e1
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: cd90dd57a744f0ed615446899a0790a6498902f9
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-05-07T12:26:43Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-05-07T12:27:53Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-05-07T12:27:53Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-05-07T12:27:53Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
