apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/cluster-api-provider-agent?rev=71f6f26658f067bd6bdec5d599a12899999d65c4
    build.appstudio.redhat.com/commit_sha: 71f6f26658f067bd6bdec5d599a12899999d65c4
    build.appstudio.redhat.com/target_branch: master
    pac.test.appstudio.openshift.io/branch: master
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "41108038753"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-krfgkj
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35333059"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-api-provider-agent-mce-29-on-push-9kgsp
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "master"
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-agent-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift/cluster-api-provider-agent
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-agent-mce-29
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 71f6f26658f067bd6bdec5d599a12899999d65c4
    pac.test.appstudio.openshift.io/sha-title: Update registry.access.redhat.com/ubi9/go-toolset
      Docker tag to v9.5-1745328278 (#211)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift/cluster-api-provider-agent/commit/71f6f26658f067bd6bdec5d599a12899999d65c4
    pac.test.appstudio.openshift.io/source-branch: refs/heads/master
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/cluster-api-provider-agent
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-agent
    test.appstudio.openshift.io/pipelinerunstarttime: "1745517452"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift/cluster-api-provider-agent
  creationTimestamp: "2025-04-24T18:07:18Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: cluster-api-provider-agent-mce-29-on-push-9kgsp
    appstudio.openshift.io/component: cluster-api-provider-agent-mce-29
    pac.test.appstudio.openshift.io/check-run-id: "41108038753"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-agent-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-agent-mce-29
    pac.test.appstudio.openshift.io/sha: 71f6f26658f067bd6bdec5d599a12899999d65c4
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-agent
    test.appstudio.openshift.io/pipelinerunfinishtime: "1745518022"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-j4rp2
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "3705428366"
  uid: 09a2e775-cb24-4d16-b085-ad12a21f3cb7
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:74b4a21cbb975134961aca7685074b0fc70de5fba183759b41ea18c11ee7f660
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 435604b567fb688bb04142f1f3de78ff3e699aae
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:828abb0124a0e873ebeb21d482e12490bcbe3210a902defa4ede6498ac614119
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 95326c6fcd0c4e519f2a60787834117d559ccb42
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:405f0ead18f5deaeb15cd26dc2612ad0f3ccaf6c457a8550f803949afccbcec2
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3ad9b9f8e3306a0c5835beb44ee52950fab2658c
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:d4bd3dc74578da3c151a912e548c81a0a3fe5709f664142941d4b5db2b3f39cf
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 3e92dffa499c84aee04c0ffb1fe83f3d24b76979
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:ca718ff843b2817cfda55deba55ba9e3db9ae88ab4ef9fc43f2353a89be96afa
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f621572a90022969cbe9e2052e734e60ae903258
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:5aaf06ca19aa1741f919aeed61089947e0524e8c5f9398367f09dd352cf62327
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 857ab23b5f8c27657ab6bb962c2b1b6df8480d20
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:116bb0edb62549da68b0dead5f881704e3d04e9ec773e4440ecced8013630ab2
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a3822f4c12d756cb31d5e3dd9116d1d4301f1b25
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:59737bff028b674d515900dbe0d1e58e0142b847eda4acd39f0a18df71118299
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 9631cc0d93c5f427331caa7e0484366f909ed8d6
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:2acc472de4b7f7338ea7650b5d9670b319821d2a0811ec238ff16fe3108351bc
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 959ed25d9067b70cacb0fd764c7dcdfa6a2da0fe
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:8b3394917b0b32642ed21402522862d53954a4027931347f75204e693aec1965
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 959ed25d9067b70cacb0fd764c7dcdfa6a2da0fe
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:63b50e792e55dd986a3f51ba52ad566b2bf6bec1167c1240fcb0bdd2b061970a
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2cacd5f052b1be2343a110f80741064432100f4f
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:84608b203ee09b295a209c41eb735f8fb501a54bbc61d2bf60a6c487f4ed7bba
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9f3c86ad098fa07e45572a3d1ac4b3734e3d277a
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:a1ee6b464c602f097f6e3397dacd2ae875d9d42abdfe0bb50015eda3ee83df23
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 7dfcb0a882db0016253105ab65ec269abce11f88
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:9aca2c0f5bc0697ddc67419436ed67212586f13e3f321945f9c82ca629ca6178
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 97697f8dd20bb567949bce21deae4e79c7d0d7c1
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:4ba229ea91dafa59496e4119d980c850f1181904e5d510281e0cbceb39f5efb5
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 959ed25d9067b70cacb0fd764c7dcdfa6a2da0fe
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:04f74381332f0158968743980b5b46c9f3578a734cbc708900a251369bff702e
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0b4ff1ef2a5695608c236e657e56fb4eb5aa7bb5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:40ec4ed30927ae6aa50d5198d6843aa9ddffed9d7c374e59b5f35b60b050d7eb
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: c169984217e9fb9b5dddc8bd6ca8ebda7005ba8e
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:88f453e73d49b46557baaadc4d21989c3125f1ac901dcd7e1eaa7df944c989ba
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: c9c2fc60801e77bbd4092e92c62a9a6f7ea7203c
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:425780a754c8d15886232441bd56ac98a19f1a445ed72a48fc9822d14b3cfc4c
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2ce270d94fd67a57b10d54bcb76a51da419de160
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:637b077ceeab5c6693283a7f8a6173286d06a9aaa1c74e0a94695d3ae9263c12
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d8efb9c7d910fec7c42cf2fd0adf7183563a4bcf
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:0998290515a3e9d7a53ac40d41852e01293779235d482a52900a577e44cb4ea2
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1374416bbc2e45d2989350e9552805e221f640d6
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:eaef3607f11fc75f95ad4e3327bbb48d3993e4e25a05d187ee72da3bfcefbd13
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 959ed25d9067b70cacb0fd764c7dcdfa6a2da0fe
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:fe545e55e5dc8fd27ab80f4de3b55805e8dc2b6ba18d2d4514dd1787b5ab0ecb
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        revision: 71f6f26658f067bd6bdec5d599a12899999d65c4
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:774ca20ea4209854311d16f81704a0d62b52dd8121bdb7a5035b4b982ee76cb2
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 8ccdc69f8da10f407d3492f426f82cc2434d7259
        url: https://github.com/stolostron/cluster-proxy-addon
status:
  conditions:
  - lastTransitionTime: "2025-04-24T18:07:19Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-04-24T18:07:19Z"
    message: No required IntegrationTestScenarios found, skipped testing
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-04-24T18:07:19Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
