apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted?rev=b6ba4e8516de658dd7ad398c24f4347c9a7de5f0
    build.appstudio.redhat.com/commit_sha: b6ba4e8516de658dd7ad398c24f4347c9a7de5f0
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "45991234519"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: retest-comment
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-vdgfap
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "37784342"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-api-provider-openshift-assisted-control-plane-mce-zbf7c
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: cluster-api-provider-openshift-assisted-control-plane-mce-29-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    pac.test.appstudio.openshift.io/sender: pastequo
    pac.test.appstudio.openshift.io/sha: b6ba4e8516de658dd7ad398c24f4347c9a7de5f0
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #349 from openshift-assisted/konflux/references/backplane-2.9'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted/commit/b6ba4e8516de658dd7ad398c24f4347c9a7de5f0
    pac.test.appstudio.openshift.io/source-branch: backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift-assisted
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-openshift-assisted
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"mce-29-enterprise-contract-registry-standard-release-mce-29-qd947":{"lastUpdateTime":"2025-07-15T08:37:11.532251105Z"},"mce-enterprise-contract-release-mce-29-qd947":{"lastUpdateTime":"2025-07-15T08:37:11.426646125Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1752567893"
    test.appstudio.openshift.io/source-repo-url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
    test.appstudio.openshift.io/status: '[{"scenario":"mce-29-enterprise-contract-registry-standard","status":"TestPassed","lastUpdateTime":"2025-07-15T08:37:11.532251105Z","details":"Integration
      test passed","startTime":"2025-07-15T08:36:10.160872948Z","completionTime":"2025-07-15T08:37:11.532251105Z","testPipelineRunName":"mce-29-enterprise-contract-registry-standard-x98dz"},{"scenario":"mce-enterprise-contract","status":"TestPassed","lastUpdateTime":"2025-07-15T08:37:11.426646125Z","details":"Integration
      test passed","startTime":"2025-07-15T08:36:10.138033234Z","completionTime":"2025-07-15T08:37:11.426646125Z","testPipelineRunName":"mce-enterprise-contract-rx5gh"}]'
  creationTimestamp: "2025-07-15T08:36:10Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: cluster-api-provider-openshift-assisted-control-plane-mce-zbf7c
    appstudio.openshift.io/component: cluster-api-provider-openshift-assisted-control-plane-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "45991234519"
    pac.test.appstudio.openshift.io/event-type: retest-comment
    pac.test.appstudio.openshift.io/original-prname: r-api-provider-openshift-assisted-control-plane-mce-29-on-push
    pac.test.appstudio.openshift.io/repository: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    pac.test.appstudio.openshift.io/sha: b6ba4e8516de658dd7ad398c24f4347c9a7de5f0
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: openshift-assisted
    pac.test.appstudio.openshift.io/url-repository: cluster-api-provider-openshift-assisted
    test.appstudio.openshift.io/pipelinerunfinishtime: "1752568563"
    test.appstudio.openshift.io/type: component
  name: release-mce-29-qd947
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "4466812231"
  uid: cde68216-b052-4c96-b7b9-afc8472bbb0d
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:7f1f70813e6d753b4acb04c7e9d7acb0047ad91f8a9a10e0fe2fff6c4411c8b4
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 6244b8021a455c902dea7a6823b437416c707e15
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:f8c3898e29f8c0a20c3be92bc4ee5a9443b9fc8218db95ba541fe3e57a89c40d
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: da32b47345c6a1ce4fa2981390292bdbe79334e8
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:1bbd134d44839258172e013fe84bfd174d36d6b7232e2cc8a3d8556998181d9d
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 12105116d3c87f4f079dc31142950fc506ad91fc
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:6a75df76fb0d9516b13fa6b079bc6c4d49dc6774f0d4f31343abfb8d70edcc23
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 1ce65a46cb454cf6490e8f63cf708124606d870b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:d068d73f41d8f8ecbec36752d0a432913bfbe2580f489abefe513c06233e80c9
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 1ce65a46cb454cf6490e8f63cf708124606d870b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:edbb174cb69dd31339a53542d24c4fd00552e41fa09d7e2553baa7a1ad8dd810
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 1ce65a46cb454cf6490e8f63cf708124606d870b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:902c5b3b4a4e8cb0a14fa5aba8451ec02830d5167ff1b91323ded62255983cd9
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cdfb1615404c21983260a55a8a66bc6781e9d004
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:1b218f0aa0ea1f494094e3bc783ef40968cbff780e22de186d578a1d64c33bf8
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: a78fa7860413317be5115c8a8d46221d00fdaf12
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:8db1386d12d40dfbc80054c023897e5bfc0a987f6d07792b0f9f50f59f1a68d8
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 30e30dd46288e4b0616641beb021ed4810241dd9
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:25ec9a0cc4ac92d4bed75c38fa37ef8d5ff9478cc475049b303d74eb58687a81
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 7cc2c7c0bb20ecd32738795f2387b3be6a63a2a2
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:ce0fd7bdc73cd2c84d1a9c5af528916488ca8116dd05d83dacf72f2af4248e65
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: d84675da2bfb1bd82a6b2c11394879968eb2b3df
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:9555fd5f577f32a1d8ebe25f0d03e453c8ea925e4a12dbbe1015c58d3c8528b0
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 929b3f63644ffef3ca597d7fa69d4013a60014e1
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:ea57247cf11f6ab966893ce4e6d2948232a4314588af2ca33c1d9689da7482dd
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cfde8c0cfdfbcaa61e54b9621bdf4d72f1492fa6
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:a41cafc65e30deb073e051542702e258901b552ad00e42eacab05d149d6f0565
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 98a7e79c19d4b83caa8a9ed90050191cfe334ed6
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:37087ad8678f3e8ec8e2b2d035d3a12087ce9e0c993194a04a9874fd07e80d91
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ff719f61af88b0e98c68c33cc6e464d49c112a58
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:72a4ac73bb5e7797329e1856f785751d48815a64e82350a5d694bb5a8e121956
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 36d42b2a397668e9ecfbe1cbd03aabcd70abad69
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:a91276fcf5a589ef11f01b39df7d33ceb58ebcb47f95dfab772114bce7c1b4a8
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 03addcbec12b1675a8fdf15c05688cc796e731e6
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:5e6594464bf7ddc2a66f127f645d93ad35d8cd95dd70544fa7fcec791f67f45c
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: fc33389bc5db24c4210ddf13d1e68b589312a5e7
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:f3d65f68538e94260fad54f145433a36366f8c88f9c9f80b7fc5545ba62e1773
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4d337b1d11d9d76f844820668dab6c75e2a189e8
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:b510a25a6370ca6b8d2f74165814ebfdae0ce9898cc343e73fab6344eebf2bed
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        revision: b6ba4e8516de658dd7ad398c24f4347c9a7de5f0
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:8d189b565e4c3c434988aa4ff0ecad4c5f86b2a94120325c142ff111b25facde
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 809cf5128f453e9b82cf763830a473dea222f0d7
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:36a6000b6482966f8bbf86e45c25335c066736ae1f8695a8b68e6b76b7c491ac
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 112513b8ce8c7065c4a6cd4d5be5e78e7bd04640
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:cecec1f7d7f0d37cf17fb25ccf34602728f2a09c61af7e212967b4ee28d2dec3
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 0e373e4a8a99c10b5af6865c45b78373960bc85e
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:8901e984b3b47f0650cddc1c36bdd89af22390f3d4a562d562fde7774d8ba6db
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 880c27856deb7f429dc94496c24a8099469ef79f
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:ee75e805f0f9d73f073ce870f5d46962c0033d63158017841d17410febfc2c57
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 1ce65a46cb454cf6490e8f63cf708124606d870b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:8076db8ccd5578cb5aba2d66f53790563d3f42b93a6cfd14c7094d3a25707982
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 714c008c19e6de1ba1a47b03dda6bf89fc9bd333
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:bf343592bf2f4399b5ac61709f56528435990e903812e264cbef845ff4433231
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: b78b776de14fef5fd8bd6ec56abc94086bf8f2c3
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:a8b1278a2df9b17cee66813715995385bb3539af05e4df9b5bf7d9ccd508c313
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: b6ba4e8516de658dd7ad398c24f4347c9a7de5f0
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:ad382d5eb347c448c46495a0a17503d789db4eb1096ad71a588b316b235e437f
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 1ce65a46cb454cf6490e8f63cf708124606d870b
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:cd9dc89b933b394b08fe05ab5f0bbecea727bfb2c29770f11ec1db4aa5740b3c
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9a7e5d1fdc41673d245a4de6b6e0f7b321449402
        url: https://github.com/stolostron/provider-credential-controller
status:
  conditions:
  - lastTransitionTime: "2025-07-15T08:36:10Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-07-15T08:37:12Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-07-15T08:37:12Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-07-15T08:37:12Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
