apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/cluster-curator-controller?rev=4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
    build.appstudio.redhat.com/commit_sha: 4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "51523494481"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-zhxezc
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/cluster-curator-controller-mce-29-on-push-lrr2q
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: cluster-curator-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "493"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/cluster-curator-controller
    pac.test.appstudio.openshift.io/repository: cluster-curator-controller-2kgj
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: fxiang1
    pac.test.appstudio.openshift.io/sha: 4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
    pac.test.appstudio.openshift.io/sha-title: 'Merge pull request #493 from ralphbean/backplane-2.9-KONFLUX-6210-cluster-curator-controller-mce-29'
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/cluster-curator-controller/commit/4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-curator-controller
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-curator-controller
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-lwtj6":{"lastUpdateTime":"2025-09-29T18:40:50.246729816Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1759170577"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.9
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/cluster-curator-controller
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2025-09-29T18:40:50.246729816Z","details":"Integration
      test passed","startTime":"2025-09-29T18:40:15.015690101Z","completionTime":"2025-09-29T18:40:50.246729816Z","testPipelineRunName":"enterprise-contract-mce-29-vs8cq"}]'
  creationTimestamp: "2025-09-29T18:40:14Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: cluster-curator-controller-mce-29-on-push-lrr2q
    appstudio.openshift.io/component: cluster-curator-controller-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "51523494481"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: cluster-curator-controller-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "493"
    pac.test.appstudio.openshift.io/repository: cluster-curator-controller-2kgj
    pac.test.appstudio.openshift.io/sha: 4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: cluster-curator-controller
    test.appstudio.openshift.io/pipelinerunfinishtime: "1759171209"
    test.appstudio.openshift.io/pr-group-sha: 3f5ad436ec9e59c9f4c91e27298a4c40745f9b3ecde6e100e6d73cf94ffb6f
    test.appstudio.openshift.io/type: component
  name: release-mce-29-lwtj6
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "5273100498"
  uid: 372e1682-7f7e-4ddb-b14a-e36348007f8b
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:a4129c478b3316e6e50723e88c597dac37f9dbb52d934b5e47c428f04001df67
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: c1fa0769a32eb9fa9e0437971a24f4943f8262b8
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:562e84316ce049ca686c36cb49f188a1934e1d02b62adcc23d94f142784afad3
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7d832b2fd92345ef51562488e96ba2783c88db27
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:6e0215e27a8defc84b1a2d30df77b7e3e776b55dde398d451b3968f17a7724d8
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c618f75439aa13f19607ef4a9c9e61af0124eaa4
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:eb547d2e08d9308883973aab57f8a811e3637315d485b9395db9b3f3e01418a4
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e4095780afe8c619968a478331d357b5cf6d5574
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:aaa6e8e853469c9bb3338199c4554ce39077afd69ac82a981084464fb57c3533
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: ee85e67268d33efed50b624b247bc50f341b16f3
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:6aed1b7462809dc97441656b9b1f3f3915ef3a72d3fe95cd6f6749020d4a0c4f
    name: cluster-curator-controller-mce-29
    source:
      git:
        revision: 4523fbfdd6b97b9e20b0e8dd7e1509e6114d99c5
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:f1e24af086c099ddf06ceb347e121b4883fc468e278cf0127bf46cae86fb27a2
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 61a5fb5d58056eb8cbc3885c4b1417e596b258ce
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:c02e3da65eebe71065f6b96f14a72ee9f21eb9aaa022a321a10a0639263ec3d3
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 501d43cb4983422fbee372af47ef134f3a9f5638
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:a1ccc873eafda2e709a6e51912b1c32e33456e78be3bc3b4e16097640b8a37b5
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:a5cbfa10deb806cf36a573a0987b3b82f0520838f805d78505411afbbd02bfa1
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f72f75b656967073d68e91500511a8ef991c2d5d
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:021e3f84ed3e06bb43478e4eb086ab83be8f3b806b39f98c4b4604018da42058
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 6092642a8c02c91a3620b03130223dbbd4b043bb
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:f35cd2aa4fed0188f9ef0fe7eff96c8e56e76183627eba433ecf96159445b212
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 4a2c8feef2255ba92e8e76046dbf16177907f76f
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:52d17ffa5b2761987f2831280db7d4a2dd29bd78f61c9ebec70a63e669b59809
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cb753172342f4dfdd7e022b24ffbda99c4aa41ed
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:e9fbb51a2d6a471df4155ef6807e04b3a244708f829fc1a567e29451a13f9066
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 9359b998ac1769eca470bd0466a5b960357fd427
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:740271bd4fdbfecd14cf632968a182cb542a241e840fdcf564248a420e5c013c
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a875352be0a241119334c5339c461d0a0d35a624
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:a6c94c0dbb516f04ff46afb8ea17205e8b377ffc187edc73bcac46fb0aeea5ca
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 685cd1108a3b2d6de2eee7c4f9c62e84dae761c1
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:ce05a79ae5fd2cce07d70fb6a30634ec5681cc2ca4873de9e5cea24a033e2ebc
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: caae901a3727422629e5bd0676bb19b82c9f04fb
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:5f44cdcb2aea15f55117dcfebfda9443385d1a7622583637504e5d0997c7d8a8
    name: backplane-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ef8183f65b80300d186620d90f42e56c8b87e03e
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:30fd5193b972f93607af9bed0e91fd87fa6cfb8e9cced3e8c8c0753400f1fcbd
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 63010e4e8b0b4fb178b31d6241ea92396906ce68
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:38a3638cb7e980223b3f782321d8c6601318fca0bf83986feca78f75fdc4cb26
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:51ba517079992cc3e295adc93b1c5c9381d6a83cfbb9abd74765098ed4280890
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 64295b2217c68b3b0001268c023fd8573c5c1f31
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:ce12d193c72cffefef6695130f8dcea0460ee88d0f6d5f98516d5bd4deb963d3
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: a43b6c173e3f8ca6a1071b73e0691d568c65396f
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:5f27f6c7a20977d568e513edbb2c9dd7ab2676f773325f84930e8fc6f260359e
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:37a9bb6fe585f97a8aa87a5709bf547e5b2699710c8172b69d0d20b2ab8a55b7
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 81ff056c9431c4a5e4234955ebdcf4f8ceb2559f
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:261877be379be8d71f5b6d7aca4e6c90056a7ef6abf13c5c8da52ec150be34e1
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 63010e4e8b0b4fb178b31d6241ea92396906ce68
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:2dd8c3e3447c7f1952a93eb81e802d4b6e7dea5793e94f100b544daa19c9ab86
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: d47a6d0e6443b9ac611945eddd72b7431c3249a2
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:a53401f933101ec7ec1d91b27d932fa7fa19c5ee8b881342f43c2d36c85a42b7
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 043ad9ce26197e52b0fe519279cc310459fd7d4e
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:dc8f9dab3eb5061bae58faa7e2bdb2bee468d3efcc6fe71ab72078956fce7029
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:dd83630f5b747ec8f83918617c2528eeecb87d34919490e18f7d9ce549346f03
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:6ffa6e4d90c5b49e7e501fefff72935012682cf9fb3a721da5417facc811468a
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 685cd1108a3b2d6de2eee7c4f9c62e84dae761c1
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
status:
  conditions:
  - lastTransitionTime: "2025-09-29T18:40:14Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-29T18:40:50Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-29T18:40:50Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-29T18:40:50Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
