apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/ocm?rev=502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    build.appstudio.redhat.com/commit_sha: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    build.appstudio.redhat.com/target_branch: backplane-2.8
    pac.test.appstudio.openshift.io/branch: backplane-2.8
    pac.test.appstudio.openshift.io/check-run-id: "51750733537"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-jtmdoj
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/work-mce-28-on-push-4jxtz
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.8"
    pac.test.appstudio.openshift.io/original-prname: work-mce-28-on-push
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/ocm
    pac.test.appstudio.openshift.io/repository: addon-manager-mce-25
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: incoming
    pac.test.appstudio.openshift.io/sha: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    pac.test.appstudio.openshift.io/sha-title: Add MCE_VERSION and SOURCE_GIT_TAG
      environment variables to registration-operator Dockerfile (#475)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/ocm/commit/502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    pac.test.appstudio.openshift.io/source-branch: backplane-2.8
    pac.test.appstudio.openshift.io/source-repo-url: ""
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: ocm
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-28-release-mce-28-wdkj5":{"lastUpdateTime":"2025-10-02T00:04:08.07476417Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1759362626"
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/ocm
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-28","status":"TestPassed","lastUpdateTime":"2025-10-02T00:04:08.07476417Z","details":"Integration
      test passed","startTime":"2025-10-02T00:03:33.426971049Z","completionTime":"2025-10-02T00:04:08.07476417Z","testPipelineRunName":"enterprise-contract-mce-28-swp2v"}]'
  creationTimestamp: "2025-10-02T00:03:33Z"
  generateName: release-mce-28-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-28
    appstudio.openshift.io/build-pipelinerun: work-mce-28-on-push-4jxtz
    appstudio.openshift.io/component: work-mce-28
    pac.test.appstudio.openshift.io/check-run-id: "51750733537"
    pac.test.appstudio.openshift.io/event-type: incoming
    pac.test.appstudio.openshift.io/original-prname: work-mce-28-on-push
    pac.test.appstudio.openshift.io/repository: addon-manager-mce-25
    pac.test.appstudio.openshift.io/sha: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: ocm
    test.appstudio.openshift.io/pipelinerunfinishtime: "1759363406"
    test.appstudio.openshift.io/type: component
  name: release-mce-28-wdkj5
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-28
    uid: 1bb16185-3532-42f1-8819-a53d8cfd38dc
  resourceVersion: "5305202212"
  uid: f33280c4-d638-4d41-b96d-caaf6f9fa7fa
spec:
  application: release-mce-28
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-28@sha256:557bcaf3a34acc3517196f6372c51f99b09a9b5ac61e58728181de29279497ad
    name: console-mce-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: fa98d5e66829bf2b8e8a090ac09b4a7b3b932dc4
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-28@sha256:efb8663f692e10d369619a993fc481f25b091ae825e1a105fca51263fb53a6ed
    name: backplane-must-gather-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ccc2321a183c5c33ea7f3cfa84d1726d7042e2d6
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-28@sha256:0832b0e5cba0d693632e92c335563e7cc672f3d08c834bc56b099b4f8af4242b
    name: cluster-proxy-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 49177b034559cb4e19efc14f3331bcbb926d885d
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-28@sha256:3ad67e2dc6852dd8884f24f706d02c7744d28d18219e8f2eaa9981b7e629c88e
    name: hypershift-release-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 4efd9e81f59eb6138511b39facb8079c987a5144
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-28@sha256:7294543946b1e722f47677cbfbcb3e9b0fa02a1663ffe5f10330e3b84322c41e
    name: image-based-install-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 838312bdc10a32227ad5aa347601b565d831666e
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-28@sha256:9917355547f1b8ee6aba79b0e1bdab3436b1a00157051e52e50b957b5d294227
    name: registration-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-28@sha256:eebee33de7751daa8de2490f3ae1bd3a500c481b0e35c5840183e4bc5bb58ac5
    name: work-mce-28
    source:
      git:
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-28@sha256:7e69b87dfbd0859023de37e446401fb854cd379417821890bf5f91e9d3c02824
    name: backplane-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 41d4e8830a0e34be429a580319600f84f799aa36
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-28@sha256:d4f34bbfaab7225e357040dad7e1dfb6ce9d9595d52effc215c7bb931cccc701
    name: cluster-api-provider-kubevirt-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: bf9721135d98560e9840aa76cd8ccb8d3b7e3ff1
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-28@sha256:bc5c458708795cee93f9f0711c2377e40cbbb296f0b5031e656bcf39593ee100
    name: discovery-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3a80331d43bd7b99b904301af5444946ea338b4e
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-28@sha256:4e8f7f13e3059628ee02122a0af94466a57d901df135fb329db92a31ff18626c
    name: hypershift-addon-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: e897a22b745e889224480ceac08b42a0a158467d
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-28@sha256:abd5bbc32a5e424b9ef2e2fa78616953956f09c6487259612183091c9e90787d
    name: kube-rbac-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 7c18f8b5519a2d04a920679ed9faade52fec02f4
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-28@sha256:6714beb96064f086a28fef79357966702be0ddfee7bcf6060062831b811194a9
    name: managed-serviceaccount-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f6f650cba5c5fd71afd110fe9c8b9e5603686fa8
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-28@sha256:a82d88e92a2412782e410dc85269d47a4530b652d8bcbce7fcd6df63eec02fe4
    name: provider-credential-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ac181e585fd81be1f0285291ab7d2dd83c2c1452
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-28@sha256:47935705e75333cc7081513a858b7dce7ad88a69d9a5a2845523e2bf7586ad7e
    name: registration-operator-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-28@sha256:b39c53be01d55edb3b9f984038cc8837c449ef2796c0a1244e96f7aef882f077
    name: hive-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 08341899d1d333720c764780b2872195202f9979
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-28@sha256:a73172012d4ad3089653aeb16ed2db044e0eaf41d126d64af74b73549747c33b
    name: cluster-api-provider-agent-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 30182ceaa8ce4bbe37137274a734329a50f63271
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-28@sha256:4a2dba3a5efb25fe27ad8d160102c10ddd753beb319e9416e3ffd80ab1aaac15
    name: cluster-curator-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c66264d417949884041d549f0bfdae65a011ca77
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-28@sha256:05d60a4ccfe67ab2c38f284adec5563350f2c298bbda87e276a30d809a189312
    name: cluster-image-set-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 3c09d597118a38e922e38e50e551f4839fa5c815
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-28@sha256:e6bda83c23df7f573dd5518564f47f583cf82299985d7ab643c8babfc9ef3d2f
    name: cluster-proxy-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 974775787c8f27de637f454f5bc51446ac75370b
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-28@sha256:bbca683b8352bc22c72bc76d4320f998e7dafc3d7d4c49a34330810210199061
    name: clusterclaims-controller-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 0458daeb54db76bc4b95853a6cd22f6212ac5252
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-28@sha256:ff8802c1348803f5389b332f4ad4c40fcce6482aa9f66deaf9de61bde3837c79
    name: clusterlifecycle-state-metrics-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 7c5d1b94fed1c79d4c3179d0be7bddd1e9c08892
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-28@sha256:81511b244f8d96c03038943ccd0450317b09c5707cbf2efe106413c13f6198ac
    name: managedcluster-import-controller-addon-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 72be166c28a115ee5f104afb5081da59acd01be6
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-28@sha256:6cdda7515ea7b6fe1491a8a0a57b6545d1a3ef8b925647dac38b5bd7745ac0bd
    name: addon-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-28@sha256:b5df2b88286ccdc9f172d0038b3f3d24c64bc7edc2ffac032f2509d2be86cbf7
    name: hypershift-cli-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: 65c8b9f2e85e36545140ed5df17c9cba755a6fd1
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-28@sha256:e83264fd8e608146f30a1bbed69c6b3d770c2a550e6db3c4b7ba163e558093d3
    name: multicloud-manager-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 88fc6e87964fe89682d7e740ebbe31ae27e91888
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-28@sha256:7e1d03074f27821aad5fecd56c0ec5088eeae2685019ace4489768755d3a7132
    name: placement-mce-28
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 502cf8d8f1776f1106582c1e8631e2ccbbe790ce
        url: https://github.com/stolostron/ocm
status:
  conditions:
  - lastTransitionTime: "2025-10-02T00:03:33Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-10-02T00:04:08Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-10-02T00:04:08Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-10-02T00:04:08Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
