apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/console?rev=2c510fed6b1d3c1d5d312710becf2a0079acde4f
    build.appstudio.redhat.com/commit_sha: 2c510fed6b1d3c1d5d312710becf2a0079acde4f
    build.appstudio.redhat.com/target_branch: backplane-2.10
    pac.test.appstudio.openshift.io/branch: backplane-2.10
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49974997968"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-tkstts
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/console-mce-mce-210-on-push-hxpm5
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.10"
    pac.test.appstudio.openshift.io/original-prname: console-mce-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "4976"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/console
    pac.test.appstudio.openshift.io/repository: console
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: acm-cicd-prow-bot
    pac.test.appstudio.openshift.io/sha: 2c510fed6b1d3c1d5d312710becf2a0079acde4f
    pac.test.appstudio.openshift.io/sha-title: sets cursor rules for console repository
      (#4976)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/console/commit/2c510fed6b1d3c1d5d312710becf2a0079acde4f
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.10
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/console
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: console
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-210-release-mce-210-r4xqf":{"lastUpdateTime":"2025-09-09T18:47:33.732528296Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1757442355"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.10
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/console
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-210","status":"TestPassed","lastUpdateTime":"2025-09-09T18:47:33.732528296Z","details":"Integration
      test passed","startTime":"2025-09-09T18:46:42.840984457Z","completionTime":"2025-09-09T18:47:33.732528296Z","testPipelineRunName":"enterprise-contract-mce-210-gbrnt"}]'
  creationTimestamp: "2025-09-09T18:46:42Z"
  generateName: release-mce-210-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-210
    appstudio.openshift.io/build-pipelinerun: console-mce-mce-210-on-push-hxpm5
    appstudio.openshift.io/component: console-mce-mce-210
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49974997968"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: console-mce-mce-210-on-push
    pac.test.appstudio.openshift.io/pull-request: "4976"
    pac.test.appstudio.openshift.io/repository: console
    pac.test.appstudio.openshift.io/sha: 2c510fed6b1d3c1d5d312710becf2a0079acde4f
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: console
    test.appstudio.openshift.io/pipelinerunfinishtime: "1757443596"
    test.appstudio.openshift.io/pr-group-sha: 72b3ef008256132a511ab42a799a5054c1b4087880cee879ab80db01c93ebb
    test.appstudio.openshift.io/type: component
  name: release-mce-210-r4xqf
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-210
    uid: 991ec411-638f-453f-837e-5b8d3562aa61
  resourceVersion: "5038187513"
  uid: 359b5f77-4d3e-4c14-b41e-7bd30bbd8118
spec:
  application: release-mce-210
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-210@sha256:3da42b6fd2ead2b74694b37a827f222ad50af7aa65e255a293425cf7bbf412e3
    name: multicloud-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: add2996964cf684147fc9d7f71386b48ca828536
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-210@sha256:00bb7aad2b971bd391c4b3fd00715b5fbc8f3594c3712b2df0cb7b5b71a2c6ad
    name: registration-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: f1843e5a6b2d87614f94b62dfd47feeebbef7eab
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-210@sha256:07ddae9cc985861aebdefbc0f02ab4983e8f9355019b801621765185556c9841
    name: image-based-install-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 69a8aee6bb5d52da72bb05b6462cb647d9e82b39
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-210@sha256:e78210eb1888f58251c52616cc487a4b309e95f8182a0a7893e9b6d26fc6a3d6
    name: kube-rbac-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 29232f81fe535e11646513eeb2ff01fe601f6eb3
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-210@sha256:4f566286a2a4bd72ea15170c1ba771932eb06117c5701c3670eec12d02a291ca
    name: cluster-api-provider-openshift-assisted-control-plane-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 05199d10b322273b0a9989a70f4a5260695fcf1c
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-210@sha256:66b56c388cb44d6bfff8cf3c98f35d22114865235a0ffff79abd40e62626d5b2
    name: cluster-api-webhook-config-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 90c6648c0d963a50b4e355e85b0a8fe9827e8227
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-210@sha256:743a4047f11232d25d11fe6caad1607f64ee3f48739dc3d1116a3ba0bcff47a7
    name: cluster-curator-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 466125c2c29227d573d693d06cd2c93b68071a0c
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-210@sha256:bc66ae06442d693689da4c0277b3305f66c5d46cf269b3832e583dfc1a17451f
    name: cluster-proxy-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d430978bca78b616070ddf148df9f206a8f4e110
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-210@sha256:41a7a2f61a71246584c0a2c4bec2f138f8e5b0455abed3978e8fe7f1a54ea30f
    name: clusterclaims-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 02c45a3f829deaafedd645d571504dd826cf1441
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-210@sha256:713ac2eb7af9d011dfc2c207bfee16697e89ea087963d6f99b155952b38ecf0f
    name: hive-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: a4611b9a1a8227de8aa7daab65085e559bd9a7dc
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-210@sha256:3de3ac6871621f487d766e0c9c85bed9220d84d5a0093428c1e23d7335f0bed2
    name: managed-serviceaccount-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: d0fd925bfe36507187da55b08fccc26c662963a1
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-210@sha256:6f1f3e53c05f45657a765936f05885505dce94388b8e2f3f589ae173f414b049
    name: registration-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: f1843e5a6b2d87614f94b62dfd47feeebbef7eab
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-210@sha256:9b666863afb4c95e6416896cfdf14ebbb2562783e48c9d4ade9a4e582a7464c6
    name: cluster-api-provider-kubevirt-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b0237a356c830b986b6de9dbae2450ac804bb77b
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-210@sha256:f1342d9e5944efa31beb44feb076516e3a85c2bdd88cc642b4669ffa28e8fa92
    name: managedcluster-import-controller-addon-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: 97ecd136898d39f4bc7086021e561d7cb184fd0f
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-210@sha256:abb2862b729909bfecc86a314ce1e72b306e5710eafe5fd8c599fa1aa1ef2d28
    name: placement-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: f1843e5a6b2d87614f94b62dfd47feeebbef7eab
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-210@sha256:cf82188a4f1f6966e39ca9ad63148a9b121db657fda5c2f68c2264c2d4818206
    name: provider-credential-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 707a815152c4329312a0826eee72851ae9cc33e3
        url: https://github.com/stolostron/provider-credential-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-210@sha256:4a8d0f9a773a24af07bb091f28699ababe15afff57decf3717db651de577162d
    name: addon-manager-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: f1843e5a6b2d87614f94b62dfd47feeebbef7eab
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-210@sha256:7203601aac68aa82e9b1c8d82fb77c5783b2bd2758125459b56a606e055ab2ad
    name: clusterlifecycle-state-metrics-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b4dadc06c655397d64330aec1c9a791fdfa5c154
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-210@sha256:3ed31199dd3d34bd81e44711e07fed9a122600295ebcab1e78e267efa76f7656
    name: console-mce-mce-210
    source:
      git:
        revision: 2c510fed6b1d3c1d5d312710becf2a0079acde4f
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-210@sha256:0b3bef84ff1e4806724d0446c3d8beae452007e29a14af6283413cc0ec114010
    name: discovery-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: ecc67351f078b669d0543ff6e74a0d6fe316990e
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-210@sha256:ce81ab7826b357c8e5a1e5c340f80b658b41bc2165e8ff59540912bf062875cf
    name: work-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: f1843e5a6b2d87614f94b62dfd47feeebbef7eab
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-210@sha256:7df6b879648b3f3ca4dcd92ffe37edd551415d1ba8f2a0844d64c00a35e0ce55
    name: cluster-image-set-controller-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c1b0e4c48e4e7a23c5bee26a17b89749f91341a1
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-210@sha256:b675b65e6d4c0c5910092fc9a04e3c6cbfa5bd1d0fe31115f190d586c5d13c67
    name: hypershift-cli-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: d0949b2672ed9e1bca4b44bc48c71c1dc7b3de39
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-210@sha256:73d8945212017ec82736e9ddd08d17e405fc57e30ce0dc05b830fdb215eb683a
    name: backplane-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fed6c3ad4a41cc88098787ce109fae473bfcf03a
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-210@sha256:109a5d2c8918b6534b09fc7037bc5b4dae3af2a981717f9569690a9826520c2a
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 05199d10b322273b0a9989a70f4a5260695fcf1c
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-210@sha256:c8252b77bc02d994ea57e6a9cde7e2d8eaf12944f723477ffa34bf2d4bc6493d
    name: cluster-proxy-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: 62c16fdf6db72f4496ab176047b99231fcb506d1
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-210@sha256:b1aa0a52fc4f2e3248f536bfa1f46fe0a2e2158483d14b356ee9c4790716ca84
    name: backplane-must-gather-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: fb4ab7480926b6be1c286ad7f7eb7dd4c2f4a91d
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-210@sha256:024f0faa4f95269a528b5b77505d531d26cdac502a73a383951aab8e698bd6e3
    name: cluster-api-provider-agent-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 2bc44cc6d363361aa889df323ebcecab47d28862
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-210@sha256:15e062bcfdfa74f468ed6a19f641ce856adbe19537eeee5d43d8377d3faf90d0
    name: hypershift-addon-operator-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: a6212f44f64d8dc1f454d1946f336bdca29c18ed
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-210@sha256:bf395a42b081d18c842321d01e48a504047b55fb37ede76ee59a6e00e1ee5770
    name: hypershift-release-mce-210
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: d0949b2672ed9e1bca4b44bc48c71c1dc7b3de39
        url: https://github.com/openshift/hypershift
status:
  conditions:
  - lastTransitionTime: "2025-09-09T18:46:42Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-09T18:47:33Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-09T18:47:33Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-09T18:47:33Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
