apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/backplane-operator?rev=83639fca1db4eda629987a160d43c69a2fbd9d3f
    build.appstudio.redhat.com/commit_sha: 83639fca1db4eda629987a160d43c69a2fbd9d3f
    build.appstudio.redhat.com/target_branch: backplane-2.9
    pac.test.appstudio.openshift.io/branch: backplane-2.9
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49977593202"
    pac.test.appstudio.openshift.io/controller-info: '{"name":"default","configmap":"pipelines-as-code","secret":"pipelines-as-code-secret",
      "gRepo": "pipelines-as-code"}'
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/git-auth-secret: pac-gitauth-enafze
    pac.test.appstudio.openshift.io/git-provider: github
    pac.test.appstudio.openshift.io/installation-id: "35324288"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/pipelinerun/backplane-operator-mce-29-on-push-mbxpt
    pac.test.appstudio.openshift.io/max-keep-runs: "3"
    pac.test.appstudio.openshift.io/on-cel-expression: event == "push" && target_branch
      == "backplane-2.9"
    pac.test.appstudio.openshift.io/original-prname: backplane-operator-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "1865"
    pac.test.appstudio.openshift.io/repo-url: https://github.com/stolostron/backplane-operator
    pac.test.appstudio.openshift.io/repository: backplane-operator-qa7p
    pac.test.appstudio.openshift.io/scm-reporting-plr-started: "true"
    pac.test.appstudio.openshift.io/sender: openshift-merge-bot[bot]
    pac.test.appstudio.openshift.io/sha: 83639fca1db4eda629987a160d43c69a2fbd9d3f
    pac.test.appstudio.openshift.io/sha-title: Updated imageMappings for cluster-api
      component in MCE 2.9 (#1865)
    pac.test.appstudio.openshift.io/sha-url: https://github.com/stolostron/backplane-operator/commit/83639fca1db4eda629987a160d43c69a2fbd9d3f
    pac.test.appstudio.openshift.io/source-branch: refs/heads/backplane-2.9
    pac.test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-operator
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-operator
    test.appstudio.openshift.io/git-reporter-status: '{"scenarios":{"enterprise-contract-mce-29-release-mce-29-8n5tf":{"lastUpdateTime":"2025-09-09T19:10:05.149295324Z"}}}'
    test.appstudio.openshift.io/pipelinerunstarttime: "1757444314"
    test.appstudio.openshift.io/pr-group: refs/heads/backplane-2.9
    test.appstudio.openshift.io/snapshot-creation-report: BuildPLRInProgress
    test.appstudio.openshift.io/source-repo-url: https://github.com/stolostron/backplane-operator
    test.appstudio.openshift.io/status: '[{"scenario":"enterprise-contract-mce-29","status":"TestPassed","lastUpdateTime":"2025-09-09T19:10:05.149295324Z","details":"Integration
      test passed","startTime":"2025-09-09T19:09:16.984406016Z","completionTime":"2025-09-09T19:10:05.149295324Z","testPipelineRunName":"enterprise-contract-mce-29-xpcqx"}]'
  creationTimestamp: "2025-09-09T19:09:16Z"
  generateName: release-mce-29-
  generation: 1
  labels:
    appstudio.openshift.io/application: release-mce-29
    appstudio.openshift.io/build-pipelinerun: backplane-operator-mce-29-on-push-mbxpt
    appstudio.openshift.io/component: backplane-operator-mce-29
    pac.test.appstudio.openshift.io/cancel-in-progress: "false"
    pac.test.appstudio.openshift.io/check-run-id: "49977593202"
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/original-prname: backplane-operator-mce-29-on-push
    pac.test.appstudio.openshift.io/pull-request: "1865"
    pac.test.appstudio.openshift.io/repository: backplane-operator-qa7p
    pac.test.appstudio.openshift.io/sha: 83639fca1db4eda629987a160d43c69a2fbd9d3f
    pac.test.appstudio.openshift.io/state: completed
    pac.test.appstudio.openshift.io/url-org: stolostron
    pac.test.appstudio.openshift.io/url-repository: backplane-operator
    test.appstudio.openshift.io/pipelinerunfinishtime: "1757444950"
    test.appstudio.openshift.io/pr-group-sha: 3f5ad436ec9e59c9f4c91e27298a4c40745f9b3ecde6e100e6d73cf94ffb6f
    test.appstudio.openshift.io/type: component
  name: release-mce-29-8n5tf
  namespace: crt-redhat-acm-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Application
    name: release-mce-29
    uid: 20473971-c86b-40e3-8b15-f0637463a27d
  resourceVersion: "5038400280"
  uid: 7410637c-7e68-419a-88a4-57d99c231ea6
spec:
  application: release-mce-29
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/work-mce-29@sha256:6bf7d1c2005fc79785e7a4f814c65d55c3c02d69c4b6ef62678bcbbaef16666b
    name: work-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.work.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-addon-mce-29@sha256:286bc0ef666f03b5fa253e3a3257246cbd4da4c51153bd14a1dba7288192f1ce
    name: cluster-proxy-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: f72f75b656967073d68e91500511a8ef991c2d5d
        url: https://github.com/stolostron/cluster-proxy-addon
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/discovery-operator-mce-29@sha256:8ff8497d38e7142b7f564db8b5aed85aea340772d585336714190330b5906e3f
    name: discovery-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 282bb4fcdda5b1918f7dde577bd59773d8090bab
        url: https://github.com/stolostron/discovery
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-release-mce-29@sha256:dddea71d20dff988a20f84ca9b5277f23ff52510a97cfc2be5757f1a2ce45a38
    name: hypershift-release-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: edfa49d7396105759a6019f6ce16be00331c6440
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-operator-mce-29@sha256:318a016762548a68d163eeddf50b310c60efe7135c14d144213e5df1912beb76
    name: registration-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration-operator.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/addon-manager-mce-29@sha256:8770e04f759aa7010019e780dd59aad1c3519af88f62fda0f4946b746b980478
    name: addon-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.addon.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-agent-mce-29@sha256:6a1843a583709bd299f12d1919ce67b3381ae06e807789fd22eaa835054b134e
    name: cluster-api-provider-agent-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 87dff4d321e53ecdffcfcd10c0f5ea51b0a2f15a
        url: https://github.com/openshift/cluster-api-provider-agent
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-cli-mce-29@sha256:f460d748fd17bf92b63f08460a5e06eeb04def79d4381650e4ab1cd529c1b5f9
    name: hypershift-cli-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.cli
        revision: edfa49d7396105759a6019f6ce16be00331c6440
        url: https://github.com/openshift/hypershift
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-bootstrap-mce-29@sha256:93cd0957d534e6218c3dde901291f09f0626e1f4f5292fb47390e47a2ef1dd80
    name: cluster-api-provider-openshift-assisted-bootstrap-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.bootstrap-provider
        revision: 2e99638ac0139ffe0aac8795eb2675a37e5a428e
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-must-gather-mce-29@sha256:6684290b745103fb378b067bac0e782350974511915495e15a6d10ebc2787756
    name: backplane-must-gather-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c584fc61feb9256543d706ce1dd8d17a7858b3ae
        url: https://github.com/stolostron/backplane-must-gather
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterclaims-controller-mce-29@sha256:3b2cbdcea0c8416523012785f007f2a463db78bb3cef33dd7cb93d8dd1f558d4
    name: clusterclaims-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 1b0c5f8baf37578e76f346b58fe46af7f9ccc5a8
        url: https://github.com/stolostron/clusterclaims-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/placement-mce-29@sha256:d48dc087e6cd76ed7c03d38d1004fef3a60390f0908177d9a54e177da5669bab
    name: placement-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.placement.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-openshift-assisted-control-plane-mce-29@sha256:c6392b18d6868285b1bb364942eb817d55b5aadcb93001f0a94d9ceaaec6a03d
    name: cluster-api-provider-openshift-assisted-control-plane-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.controlplane-provider
        revision: 2e99638ac0139ffe0aac8795eb2675a37e5a428e
        url: https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hypershift-addon-operator-mce-29@sha256:da5f3062bd9d300f7110db52533a23af631050321bb8e3aa1c1832f2ea829fbb
    name: hypershift-addon-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 486a2e3997179a38badcb7f204a486b53f9a77c8
        url: https://github.com/stolostron/hypershift-addon-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-webhook-config-mce-29@sha256:cb8836f2b75b67358c388b8c5dab1587a661c17dd270973b436d8171b8705055
    name: cluster-api-webhook-config-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: mce-capi-webhook-config/Dockerfile
        revision: 18e4771f30788b1e780ba3ffff8f9ff6841f3123
        url: https://github.com/stolostron/cluster-api-installer
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-proxy-mce-29@sha256:e25ee4d80c712990a6c528f5f5e9959bacd908cff0b452be4ea24fb27d4e40b6
    name: cluster-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: cmd/Dockerfile.rhtap
        revision: c1fa0769a32eb9fa9e0437971a24f4943f8262b8
        url: https://github.com/stolostron/cluster-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/console-mce-mce-29@sha256:5947e2c65663b1483216cc10b0f1aeded50ab205930e9bd024de1b3235eead16
    name: console-mce-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.mce.konflux
        revision: 351067bf9152d620755f248b4d86511304e40c40
        url: https://github.com/stolostron/console
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/hive-mce-29@sha256:893cd95b0687cc5b017e3493574aefdd258fb1fc2ef2c68a17a2f1d22912309b
    name: hive-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: a4611b9a1a8227de8aa7daab65085e559bd9a7dc
        url: https://github.com/openshift/hive
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/kube-rbac-proxy-mce-29@sha256:20fdb55abcbafd51040e0b2958d488968eaf42d479262ee9e554c1701ecbab7a
    name: kube-rbac-proxy-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Containerfile.operator
        revision: 501d43cb4983422fbee372af47ef134f3a9f5638
        url: https://github.com/stolostron/kube-rbac-proxy
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managed-serviceaccount-mce-29@sha256:af3e9d6269ef8a578f69af5453e9a5bcba91b2cdf15531d4c6dbe61b0ff1bcc9
    name: managed-serviceaccount-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 043ad9ce26197e52b0fe519279cc310459fd7d4e
        url: https://github.com/stolostron/managed-serviceaccount
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/registration-mce-29@sha256:42736911076d8f3254b329347d94a7e440b762418c8fefcc52ad8239970c4e67
    name: registration-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.registration.rhtap
        revision: 6ee73a6ca83c9b51515c4603e80fb61ea54a6409
        url: https://github.com/stolostron/ocm
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/managedcluster-import-controller-addon-mce-29@sha256:0753ef817861975779bc99fd3aaefc0ea66be3b6ee051ea43b88e073eee8e354
    name: managedcluster-import-controller-addon-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: f491c6e9c9770bdf18abfd0e0803a27ae6358f21
        url: https://github.com/stolostron/managedcluster-import-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/backplane-operator-mce-29@sha256:40ba18614e946629a5e8fa0a9316a3e636890132eccc7db4ac44de334a2d6512
    name: backplane-operator-mce-29
    source:
      git:
        revision: 83639fca1db4eda629987a160d43c69a2fbd9d3f
        url: https://github.com/stolostron/backplane-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-api-provider-kubevirt-mce-29@sha256:d455b790ae1aa36b468ce1434d8e55a3a694a62adf5c9799d5ba67185f248e87
    name: cluster-api-provider-kubevirt-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 714c008c19e6de1ba1a47b03dda6bf89fc9bd333
        url: https://github.com/openshift/cluster-api-provider-kubevirt
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-curator-controller-mce-29@sha256:d55c492358c276cfc07f4ba6ed068d78c852e9b0cfd33b97b59c0d6e0854eeec
    name: cluster-curator-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: b26921fb30b146a778dcc73135db785077bf0f89
        url: https://github.com/stolostron/cluster-curator-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/cluster-image-set-controller-mce-29@sha256:5e9547c326df058bf9dbf9e716321c0abc3f75a63d934175283356ea3facdb32
    name: cluster-image-set-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: 06a3783c03f53edf9f9601ee9b0c3141db622b7c
        url: https://github.com/stolostron/cluster-image-set-controller
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/clusterlifecycle-state-metrics-mce-29@sha256:590c466eb36c3aad8adeb176464c671cfd57bcf9eddb48db5336760da9143fa3
    name: clusterlifecycle-state-metrics-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: build/Dockerfile.rhtap
        revision: b83cdc2a9e2653138b66713cb01fb94ad6c56cf4
        url: https://github.com/stolostron/clusterlifecycle-state-metrics
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/image-based-install-operator-mce-29@sha256:b1ad54e9e8709f5af1e7ddcf67071fd4a2d9be95abab59e950030521cfc02cdc
    name: image-based-install-operator-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile
        revision: 0589c388bbd645033cfa8b4dc9bfb6d9667b8899
        url: https://github.com/openshift/image-based-install-operator
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/multicloud-manager-mce-29@sha256:e466374e4e2e4861861afe48d33d511ff7364f83e88225aa11f7dce3fe6662a5
    name: multicloud-manager-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: cb753172342f4dfdd7e022b24ffbda99c4aa41ed
        url: https://github.com/stolostron/multicloud-operators-foundation
  - containerImage: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/provider-credential-controller-mce-29@sha256:afcebe18da2cc443eda7aad1c050183debedeecac26c333ff88302f4d33dc486
    name: provider-credential-controller-mce-29
    source:
      git:
        context: ./
        dockerfileUrl: Dockerfile.rhtap
        revision: c618f75439aa13f19607ef4a9c9e61af0124eaa4
        url: https://github.com/stolostron/provider-credential-controller
status:
  conditions:
  - lastTransitionTime: "2025-09-09T19:09:16Z"
    message: The Snapshot's component(s) was/were added to the global candidate list
    reason: Added
    status: "True"
    type: AddedToGlobalCandidateList
  - lastTransitionTime: "2025-09-09T19:10:06Z"
    message: Snapshot integration status condition is finished since all testing pipelines
      completed
    reason: Finished
    status: "True"
    type: AppStudioIntegrationStatus
  - lastTransitionTime: "2025-09-09T19:10:06Z"
    message: All Integration Pipeline tests passed
    reason: Passed
    status: "True"
    type: AppStudioTestSucceeded
  - lastTransitionTime: "2025-09-09T19:10:06Z"
    message: The Snapshot was auto-released
    reason: AutoReleased
    status: "True"
    type: AutoReleased
