FROM scratch

COPY ./manifests /manifests
COPY ./metadata /metadata
COPY ./extras /extras

LABEL com.redhat.delivery.operator.bundle="true" \
      cpe="cpe:/a:redhat:multicluster_engine:2.6::el9"

LABEL com.redhat.component="multicluster-engine-operator-bundle-container" \
      name="multicluster-engine/mce-operator-bundle" \
      version="${BUNDLE_VERSION}" \
      summary="multicluster-engine-operator-bundle" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images" \
      io.k8s.display-name="multicluster-engine-operator-bundle" \
      io.k8s.description="Operator bundle for Red Hat Multicluster engine" \
      maintainer="['acm-component-maintainers@redhat.com']" \
      description="multicluster-engine-operator-bundle" \
      konflux.additional-tags="v${BUNDLE_VERSION},snapshot-${SNAPSHOT_NAME}" \
      vendor="Red Hat, Inc." \
      url="https://github.com/stolostron/mce-operator-bundle" \
      release="${BUNDLE_VERSION}" \
      distribution-scope="public"
