name: Gen Latest Dev Snapshot

on:
  workflow_dispatch: {}
  schedule: 
    - cron: '0 5 * * *'   # 1:00AM EST every day (UTC-4)
    - cron: '0 11 * * *'  # 7:00AM EST every day (UTC-4)
    - cron: '0 19 * * *'  # 3:00PM EST every day (UTC-4)
    - cron: '0 23 * * *'  # 7:00PM EST every day (UTC-4)


jobs:
  snapshot:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false # If one jobs fail, we still want the other jobs to run.
        matrix:
          branch: ['backplane-2.6', 'backplane-2.7', 'backplane-2.8', 'backplane-2.9', 'backplane-2.10']
          include:
            - branch: backplane-2.6
              release-plan: "dev-publish-mce-26"
            - branch: backplane-2.7
              release-plan: "dev-publish-mce-27"
            - branch: backplane-2.8
              release-plan: "dev-publish-mce-28"
            - branch: backplane-2.9
              release-plan: "dev-publish-mce-29"
            - branch: backplane-2.10
              release-plan: "dev-publish-mce-210"

    steps:
      - name: Checkout tooling branch
        uses: actions/checkout@v3
        with:
          ref: tooling

      # Run the snapshot collector script and create a PR with the latest snapshot in the correct branch
      - name: Run snapshot collection and file handling
        env:
          SA_TOKEN: ${{ secrets.KONFLUX_SERVICE_ACCOUNT_TOKEN }}
        run: |
          chmod +x snapshot-collector.sh
          ./snapshot-collector.sh ${{ matrix.release-plan }} "$SA_TOKEN"

      - name: Generate GitHub token for workflow actions
        id: gen-workflow-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.WORKFLOW_BOT_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # Create Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "update-snapshot-${{ matrix.branch }}"
          base: "${{ matrix.branch }}"
          delete-branch: true
          title: "Gen Latest Snapshot [${{ matrix.branch }}]"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          token: ${{ steps.gen-workflow-token.outputs.token }}
